### ISSUE TITLE
Feature-request: Option to limit download-rate

### ISSUE THREAD

**Issue by jolpe** [aajanki/yle-dl#100]
As someone who doesn't have fibre 100M internet bandwidth, actually quite the opposite, I could appreciate if yle-dl had an option to limit the download-rate, something like wget --limit-rate

Please?

**Comment by aajanki** [comment]
I added an option `--ratelimit 100` for setting the maximum bandwidth consumption in kB/s.

There is also the `--maxbitrate low` option for downloading a lower quality version of a stream.

**Comment by susundberg** [comment]
Hi! 

The --ratelimit sounds excatly what i have been looking for -- i trickle outside of the program to limit the rate. I find it hard to belive this is working properly; i tested with very low rate "--ratelimit 10" and it still seems to download with almost if not full speed. And the KB reading that it prints as progress is increasing way way faster than the limit

Anyway, great program, workaround is limit the download outside, with say 'trickle'

**Comment by aajanki** [comment]
Rate limiting doesn't work with audio streams. I'll check if rtmpdump supports rate limiting and, if not, at least add a warning message explaining that the limit will be ignored when downloading audio.
