### ISSUE TITLE
Can't download since Areenan updated

### ISSUE THREAD

**Issue by kurtlager** [aajanki/yle-dl#102]
Hi,

Since areenan updated yesterday I can't no longer download new episodes. E.g. the series 

http://arenan.yle.fi/1-3341647
http://arenan.yle.fi/1-3114355

I can download older episodes, but not the latest published today using yle-dl  2.16

**Comment by mulecat** [comment]
The older videos with flash or html players can still be downloaded

http://areena.yle.fi/1-2883105 (flash)
http://areena.yle.fi/1-3917899 (html)

Only new videos fail to download. Yle-dl 2.16

**Comment by gunnar12** [comment]
Since areenan updated yesterday/

Yep, not ADOBEHDS anymore on at least TEEMA/FEMMA (including the live stream since beginning of month).
Figured out FFMPEG.exe can do the download but needs to get the URL with parameters to get the "manifest" which now is "index" from "somewhere".
I quickly used windows IDM , a good download prgrm, to both download and get the URL-parameters, which also works with "plain FFMPEG -i URL etc outfil".
(checking how easy to add to my own custom yle-dl)

Btw, YLE added  one higher resolution as a bonus, hehe

**Comment by gunnar12** [comment]
flash or html players/

Btw, seems one can "detect" which one in the beginning, at least wth my windos-firefox setup and areena player

- flash makes a round rotating circle (waiting for first video fragments)
- html (dwnladable wth ffmpeg) a slightly smaller "flower" or "wheel with spokes"

**Comment by tlikonen** [comment]
Yes. I noticed it too three days ago or so. Yle-dl doesn't work anymore on (some) new Areena videos. Here's one short example: http://areena.yle.fi/1-1407680

**Comment by aajanki** [comment]
There is now an initial support for the update Areena streams.

Caveats: ffmpeg is required for the new type streams, the downloaded streams are of medium quality (and the `--maxbitrate` option is ignored), some older streams might stop working (please, report if you find any). I'm working on these issues.

**Comment by localdoc** [comment]
So I tried the new version. At least with this stream http://areena.yle.fi/1-3988436 I got an error as follows:

[mp4 @ 0x270cf80] Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)
av_interleaved_write_frame(): Operation not permitted 

Adding the suggested paramteter to the ffmpeg arguments seems to produce a valid mp4 file as a result, but no subtitles are downloaded.

**Comment by tlikonen** [comment]
The same AAC error here.

Also, there's a problem if the filename contains ":" character because FFmpeg's input and output are URLs. Filename URLs should start with "file:" and followed by normal file system path name. Only then path names work reliably with arbitrary characters. See manual page ffmpeg-protocols for more info.

**Comment by aajanki** [comment]
I fixed a few things:
* aac_adtstoasc
* The highest quality available is now downloaded by default, and --maxbitrate works
* ffmpeg was refusing to write filenames containing colons

The subtitles are not being downloaded, yet.

**Comment by kurtlager** [comment]
I can now download the examples I started this thread with. 

Thank you

Kurt

**Comment by teroyks** [comment]
Downloading the file in the first post works, but others do not, for example: http://areena.yle.fi/1-4072204

All it does is says "Stream saved to <file>", and saves a 168-bit file.

**Comment by aajanki** [comment]
Subtitles are fixed on the latest master.

@teroyks, I'm able to download that stream. Can you pull the latest code and post the output of `yle-dl -V http://areena.yle.fi/1-4072204` if it still doesn't work for you?

**Comment by teroyks** [comment]
I have the latest homebrew version.

[This is the output I get.](https://gist.github.com/teroyks/09d401d64a3cd16a82f92518f2d5ad0d)

**Comment by aajanki** [comment]
I just released yle-dl 2.17 which should be able to download all Areena videos.

https://github.com/aajanki/yle-dl/tarball/2.17

**Comment by tlikonen** [comment]
Huge thanks! Seems to be working nicely.

**Comment by teroyks** [comment]
Thanks for the quick response! Download now works.
(At least the build on Homebrew outputs quite a lot of debug info to the terminal, but that's not such a big deal.)

**Comment by EliasA** [comment]
Another new issue. yle-dl version 2.20. Trying to download http://areena.yle.fi/1-3518036 gives the following error: https://pastebin.com/4KZfdyM7

**Comment by aajanki** [comment]
@EliasA, can you try again on version 2.21 (or on the latest master branch)? It uses a different way to download the stream and should fix this issue.
