### ISSUE TITLE
WishlistLive

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#103]
Hi and thanks for YLE-DL.

As some videos not archived on Areena Ive been grabbing the live stream.

Demands minor change to ADOBEHDS but whatabout

1. Yle-Live now keeps fragments for last 4 hours., one can scroll back with ordinary flashplayer.
That is, no need to use alarm clock or similar to grab it upto "4 hours ago".
(except for SUORAT programs)

Added a negative offset "correction" to when ADOBEHDS gets the first initial fragment number.
Seems a fragment is always 6 seconds but I guess the info is somewhere in the meta data if one searches.

2. same for FFMPEG??
 Spent some time searching for a standard input argument which wld " do the same", havnt found one.
My old-old compilation setup for (windows XP-Vista, not "supported" anymore) FFMPEG doesnt work anymore, so I havnt yet tried finding a pl;ace and changing FFMPEG code.

3. Another possibility that I have done with both batch file and windos task manager is to set start-time for starting yle-dl. Buy then no easy way for end-time.
Can you easly add a feature like that to yle-dl, that it sets up another yle-dl which gets a start and end-time.?

PS Me thinks both ADOBEHDS and FFMPEG shld have that "start X hours ago fragment" as a standard argument.

PPS forgot one series-feature-wish:
Areena used to have different time-info for (almost) all series and the time went into the filename.
Easy to avoid downloading the same file twice,
However, now they regularly  publish 4-12 programs in an "instant series", with same "-time" for all.
Easily solved by adding that "1-12345" code to the filename in yle-dl, although looks bad.
Same similar thing when Areena suddenly adds a second or two to that "-time", one cld then go by that "1-1234" code to detect "alrdy downloaded".

Or as another thing Ive added, put all meta-data in a filename.1-1234.info.txt file

PPPS I also changed ADOBEHDS to not use yle-live filename but askl me for the name when grabbing a live program which started an hour or so ago.

**Comment by gunnar12** [comment]
Hakuammunta, questionlist.

AS an old assembly, barely C-guy I cant really stand nor handle python file and string handling. same for php.

Anyway, managed to add windows-code for your yle-dl to pling, stop and ask for a console input.
Even got the most important,, a plinging timeout and default action "if  Im not there" wihin seconds or ,imutes.

However, wld need similar for ADOBEHDS php, havent found one. In this talk-to-keyboard case php is worse than python?

Specifically change number of download "ports", parallell 1-8 or more, "pn the fly".
 I use that paralell for fixed boost of live streams "competing for ADSL bandwidth" with simultaneous archived streams that use 1 or max 2, Kindo priority (can luckily ctrl-s pn-off, pause-start console for ADOBEHDS)

Same thing to "speed up" and "slow down" these semi-live streams while they catch up from 1000 fragments back.

All this in "hated windows" where I am stuck bc of the IDM download Manager

any windos php-trick??

**Comment by aajanki** [comment]
> start a live stream recording up to 4 hours in the past

The support for this would need to be implemented in AdobeHDS (and/or ffmpeg, youtube-dl) like you said. I'm don't find this feature so important that I would be motivated to do that myself. So unless somebody else gets this included in AdobeHDS, this won't be supported in yle-dl.

> an end time for the recording

The master branch now has `--duration` switch for limitting the length of recording. For example, `yle-dl --duration 60` will stop the recording after downloading the first 60 seconds of a stream.

You can implement a small script for converting the end time to duration.

> same timestamp for several episodes of a series

Don't they still have episode numbers (S02E05) and episode titles that separate them form each other? At least in all cases I have seen so far each episode file gets an unique name. If you have encountered series where this is not the case, can you post an example URL in as a new bug report (easier if the different bugs are discussed as separate issues).

> changing AdobeHDS to ask for a file name

You can override the automatically chosen file name using the `-o` option for yle-dl. No need to patch AdobeHDS.

> php

Sorry, can't help there.
