### ISSUE TITLE
-o argument no longer works for me

### ISSUE THREAD

**Issue by KatseNarniaan** [aajanki/yle-dl#105]
When I use yle-dl without the -o argument, it downloads just fine, but when I add the -o argument I get an error.

[withouttheargument.txt](https://github.com/aajanki/yle-dl/files/1083091/withouttheargument.txt)
[withtheargument.txt](https://github.com/aajanki/yle-dl/files/1083092/withtheargument.txt)

**Comment by KatseNarniaan** [comment]
Ok, so the -o argument works if I use a name with a file name extension.
In the past yle-dl added the file name extension automatically. In the past the extension was .flv, is it now always mp4, or does it depend on what it is downloading?

**Comment by oqibidipo** [comment]
It depends on what you are downloading.
For example, the latest Dr Who (s10e10) is .mp4, but the previous one is .flv.

**Comment by aajanki** [comment]
I fixed it to automatically append the file name extension.

New videos are downloaded as .mp4 and the older ones as .flv.

**Comment by KatseNarniaan** [comment]
Thanks!
