### ISSUE TITLE
Unable to download from yle areena

### ISSUE THREAD

**Issue by MakeLord95** [aajanki/yle-dl#106]
Trying to download http://areena.yle.fi/1-4072204 and all I get is
make@ubuntu:~/Downloads$ yle-dl http://areena.yle.fi/1-4072204
yle-dl 2.17: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2017 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3
Subtitles saved to Doctor Who: S10E10: Valonriistäjä-2017-06-18T06:00:00+03:00.fin.srt
Output file: file:Doctor Who: S10E10: Valonriistäjä-2017-06-18T06:00:00+03:00.mp4
Failed to execute ffmpeg -y -i http://cdnapi.kaltura.com/p/1955031/sp/195503100/playManifest/entryId/1_4uyobrq0/flavorIds/0_63ospxsy/format/applehttp/protocol/http/a.m3u8?referrer=aHR0cDovL2FyZW5hbi55bGUuZmk=&playSessionId=11111111-1111-1111-1111-111111111111&clientTag=html5:v2.56&preferredBitrate=600&uiConfId=37558971 -bsf:a aac_adtstoasc -vcodec copy -acodec copy file:Doctor Who: S10E10: Valonriistäjä-2017-06-18T06:00:00+03:00.mp4
No such file or directory

Any help?

**Comment by hharsunen** [comment]
install ffmpeg

**Comment by MakeLord95** [comment]
Ok, now it's working. Thanks!
