### ISSUE TITLE
subtitles not downloaded

### ISSUE THREAD

**Issue by aholatom** [aajanki/yle-dl#109]
I noticed subtitles are not downloaded for this:
http://areena.yle.fi/1-2490272

**Comment by aajanki** [comment]
I got subtitles when I tried just now. Which yle-dl version are you using? Can you post the output of `yle-dl --debug http://areena.yle.fi/1-2490272`?

**Comment by aholatom** [comment]
Ooops... seems I used old version 2.16.   I did download latest 2,21 and did "sudo python setup.py install" but seems that did not install anything (another issue maybe).   Now with manually copying and running 2.21 the subtitles are downloaded.  Sorry and Thanks..
