### ISSUE TITLE
Using mencoder instead of ffmpeg

### ISSUE THREAD

**Issue by clbr** [aajanki/yle-dl#111]
I hacked my copy to use mencoder instead of ffmpeg. In case you'd like to add it as an alternative, here are the options I used:

```
args = ['mencoder', '-ovc', 'copy', '-oac', 'pcm', '-of', 'lavf',
                '-lavfopts', 'format=matroska',
                self.stream.to_url()]
```

**Comment by aajanki** [comment]
Does mencoder work better than ffmpeg?

I'd like to support only one option, either ffmpeg or mencoder, unless there is a reason to support both. Supporting both complicates code and increases maintenance burden.

**Comment by clbr** [comment]
They use the same code for HLS streaming. It was just a matter of preference, as I don't have ffmpeg installed, but I do have mencoder. (mplayer/mencoder builds ffmpeg statically by default)

**Comment by gunnar12** [comment]
They use the same code for HLS streaming/

Maybe there is hope??
Seems impossible to just tell some library to download the whole video to the HD, disconnects or gets stuck.
Instead concentrate on downloading just a segment (packet, chunk, blabla), one-at-a-time, to HD, under  "careful supervision" that it actually gets done correctly, timeouts, retries, etc.
Only then feed the segment, from HD-file, to the decoder.
This makes "total retry" and resume possible, by first checking HD for the segment, if it is alrdy there, correct and only if not downloading it.

Unluckily FFMPEG, at least on windows, just stops downloading fairly often, in the middle.
The good thing is that the connection is not disconnected, and using TCPVIEW.exe one can see two connected sockets.
- one doing CLOSE-WAIT
- the other doing the actual segment downloading, ESTABLISHED, but nothing happens.

By "close connection" of #2, ffmpeg at least continues to the next segment. 
Gives some error message on the datastamps in the video, but that is max a missing 10 sec (length of segment), not the whole video.

I guess aajanki has run into similar ffmpeg problems running linux, and worst, the present "python" downloader seem to do the same?? (but additionally disconnects everything)
Guess all three use same basic linux urllib code handling the socket traffic, protocol where it gets stuck??

PS tried to track down the HLS.c code to find out where it "didnt return" (wthout getting a windows debugger to work), but gave up when HLS went into urllib funnctions, switched to pure linux.
Same, or similar problem!

**Comment by aajanki** [comment]
I'm closing this issue. It would be nice to support both mencoder and ffmpeg, but I guess that so few users have just mencoder installed that it doesn't warrant complicating the code.
