### ISSUE TITLE
error(104, 'Connection reset by peer')"

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#112]
Getting lots of these

---
raise ChunkedEncodingError(e)
ChunkedEncodingError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))
---

From somewhere deep in phyton2.7.  urlib3??
"Often" means every 3-4de download, evry 2-3 hour.

Q1: Started running 2-3 yle-dl frm URL-lists, UBUNTU16 at same time, is that a problem, internal cookies,etc (as orig ADOBEHDS)
Difference if in same or different directory?

Q2 YLE-DL using this python library downloader seems to retry once (and cannot resume),then give up (when from URL-list) havnt gone through code yet.
Any advice, pointer to where to "souind alarms, ring bells,try even more times"

Q3 Replace this URLLIB3 RAW?? downloader wth ffmpeg,etc where one cld at least hope of debugging the problem,

Seems they all are beaten by ADOBEHDS PHP-downloader strategy, who takes N whole numbered chunk-packets at a time (500B - 6Mb), even verifies, redownloads and only then starts decoding them/it.
Makes retrying , redownloading only that packet and resume from that packet possible.

AFAIK, the whole idea to get these streams working on mobile smart phones, including switching to lower resolution.  latest 4 hours buffered in server, switching 5G network, etc (esp for live streams)

Gunnar

PS plzplz, print the name of the lousy downloader when error, so that YLE-DL doesnt get the blame!
Add "AGAIN" after the first time. (works wonders!)
No magic that Olkiluoto still isnt up and running! AGAIN!

OK!, maybe Olkiluoto uses Python
https://www.google.fi/search?q=ChunkedEncodingError&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&dcr=0&ei=AFG1WcfEFcSq8wfc35zAAQ

PPS cpl hours later. This "internal" downloader can also "just sit there", doing nothing for half an hour.
Maybe yle-dl could work as watchdog?

**Comment by gunnar12** [comment]
Another 20-30 hours, now as only process running on cptr, not 2-3 plus browser as before.
However, also WireShark, trying to catch that "break-moment" from there.

Only 1, maybe 3 "tot stuck-freezes" but probably almost as many "failed" for above same error, which obv might mean almost anything when it is handed up from the depths of the sockets.

That is, stuck and fail happens more often the more "wild traffic"? (which is to be expected

- ffprobing files of no help, only helped for ny own setup with ffmpeg.
Present yle-dl produces "clean" files even if "failed"
After some googling, seems only solution to have ffmpeg recode the whole file, ridiculous.
SHld be a way of just reading it and check everything down the video headers, but not decoding and encoding it

Gunnar

PS running a ADSL router and a 1GB switch, varying numbers of othr cmputers,
Sudden changes in their downloads seem to cause "failed", but hasnt for many years nor now with php adobedhs.

PPPS Any pointer to where you set up the internal downloader, args, etc. Your code has really been rewritten in last year (thanks)?
Debugging, can one really debug this python efficiently on Ubuntu?? any pointer and helper.
(10 yrs since I debugged on linux, straight c code, few libraries)

**Comment by gunnar12** [comment]
Is this internal python downloader based on Kaltura code, libraries and APIs?

**Comment by gunnar12** [comment]
1st "new error code" 504 crash, gateway timeout.
on 2de try after the normal 104 fail

HTTPError: 504 Server Error: Gateway Time-out 

traceback attacched
[gsteway.txt](https://github.com/aajanki/yle-dl/files/1303608/gsteway.txt)

**Comment by gunnar12** [comment]
Where it gets stuck, although the problem has already happened, like Olkiluoto.
urllib3  response.py
 doing reads down to ssl,py

      with self._error_catcher():
            if amt is None:
                # cStringIO doesn't like amt=None
                data = self._fp.read()
                flush_decoder = True
            else:
                cache_content = False
                data = self._fp.read(amt)
                if amt != 0 and not data:  # Platform-specific: Buggy versions of Python.
                    # Close the connection when no data is returned
                    #
                    # This is redundant to what httplib/http.client _should_
                    # already do.  However, versions of python released before
                    # December 15, 2012 (http://bugs.python.org/issue16298) do
                    # not properly close the connection in all cases. There is
                    # no harm in redundantly calling close.
                    self._fp.close()
                    flush_decoder = True

**Comment by aajanki** [comment]
"Connection reset by peer" usually means that the network connection got disconnected during the download. It suggests that this might not be a software problem but a network connectivity issue. Do you use WIFI, VPN or a proxy? If yes, can you try a direct connection?

To test if an alternative, non-Python downloader functions better, can you try the following? Print the video URL using the `yle-dl --showurl` command line option and feed the URL the wget or curl. Actually, you can do this with one command:

```
wget -O testi.mp4 $(yle-dl --maxbitrate 200 --showurl https://areena.yle.fi/1-3927423)
```

Does this download the video more reliably?

Note, that this only works for HTML5 videos. Most of the latests Areena videos except for the news are HTML5. You know that the video is HTML5, if the `--showurl` outputs something starting with "https://cdnapisec.kaltura.com/".

The "504 Server Error: Gateway Time-out" is probably a symptom of a different problem. Something went wrong on the Yle server. Most likely one of the Yle backend servers was down.

**Comment by gunnar12** [comment]
Difficult to test as the disconnect (now) happens only once evry 2-5th hour.
(is it possible to get python plus request, urllib1,2,3 libraries to run under dbg? all need to be compiled with debug-symbols,etc "the same way")

However, been running a long radio-rtmp-download at the same time and keeps running OK while yle-dl gets the "peer discinnect".

Note, I am running yle-dl 24/7 to catch up with old missed days and failed programs.
(the problem to find them missed and half-failed, a more or less manual pain, but now I added an OK-file for the future)

Gunnar

PS my more general point that the download shld be able to handle "minor errors", do resume, etc.
Its kindof 20 years backwards not to be able to do it.
That is, maybe alrdy exists in the requests library??
Start from video, container timestamp or even frome a specific byte if it just downloads like protocol-free stream of bytes.

**Comment by gunnar12** [comment]
wget, curl, showurl, ??

They wld be automated list-possible wth slight modification to the pre- or post-command, yes?

**Comment by aajanki** [comment]
HTML5 video is just regular file download over HTTP and Areena servers seem to support the standard HTTP resume (the Range header). I haven't had time to implement it yet.

I'm currently considering switching from requests to wget because wget offers retry and resume support out of the box.

You can run yle-dl on Python debugger like this: `python -m pdb yledl/yledl.py`. Or did you mean debugging the low level C code? I guess you can install debug build of Python and run that on gdb, but they you need to figure out where to set breakpoints (that is which C functions the Python code calls).

**Comment by aajanki** [comment]
The version at Github repo is now using wget for downloading HTML5 streams. Benefits:
- retry failing HTML5 stream downloads (untested, because Areena is too reliable)
- retry if no data has moved in 20 seconds
- possibility to continue a partially downloaded stream (if --resume is given on the yle-dl command line)

Implementing automatic retry on HDS would take more work. I'm not planning to implement it because I think manual --resume is a good enough workaround.
