### ISSUE TITLE
 retry

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#114]
What abt a simple watchdog thread, interrupt routine, reliable timer timeout process, whatver its called in python, (easy tp test by pulling ethrnet plug, or simplest, just ctrl-S on terminal window, shows other timeouts too from the python cellar)

- to detect "no data is moving" down in the cellar, for 1 or even 10 minutes.
Could be active only when URL-list used, with a --timeout NN at first line

- A pause function wld help too, but might mess up watchdog

PS havnt looked enough into them failed-then-retry. Any pointer? 
Seems to be many at different levels?
Some kindof "until success" but others not.
Havnt seen more than one retry in my "peer diconnects".
(which php adobehds never gets, maybe a 104 a month, which one retry takes care of)

Some kind of "program-title.OK" file at RD_SUCCESS which seems to be reliably detected.

**Comment by aajanki** [comment]
There is now a timeout that interrupts yle-dl if no data has moved in 20 seconds.

I don't plan to implement pause functionality. In what kind of use cases you need pause?
