### ISSUE TITLE
[Wishlist] Please provide SHA-256 message digests for stable versions

### ISSUE THREAD

**Issue by PinkyBuffel** [aajanki/yle-dl#115]
This issue does not really belong here (to GitHub) since stable yle-dl source code packages are downloaded from pypi.python.org .

Anyway, could you please provide SHA-256 or SHA-512 message digests for released .tar.gz packages on [yle-dl home page](https://aajanki.github.com/yle-dl/index-en.html).

Thanks for consideration.

**Comment by aajanki** [comment]
Thanks for the suggestion. I included an MD5 digest to the home page.
