### ISSUE TITLE
added timeout to urlretrieve parameters

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#118]
- added timeout to urlretrieve parameters.

Doesnt timeout uplugged ethernet , except after plugging back.
Seems to activate lots of timeouts and also retires, full competition in throwing errors exceptions around?

- one retry seem to be default in python request library, need to go adapter to increase?
(lotsa complaints)

Question, is this python html5? request method downloding the whole video without segment-list, segments, fragments etc?? Contrary to HLS FFMPEG on same YLE video?

Bad standard, if one always have to restart from zero! 
Or is it not yet implemented in pythin requests, or difficult to piece together correctly?

Gunnar

**Comment by aajanki** [comment]
I added a timeout to all HTTP operations and a retry to API requests. I didn't yet add retry to video stream downloads because, as you said, it doesn't make sense to always restart from the beginning. Implementing a proper resume from the middle of a file takes more effort, but I'm working on it.
