### ISSUE TITLE
What a JOY!

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#119]
almost 24h without any BADDIE!, just OKOK!

Note how easy to visually  check!
(with this as reference I will now switch back to cluster-4196 chunks, maybe something else, some akamai servers too weird wth adobehds, max speed some 50kBps, but next segment comes from different IP adress full speed)

![whatajoy](https://user-images.githubusercontent.com/16590355/30815423-d668cec8-a21b-11e7-94ba-d48bdeb39276.jpg)

PS times are "modified", note order, Linux finishes writing minimal OKOK  file before emptying the cache of the MP4 file tail.

**Comment by gunnar12** [comment]
Find the BADDIE  (changing it to more visual 
![findthebaddie](https://user-images.githubusercontent.com/16590355/30815499-155920a6-a21c-11e7-9562-24a25841e49b.jpg)
BADBADBAD)

**Comment by gunnar12** [comment]
Switched back to chunksize 4196..

Bad hair day or something, but 2 disconnects in 3 hours,

**Comment by gunnar12** [comment]
OK, finally spare time, found this HLS 10s segnments and protocol-free? bitstream HTML5.
LeadThis or That to Kaltura server.

However, both must have a command for starting video on certain time, although it onclides finding best segment, closest timestamp in FFMPEG HLS code.
Cldnt find this command from web-published YLE-API, but it must be there considering normal browser playback (or always doing HLS then, picking 10s segments? Wireshark job)

That is, first the problem of resuming from a certain position and then how to piece together the old and new data.
Strange if not in standard..considering 5G switching of radios, networks, streaming servers and whatever..

**Comment by aajanki** [comment]
For playing back HLS starting from a certain time, you need to select the closest 10s segment and start downloading from that (like you speculated). I think that is what Areena does.

I don't know how to start a HTTP MP4 from a time position. Maybe you should ask this on StackOverflow? It is possible to resume downloading from a certain _byte_ position using the HTTP [Range header](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.35).
