### ISSUE TITLE
Start recording the "live" streams anywhere during the last 4 hours

### ISSUE THREAD

**Issue by aajanki** [aajanki/yle-dl#125]
In the Areena web player, the live streams maintain a backbuffer of last 4 hours and the playback can be started anywhere during this buffer. Yle-dl should also support starting the download from any point during the stored history.

**Comment by ExTechOp** [comment]
Do "live" stream downloads work even with the current setup, when you have to run them at 1:1 with the "live" performance? I tried recording the one Palmu movie which Kassila hasn't released for YLE Areena except for this kind of single performances:

```
% yle-dl -o Komisario_Palmun_erehdys.mp4 https://areena.yle.fi/1-607065
yle-dl 20191022: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2019 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

Output file: Komisario_Palmun_erehdys.mp4
^C
```

(Download proceeded at 1:1 with the "live" performace, but I interrupted the stream download at around the 01:50:00 mark, since the movie is only 1:42:00 long + the web page said it had ended)

```
% ls -l Komisario_Palmun_erehdys.mp4 
-rw-rw-r-- 1 users users 887881776 Jan  1 14:16 Komisario_Palmun_erehdys.mp4
```

End result is unfortunately unplayable.

**Comment by aajanki** [comment]
It is possible that there are different types of live streams and some are broken but at least two live streams that I tested just now (ice hockey on the Yle Areena "channel" and a cooking show on Yle Fem) produced playable files (even though I interrupted the recording with Ctrl+C).

**Comment by lsolin** [comment]
Can you get a high resolution video? I can download a tv-channel live stream with yle-dl 20191022, but always end up with a 704x396 video.

**Comment by ExTechOp** [comment]
Quick tests on the interrupted live file seem to indicate the issue is that the "moov atom" never got written to the file?
   
```
% /usr/bin/ffmpeg -i Komisario_Palmun_erehdys.mp4 -vcodec copy -acodec copy -scodec copy -movflags faststart KPE.mp4 
ffmpeg version 4.1.4 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --extra-ldflags='-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ' --extra-cflags=' ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-libjack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzvbi --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-libmfx --enable-runtime-cpudetect
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x563d0ad9fcc0] moov atom not found
Komisario_Palmun_erehdys.mp4: Invalid data found when processing input

% /usr/bin/qt-faststart Komisario_Palmun_erehdys.mp4 KPE.mp4
ftyp          0 32
free         32 8
mdat         40 0
last atom in file was not a moov atom

% /usr/bin/MP4Box Komisario_Palmun_erehdys.mp4 -out KPE.mp4                             
Truncated file - missing 0 bytes
Error opening file Komisario_Palmun_erehdys.mp4: IsoMedia File is truncated
```

The Google cargo cult lore seems to suggest an utility called "untrunc", but I don't think I'll start compiling random programs from the net in an attempt to correct poorly defined error conditions.

**Comment by aajanki** [comment]
@lsolin, that is the only resolution that yle-dl is currently able to detect for live TV. I opened a new issue #227 on detecting higher resolutions.

**Comment by aajanki** [comment]
@ExTechOp, I don't know how to fix the missing moov atom, sorry.

What is strange is that why did yle-dl even save it as an .mp4 file. All live streams that I have tested are of the kind that gets saved as an .mkv. MKV doesn't suffer from the moov atom issue. Just out of curiousity, do you get .mp4 files anytime you try to record live broadcasts or was Komisario Palmu a special case?

**Comment by ExTechOp** [comment]
> What is strange is that why did yle-dl even save it as an .mp4 file. All live streams that I have tested are of the kind that gets saved as an .mkv. MKV doesn't suffer from the moov atom issue. Just out of curiousity, do you get .mp4 files anytime you try to record live broadcasts or was Komisario Palmu a special case?

That's easy to answer: because I explicitly asked for mp4, as you can see from the command line. I'll have to try to let it make the default mkv file the next time and see what happens.
