### ISSUE TITLE
Download fails

### ISSUE THREAD

**Issue by nms68** [aajanki/yle-dl#129]
Download fails. Previous episode can be downloaded, but not this one.

$ yle-dl http://areena.yle.fi/1-4181979
yle-dl 2.27: Download media files from Yle Areena and Elävä Arkisto
[removed]
Proxy request sent, awaiting response... 404 Not Found
2017-11-02 13:48:13 ERROR 404: Not Found.

**Comment by gunnar12** [comment]
http://areena.yle.fi/1-4181979

Yep, fails 404 with 2.26 too, but ok forearlier Jakso 4.

Using a (Windows) FireFox addon gives slightly different URLS to the video segments,
Search swedish SVT "piratkopiera" in FireFox addons, detects HLS streams.
Small pop-up window for click-copy-paste and settings for having pre-made ffmpeg command.
(need ffmpeg installed) 
Similar to old reliable "HDS Link Detector" (adobeHDS)

But doesnt pick program name, info ,etcetc like yle-dl,

The two, 
Tested both, both at least start receiving segments with ffmpeg (to index.ts file)
(URLs, index.m3u8 are links to a segment-file with all 10s segments of the program)

https://ylekaod-a.akamaihd.net/s/enc/fhls/p/1955031/sp/195503100 ..... a.mp4/index.m3u8
https://ylekaod-a.akamaihd.net/s/fhls/p/1955031/sp/195503100 ..... a.mp4/index.m3u8

Gunnar

PS I think this SVT piratkoperaadd-un picks file name from SVT web page or similar. 
For Areena the video just goes into index.ts if one doesnt manually change the output name every time.

**Comment by niom** [comment]
I went down to version 2.23 and that still seems to work. So use 2.23 as a work-around for now.

**Comment by nms68** [comment]
Unfortunately 2.23 does not work either for that newest episode. Previous episode downloads with 2.23 and 2.27.

**Comment by niom** [comment]
Ok I had problems downloading https://areena.yle.fi/1-2477331 with 2.27 that then worked with 2.23.

**Comment by hugovk** [comment]
Maybe the lack of brackets around the output filename?

**Comment by gunnar12** [comment]
I had problems downloading/

Add --verbose or -V  to commandline and you will see more info, for example the links wget tries to access and why it fails.
The second half of URL is just kindo cookie,etc stuff that varies 
Actual important URL thing starts https and ends with name/a.mp4.

Not that it helps you to download but easier to post better error message

OOOOPPPSS  You dont dow;load to a NTFS windows formatted harddisk, do you??
Windows NTFS,FATcant take the colon in the filename, used in the time part.
But that shld make all downloads fail??

add --vfat to command line to replace letter that windows cant handle.
 
Gunnar

" No such file or directory".  Although error info , it can be any error-message used for any other error, 
That happens before one sorts out error situations.
Ffmpeg gives it when the interne tlink is wrong, its just a file and directory for ffmpeg.

**Comment by cultor1** [comment]
I use version  2.17 instead of 2.27 to get latest Outlander. I named 2.17 yle.dlf, 2.17 stores HLS-stream using ffmpeg. I had edited it to save ts container to get a better lipsync.

**Comment by aajanki** [comment]
There is now a fix. It will first try to download HTTP stream using wget and, when that fails, it will switch to downloading HLS stream using ffmpeg. So ffmpeg must be installed.
