### ISSUE TITLE
InfoWish and thanks!

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#132]
Just browsed thrgh v2.27 and test driving

No blind overwrite-downloadings of adobeHDS files anymore?
(and file creation date fixed, had to use access date earlier)

Do you actually check for existing file, its meta data duration andthat its last timestamp is appr 2%, 0.98 correct? 

What abt the other sorry standards?

Cant read walk thrgh all that jumping around to functions and objects here and there for all variations, but saw something like this for something.

I guess you dont do it for audio-rtmp, hehe??

Gunnar

OK, one serious wish.
Pick the "end-date" for availabilty. make a spmething-file so that one later on can move all them programs to another hard disk.
Ug;y, but for example a buddy-file name-YLEdate--end-date.txt

I run a custom yle-dl version on "viela ehdit"-list which does that, with the help of some other tools.

PPS Looks v2.27-bad, mainly disconnects and timeouts..
One terminal windows runs v2.26, other rerunning old list wth --resume and v2.27

The try2,3,4,5 just timeout 4-5s or that specific akamaihd server is almost down, maybe tot down.
But rerunning the the list gives a minute or so more data, then disconnects, all reties timeout again

hmm, yep, 2 problem cases of 30 in list, both the same ylekaod-a.akamaihd.net server.
Others work OK.
Other yle-dl tugging along steadily with kaltura server.

Need to find and tweak them timeouts, bc akamai is bad this night.
Me thinks every program-video file shld have some kind of "brother-file" with info and this and that, logs,etc and this "over and done with" thing..

**Comment by gunnar12** [comment]
strange..

Rebooted ubuntu and it seemed to stabilize back to more normal.
Machine really got slow and weird before I did it, esp samba share.

Strange bc I thought Linux wasnt like Windows.
This machine only does yle-dl, sometimes firefox
and samba share!

**Comment by aajanki** [comment]
Yes, you have understood correctly. The HDS downloader checks if a file exist and if the actual duration is at least 98% of duration in the metadata. (Why 98% and not 100%? I noticed that there can be a few seconds mismatch between the metadata and the actual duration.)

All downloaders except the HLS downloader (that is, ffmpeg) should now avoid redownloading an already downloaded file. I didn't check but it is my understanding also applies to audio-rtmps.

Regarding the end date: You can find out the end date and other metadata by running yle-dl with `--showmetadata`. I suggest that you run yle-dl twice, first with `--showmetadata` to save the metadata to a file and then without `--showmetadata` to download the video. Then you can use the content of the metadata file to decide which files to archive.
