### ISSUE TITLE
Read predefined args from a cfg file

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#138]
Continued trying to get yle-dl work on windows, now using PythonWin debugger first time.

Typical for the debugger, or me, cant find out how to set run-arguments.

Python seems to try to do run-arguments in a very high-levelfashion, might be some pre-stuff-add of them into os-provided list or similar.

What abt pre-reading run-arguments from a file, wld be good in normal use too, esp if listed at start of running yle-dl.

should be python standard??

Gunnar

PS Skipping if another YLE-DL downloading:  Seems python in itself doesnt support any check of file descriptor data, had assumed that (platforms).
However, using sys.os or whatever it is it is possible to check if alrdy opened for write.

PPS dpnt resume-check-adobehds:
 was thinking of just an argument --noresumeHDS.
Resume anyway not important for adobeHDS which doesnt fail, (esp if one adds some simple internal retries, and cookie fix), just for wget.
Cant miss it when adobeHDS failes bc tons of fragment files (my custom adobeHDS puts them in a subdir temp)
 If I get a decent debugger working I'll look into
- checking if beginning of videofile, timestamps, content same (deeper parsing of stream)
- same for end of file, need to scan for last video packet timestamps,etc but wld be fast,,

**Comment by aajanki** [comment]
Can't help with the PythonWin debugger but I assume there must be some way of passing arguments.

I can see some value in reading arguments from a file. It would be a way to define default values for arguments. However, this is a pretty low priority for me because it is easy to define an alias.

**Comment by aajanki** [comment]
Arguments can now be read from a config file. The default config file is `.yledl.conf` in the home directory. [Example config file](https://github.com/aajanki/yle-dl/blob/master/yledl.conf.sample).
