### ISSUE TITLE
YLE radio not RTMP anymore, just mp3?

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#143]
YLE radio not RTMP anymore, just mp3?

YLE-DL crashes when trying to build rtmpdump arguments??

add wget downloader alternative?

Gunnar

**Comment by gunnar12** [comment]
temporary YLE problem??
rtmp streams are back

**Comment by aajanki** [comment]
Works for me when I tested a few random programs. Perhaps it was a temporary problem?

If you still come across a non-working radio stream, post a link.

**Comment by gunnar12** [comment]
non-working radio stream, post a link./

Was totally dead with yle-dl (rtmp), an appr 250 long list. Both latest and oldest.
Python complain on missing argument, "app", etc/

But worked in browser and with IDM downloader who picks the mp3 stream. 
ANyway, was "back to normal" when I retried "after midnight".
Has happened temporarily and more randomly (for specific links) before.
