### ISSUE TITLE
Did resume get broken 2.30 or??

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#144]
Did resume get broken 2.30 or something odd in my installations?

Switched customization to 2.30, noticed seconds etc cut, etc

But it seems the resume-function also disappeared for ay least wget files?
Dbl checked instal;ling original, looked in source code, and no resume function?

**Comment by gunnar12** [comment]
Hmm? I have been ctrl-c un middle of a list-download to add or edit the list, then restart the list-download with --resume.
Worked OK as expected, download resumes from my ctrl-c position.

However, testing with some short 10min files with ctrl-c at 2-3 minutes seem to result in ctrl-c leaving a zero length file!! Although I just cld play them 2-3 minutes, before the ctrl-c!!
(Nautilus,etc, file propertirs,etc not reliable as long as file open for writing)

That is, restarting download with resume STARTS FROM ZERO, becaus the file is actually zero-lengrh.
BUT WHO ZEROED IT??

Some new function, or just for small files, that half-done files (by ctrl-c) are deleted or made zerolength?

**Comment by gunnar12** [comment]
OKOK!! Need to ctrl-z and not ctrl-c to avoid deletion of half-downloaded file..

**Comment by aajanki** [comment]
There was indeed a bug in the way Ctrl-C was being handled. It was being interpreted as a failed download  which caused yle-dl to delete the file and start from scracth with another downloader. This is now fixed.
