### ISSUE TITLE
FFMPEG needed, maybe new YLE Handshake

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#147]
Check (still 2 days leftl)

https://areena.yle.fi/1-50000425
or just one day left testilahetykset

https://areena.yle.fi/1-50000421
https://areena.yle.fi/1-50000422

wget is auto-selected by yledl but  doesnt produce mplayer playable"video" (only a well sized file)
Standalone ffmpeg works but I have problems finding right URL, parameters,etc with other old tools.
Sometimes just audio, sometimes just video.

--backend

Cant figure out how to tell or force present yle-dl to use external ffmpeg, althgh it sometimes falls back, if one interrups wget,  to ffmpeg? 
Or automatic, as with Robot and that other weird one?

Cant find, understand how 2..31 does this "parse backends", what order,etc, etc
(code jumps around, small functions, "objects" here and there, too much for me)

Gunnar

PS YLE seems to test multy-language etc, the testlahetykset switch between channels but windows flashplayer seem to be able to pick something.
Havent checked what, maybe server too changed middle of stream??

**Comment by aajanki** [comment]
Which media player and which version are you using? What does ffprobe say about the invalid file? `ffprobe Valtiopäivien\ avajaiset-2018-02-06T14\:35.mp4`

Do you get an usable stream with a lower resolution? `yle-dl --resolution 720 https://areena.yle.fi/1-50000425`

The only way to force yle-dl to use ffmpeg is to tell it use a non-existent executable for wget. Something like `yle-dl --wget asdasd https://areena.yle.fi/1-50000425` Yle-dl will then try to execute asdasd, notice that it doesn't exists, and fallback to ffmpeg. (I should really come up with a nicer way to select between wget and ffmpeg.)

You can always get the video stream URL with `yle-dl --showurl https://areena.yle.fi/1-50000425` and try any media player/downloader.

The two testilähetys links have already expired, but at least this https://areena.yle.fi/1-50000449 downloads and plays fine in VLC 2.2.6.

**Comment by gunnar12** [comment]
Thanks, that wget wrong link trick. Hehe, used the same to disable adobehds but didnt know wget too.
Not time now to check different resolution.

ffprobe complains from the very start for valtiopaivat, overread end of atom and then Unsupported codec.

Seems the very short testilahetykset different from the 2-3h long. If I rememer right there are more of them from the last 1-2 weeks.(but not included in  areena search?)

That valtiopaivat https://areena.yle.fi/1-50000425 the kind of "important" but also also "strange" in that same video also available as old-time flv (same video from quick comparison-watch), different ID on areena.
The old-flv-rule seem to have been YLE news, Astudio, Eduskunta, ie "totally own non-entertainmnet production", different old production team, software. 
Changing now?

**Comment by aajanki** [comment]
I'm closing down this old issue because I'm not able to reproduce it anymore. This might have been the multibitrate stream issue that I fixed recently.
