### ISSUE TITLE
make, egg, install different yle-dl versions?

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#148]
make,install different yle-dl verions?

When trying to debug,etc different versions or slightly modified codes, it wld be great to make and install yle-dlXXX instead of the same yle-dl every time.

Havnt figured out the python make-and-install-egg setting-config-files, esp that egg stuff.
Many "yl-dl" here and there, cant tell if src directory, executabele filename or whatever.
(except for the end thing, found how linux-python starts "first egg in the list", which sometimes goes wrong)

Any help where to change what to make-egg-install "yle-dltest" instead of always "yle-dl"?

**Comment by aajanki** [comment]
You can install different versions at the same time using Python virtual environments:
```
# Do this once to make sure venv is installed:
sudo aptitude install python3-venv

# Do this for each version you want to install:
python3 -m venv yle-dl-2.30
source yle-dl-2.30/bin/activate
pip install yle-dl==2.30  # or whatever version
```
While you have a virtual environment activated, the `yle-dl` command will execute the specific version installed in that virtual environment. To deactive an environment, execute
```
deactivate
```
