### ISSUE TITLE
CMD switch with/without minutes-seconds?

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#149]
If you attack the cmd-parser,etc cld you add a way of using or not using the YLE-minutes-seconds "killer" for the file-names? (btw, YLE is wilder and wilder changing them)

Mainly needed when running a "last chance" list with --resume, to catch any files forgotten or smthing similar, that was downloaded with "old system".

Or best, just check if any video file alrdy exists with name up-to the "killed" minutes and seconds.
(but same extention)

PS yle-dl cmd-parameter parser, python special?, changing this and that here and there, is another part of the code I have problems following

PPS sure been hell keeping up with areena video changes for soon a year,
"Luckily" those who bought latets, best areena compatible internet-smart-TV a year-two ago have an even worse time (minor bugs in firmware updates too,etc)

PPPS If Samsung, both CIA and YLE can turn on TV-set microphone secretly and hear great curses in finnish?
(train their AI-agents when and how to use them correctly at the right moment)

**Comment by aajanki** [comment]
`yle-dl --output-template '${series}${title}${episode}${date}'` will generate name without the time.
