### ISSUE TITLE
Subtitles only?

### ISSUE THREAD

**Issue by hugovk** [aajanki/yle-dl#150]
Other than using `--showmetadata` and extracting links from the JSON, is it possible to download subtitles without downloading video files?

**Comment by aajanki** [comment]
No, there is no options for downloading just the subtitles at the moment.

What is the use case for downloading subtitles without a video?

**Comment by hugovk** [comment]
1. Watching a programme on live television, want to check the name of a person or place just mentioned, it's quicker to search a text file than downloading and scanning a video file.

2. The video is already downloaded, but you now want the subtitles, perhaps from another language. 

3. Would also lend itself to textual analysis of programmes.

**Comment by gunnar12** [comment]
download subtitles without downloading video files?/

Migth be possible uding "trick", by gving yle-dl wrong paths to all downloader used, or possibly used.
I have used it to "unselect, disable" or "force" a specific downloader, wget and adobehds.


Note, Subtitles are downloaded before yle-dl goes for the video.
Hmm. easiest to use ctr-c or ctrl-z at that point? ctrl-c deletes started video file but not subtitles?

Yle-dl uses (in this or some order?)  wget, ffmpeg,, adobehds and rtmpdump for audio,
wget and ffmpeg do "the same video protocols", produce mp4
adobehds news and other "older" flv protocol.

add to yle-dl command arguments (where xxxx on purpose wrong)
--wget="xxxx" 
--ffmpeg="xxxx"
--adobehds="xxx"
etc
probably have to play around with argument --backend ??? too,
I am using this to skip adobehds downloads (which I download separately) Btw, using the list function.

--backend adobehdsphp  --adobehds="xxx"

the --backend wants a comma separated list of downloaders?? without blanks or pause-key!

PS hmm.. in one specific force-ffmpeg case I "changed the source code"?

**Comment by aajanki** [comment]
I implemented a new command line option `--subtitlesonly` for downloading only the subtitles.

**Comment by hugovk** [comment]
Thanks!
