### ISSUE TITLE
'no admissible streams' for some URIs

### ISSUE THREAD

**Issue by jackyf** [aajanki/yle-dl#156]
Hi,

Many thanks for maintaining this utility, as playing using a web browser usually comes with a pain.

Recently I noticed that some URIs stopped to work, e.g.:
```
~/.local/bin/yle-dl https://areena.yle.fi/1-1171003
yle-dl 2.31: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2018 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3
ERROR: Unsupported stream: No admissible streams
```

**Comment by aajanki** [comment]
Can you post the output `yle-dl --verbose https://areena.yle.fi/1-1171003`?

**Comment by jackyf** [comment]
Attached.

**Comment by jackyf** [comment]
Hm, the web interface just seems to silently drop the attached files, cannot edit comments either. I'll try to re-post so that the attachment is present.

**Comment by jackyf** [comment]
Try 2.
[no-adm-streams.txt](https://github.com/aajanki/yle-dl/files/1867501/no-adm-streams.txt)

**Comment by aajanki** [comment]
That streams is only available inside Finland according to the Areena page. Are you in Finland? Can you see the video in the web browser?

**Comment by jackyf** [comment]
I see now. It's been a while since I tried to play videos in a browser (since a browser would often crash or hang). The place is in Finland, all integration tests pass, but it's a helper machine where videos are displayed as available, but a browser then displays a permission error. So I guess I shall not try accessing those videos from that machine.

Sorry for troubling.
