### ISSUE TITLE
wishlist multi-download, resume check

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#158]
Seems YLE servers limit download speed to 600-800kbps, one reason I run 3-4 list-downloads at the sme time to use full connection bandwidth.

However, adobehds cld use full speed as it cld download many segments at the same time (ffmpeg cant)

What about wget downloading 2-3-4 pieces of same stream, starting at 1/2, 1/4, etc and then "piecing them together".

Would be kindof similar code that would "check if resume really resumes correctly"?

- check if beginning of stream still the same
- check if (overlapping) resume-point of stream same as it was when earlier download.
I guess some 4-8kB wld "do it"?

Note, --resume sometimes corrupts the video file "without saying anything".
I guess it happens when YLE does them seconds and additionally changes the actual videostream?
(typical A-Studio which "keeps changing" during a couple of days, 1st cut, 2de cut,, texting,etc)

btw2: with multipl yle-dl running, sometimes one dwnld takes "all bandwidth" and the rest run at snail-speed 50-70lbps.

A runtime key-hit Alt-B or something to change, cycle --ratelimit wld be great (for wget).
(with that code somewhere one could also do other goodies, "pause/quit after this download" etc/)

PS managed to detect these bungled cases fairly efficiently by just skipping mplayer to the end of the video. Mplayer wont go to end, but stops at point where "resume got botched"??

PPS Couldnt easily find a place to add this code? Me no Python-fan anymore!

**Comment by aajanki** [comment]
Wget or AdobeHDS can't download multiple chunks of a file at the same time, but there are other tools that apparently can, for example [wget2](https://gitlab.com/gnuwget/wget2). However, I don't have time to add and maintain another downloader backend.
