### ISSUE TITLE
Downloading the 2018 World Cup videos fails

### ISSUE THREAD

**Issue by uusijani** [aajanki/yle-dl#159]
Downloading the 2018 World Cup videos fails (with geo restriction suggested as the cause, but my IP is in Finland). Some clips (at least [this one](https://areena.yle.fi/tv/ohjelmat/30-901?play=1-50003740)) can be downloaded, but none of the games I've tried so far.  [They've upgraded the streams to 50 fps for the games](https://yle.fi/aihe/artikkeli/2018/06/13/areenan-uudet-ominaisuudet-valmiina-kisoihin), though I don't know this is related.

    09.07 jani@saegusa:tmp$ yle-dl -V 'https://areena.yle.fi/tv/ohjelmat/30-901?play=1-50003140'
    yle-dl 2.32: Download media files from Yle Areena and Elävä Arkisto
    Copyright (C) 2009-2018 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3
    DEBUG: not a playlist
    DEBUG: program data:
    DEBUG: {"meta": {"callback": "yleEmbed.programJsonpCallback", "id": "1-50003140"}, "data": {"metrics": {"sola": {"category": "urheilu", "contentLength": "10500000", "show": "urheilu.vod.vain_areenassa.fifan jalkapallon mm 2018", "contentType": "vod", "title": "20180615"}, "comscore": {"ns_st_ty": "vod", "ns_st_el": "10500000", "ns_st_ep": "20180615", "ns_st_cl": "10500000", "fp_bd": "20180615", "ns_st_ci": "54-1-50003140", "category": "urheilu", "yle_title": "fifan jalkapallon mm 2018", "yle_truelength": "10500000", "yle_ss_ohjusid": "1-50003140", "ns_st_st": "vain_areenassa", "fp_clnr": "20001", "countername": "urheilu.vod.vain_areenassa.fifan jalkapallon mm 2018", "fp_ty": "video_web_program", "yle_stickytitle": " egy - uru", "yle_dayssincepublish": "1", "yle_language": "n/a", "yle_ss_prodnumber": "n/a", "ns_st_dt": "20180615", "fp_ch": "fp198", "content_type": "vod", "ns_st_pl": "urheilu.vod.vain_areenassa.fifan jalkapallon mm 2018.20180615", "yle_metrics_api_data_version": "v2.1", "yle_ss_mediaid": "55-4a81d2d54c574c9bb8b3229f7fef0a26-od", "fp_prod_id": "na", "ns_st_pr": "urheilu.vod.vain_areenassa.fifan jalkapallon mm 2018"}}, "program": {"creator": [], "image": {"available": true, "version": 1529072769, "type": "ImageObject", "id": "13-1-50003140-1528282850652"}, "video": {"type": "VideoTrack", "language": [], "format": []}, "duration": "PT2H55M", "id": "1-50003140", "subject": [{"type": "Concept", "inScheme": "yle-content-main-classification", "id": "31-1-3", "title": {"fi": "Urheilu"}}, {"type": "Concept", "inScheme": "yle-content-format-classification", "id": "31-2-1.4", "title": {"fi": "Tapahtuma"}}, {"type": "Concept", "inScheme": "yle-content-topic-classification", "id": "31-3-3.89", "title": {"fi": "Jalkapallo"}}, {"type": "Concept", "inScheme": "areena-analytics-classification", "id": "5-267", "key": "urheilu", "title": {"fi": "Urheilu"}}], "indexDataModified": "2018-06-15T17:26:09.096+03:00", "typeCreative": "Program", "subtitling": [], "partOfSeason": {"indexDataModified": "2018-06-16T05:13:18.261+03:00", "seasonNumber": 2018, "description": {}, "title": {"fi": "FIFAn jalkapallon MM 2018", "sv": "FIFA:s fotbolls-VM 2018"}, "countryOfOrigin": [], "creator": [{"type": "Organization", "name": "FIFA Switzerland"}], "productionId": "88800092085", "partOfSeries": {"id": "1-3619218"}, "type": "TVSeason", "id": "1-4423225", "subject": [{"type": "Concept", "inScheme": "finnpanel-genre-classification", "id": "21-5", "notation": [{"valueType": "finnpanel-notation", "value": "4"}], "title": {"fi": "Urheilu", "en": "Sports"}}, {"type": "Concept", "inScheme": "yle-content-main-classification", "id": "31-1-3", "title": {"fi": "Urheilu"}}, {"type": "Concept", "inScheme": "yle-content-format-classification", "id": "31-2-1.4", "title": {"fi": "Tapahtuma"}}, {"type": "Concept", "inScheme": "yle-content-topic-classification", "id": "31-3-3.89", "title": {"fi": "Jalkapallo"}}, {"broader": {"id": "5-162"}, "title": {"fi": "Uutisohjelmat", "sv": "Nyhetsprogram"}, "inScheme": "areena-content-classification", "key": "uutisohjelmat", "type": "Concept", "id": "5-163"}, {"broader": {"id": "5-130"}, "title": {"fi": "Urheilu", "sv": "Sport"}, "inScheme": "areena-content-classification", "key": "urheilu", "type": "Concept", "id": "5-164"}, {"broader": {"id": "5-164"}, "title": {"fi": "Urheilumakasiini", "sv": "Sportsmagasin"}, "inScheme": "areena-content-classification", "key": "urheilumakasiini", "type": "Concept", "id": "5-166"}, {"broader": {"id": "5-164"}, "title": {"fi": "Jalkapallo", "sv": "Fotboll"}, "inScheme": "areena-content-classification", "key": "jalkapallo", "type": "Concept", "id": "5-172"}, {"type": "Concept", "inScheme": "areena-analytics-classification", "id": "5-267", "key": "urheilu", "title": {"fi": "Urheilu"}}]}, "contentRating": {"reason": [], "title": {}}, "publicationEvent": [{"publisher": [{"id": "yle-areena"}], "temporalStatus": "currently", "service": {"id": "yle-areena"}, "media": {"available": true, "contentProtection": [{"type": "ContentProtectionPolicy", "id": "22-1"}], "version": 1529072769, "downloadable": false, "duration": "PT2H55M", "type": "VideoObject", "id": "55-4a81d2d54c574c9bb8b3229f7fef0a26-od"}, "region": "Finland", "version": 1529072769, "startTime": "2018-06-15T17:25:00+03:00", "duration": "P5M3W6D", "endTime": "2018-12-12T16:25:00+02:00", "type": "OnDemandPublication", "id": "4-50003742"}, {"publisher": [{"id": "yle-areena"}], "temporalStatus": "in-past", "service": {"id": "yle-areena"}, "media": {"available": true, "contentProtection": [{"type": "ContentProtectionPolicy", "id": "22-1"}], "version": 1529072769, "downloadable": false, "duration": "PT2H55M", "type": "VideoObject", "id": "55-4a81d2d54c574c9bb8b3229f7fef0a26"}, "region": "Finland", "version": 1529072769, "startTime": "2018-06-15T14:30:00+03:00", "duration": "PT2H55M", "endTime": "2018-06-15T17:25:00+03:00", "type": "ScheduledTransmission", "id": "4-50003741"}], "type": "TVProgram", "typeMedia": "TVContent", "description": {"fi": " A-lohkon ottelu Egypti - Uruguay. Jekaterinburg, Ven\u00e4j\u00e4. Selostus Lauri Kottonen."}, "alternativeId": ["54-1-50003140"], "collection": "main", "originalTitle": {}, "itemTitle": {}, "@id": "http://programs.api.yle.fi/v1/id/1-50003140", "audio": [], "countryOfOrigin": [], "title": {"fi": " EGY - URU"}, "partOfSeries": {"indexDataModified": "2018-06-16T05:14:34.998+03:00", "description": {"fi": "FIFAn jalkapallon MM 2018 - Ylen kanavilla.", "sv": "Fifas fotbolls-VM 2018 - p\u00e5 Yles kanaler."}, "title": {"fi": "FIFAn jalkapallon MM 2018", "sv": "FIFA:s fotbolls-VM 2018"}, "countryOfOrigin": [], "@id": "http://programs.api.yle.fi/v1/id/1-3619218", "availabilityDescription": {"fi": "Jalkapallon MM-kisat 14.6. - 15.7.2018 Ven\u00e4j\u00e4ll\u00e4"}, "interactions": [{"url": "http://yle.fi/urheilu/jalkapallo/", "type": "WebPage", "title": {"fi": "Yle Urheilu: Jalkapallo"}}], "creator": [{"type": "Organization", "name": "FIFA Switzerland"}], "image": {"available": true, "version": 1529115274, "type": "ImageObject", "id": "13-1-3619218-1526294363132"}, "season": [{"indexDataModified": "2018-06-16T05:13:18.261+03:00", "seasonNumber": 2018, "description": {}, "title": {"fi": "FIFAn jalkapallon MM 2018", "sv": "FIFA:s fotbolls-VM 2018"}, "countryOfOrigin": [], "creator": [{"type": "Organization", "name": "FIFA Switzerland"}], "productionId": "88800092085", "partOfSeries": {"id": "1-3619218"}, "type": "TVSeason", "id": "1-4423225", "subject": [{"type": "Concept", "inScheme": "finnpanel-genre-classification", "id": "21-5", "notation": [{"valueType": "finnpanel-notation", "value": "4"}], "title": {"fi": "Urheilu", "en": "Sports"}}, {"type": "Concept", "inScheme": "yle-content-main-classification", "id": "31-1-3", "title": {"fi": "Urheilu"}}, {"type": "Concept", "inScheme": "yle-content-format-classification", "id": "31-2-1.4", "title": {"fi": "Tapahtuma"}}, {"type": "Concept", "inScheme": "yle-content-topic-classification", "id": "31-3-3.89", "title": {"fi": "Jalkapallo"}}, {"broader": {"id": "5-162"}, "title": {"fi": "Uutisohjelmat", "sv": "Nyhetsprogram"}, "inScheme": "areena-content-classification", "key": "uutisohjelmat", "type": "Concept", "id": "5-163"}, {"broader": {"id": "5-130"}, "title": {"fi": "Urheilu", "sv": "Sport"}, "inScheme": "areena-content-classification", "key": "urheilu", "type": "Concept", "id": "5-164"}, {"broader": {"id": "5-164"}, "title": {"fi": "Urheilumakasiini", "sv": "Sportsmagasin"}, "inScheme": "areena-content-classification", "key": "urheilumakasiini", "type": "Concept", "id": "5-166"}, {"broader": {"id": "5-164"}, "title": {"fi": "Jalkapallo", "sv": "Fotboll"}, "inScheme": "areena-content-classification", "key": "jalkapallo", "type": "Concept", "id": "5-172"}, {"type": "Concept", "inScheme": "areena-analytics-classification", "id": "5-267", "key": "urheilu", "title": {"fi": "Urheilu"}}]}, {"indexDataModified": "2018-06-16T05:14:35.006+03:00", "seasonNumber": 2018, "description": {}, "title": {"fi": "FIFAn jalkapallon MM 2018", "sv": "FIFA:s fotbolls-VM 2018"}, "countryOfOrigin": [], "creator": [{"type": "Organization", "name": "FIFA Switzerland"}], "productionId": "88800081516", "partOfSeries": {"id": "1-3619218"}, "type": "TVSeason", "id": "1-4393329", "subject": [{"type": "Concept", "inScheme": "finnpanel-genre-classification", "id": "21-5", "notation": [{"valueType": "finnpanel-notation", "value": "4"}], "title": {"fi": "Urheilu", "en": "Sports"}}, {"type": "Concept", "inScheme": "yle-content-main-classification", "id": "31-1-3", "title": {"fi": "Urheilu"}}, {"type": "Concept", "inScheme": "yle-content-format-classification", "id": "31-2-1.4", "title": {"fi": "Tapahtuma"}}, {"type": "Concept", "inScheme": "yle-content-topic-classification", "id": "31-3-3.89", "title": {"fi": "Jalkapallo"}}, {"broader": {"id": "5-162"}, "title": {"fi": "Uutisohjelmat", "sv": "Nyhetsprogram"}, "inScheme": "areena-content-classification", "key": "uutisohjelmat", "type": "Concept", "id": "5-163"}, {"broader": {"id": "5-130"}, "title": {"fi": "Urheilu", "sv": "Sport"}, "inScheme": "areena-content-classification", "key": "urheilu", "type": "Concept", "id": "5-164"}, {"broader": {"id": "5-164"}, "title": {"fi": "Urheilumakasiini", "sv": "Sportsmagasin"}, "inScheme": "areena-content-classification", "key": "urheilumakasiini", "type": "Concept", "id": "5-166"}, {"broader": {"id": "5-164"}, "title": {"fi": "Jalkapallo", "sv": "Fotboll"}, "inScheme": "areena-content-classification", "key": "jalkapallo", "type": "Concept", "id": "5-172"}, {"type": "Concept", "inScheme": "areena-analytics-classification", "id": "5-267", "key": "urheilu", "title": {"fi": "Urheilu"}}]}, {"indexDataModified": "2018-05-21T09:32:17.048+03:00", "seasonNumber": 2017, "description": {}, "title": {"fi": "Jalkapallon MM 2018 karsinta", "sv": "Fotbolls-VM 2018, kval"}, "countryOfOrigin": [], "creator": [{"type": "Organization", "name": "FIFA Switzerland"}], "productionId": "88800021354", "partOfSeries": {"id": "1-3619218"}, "type": "TVSeason", "id": "1-3975832", "subject": [{"type": "Concept", "inScheme": "finnpanel-genre-classification", "id": "21-5", "notation": [{"valueType": "finnpanel-notation", "value": "4"}], "title": {"fi": "Urheilu", "en": "Sports"}}, {"type": "Concept", "inScheme": "yle-content-main-classification", "id": "31-1-3", "title": {"fi": "Urheilu"}}, {"type": "Concept", "inScheme": "yle-content-format-classification", "id": "31-2-1.4", "title": {"fi": "Tapahtuma"}}, {"type": "Concept", "inScheme": "yle-content-topic-classification", "id": "31-3-3.89", "title": {"fi": "Jalkapallo"}}, {"broader": {"id": "5-162"}, "title": {"fi": "Uutisohjelmat", "sv": "Nyhetsprogram"}, "inScheme": "areena-content-classification", "key": "uutisohjelmat", "type": "Concept", "id": "5-163"}, {"broader": {"id": "5-130"}, "title": {"fi": "Urheilu", "sv": "Sport"}, "inScheme": "areena-content-classification", "key": "urheilu", "type": "Concept", "id": "5-164"}, {"broader": {"id": "5-164"}, "title": {"fi": "Urheilumakasiini", "sv": "Sportsmagasin"}, "inScheme": "areena-content-classification", "key": "urheilumakasiini", "type": "Concept", "id": "5-166"}, {"broader": {"id": "5-164"}, "title": {"fi": "Jalkapallo", "sv": "Fotboll"}, "inScheme": "areena-content-classification", "key": "jalkapallo", "type": "Concept", "id": "5-172"}, {"type": "Concept", "inScheme": "areena-analytics-classification", "id": "5-267", "key": "urheilu", "title": {"fi": "Urheilu"}}]}, {"indexDataModified": "2018-05-21T09:31:59.168+03:00", "seasonNumber": 2017, "description": {}, "title": {"fi": "Fifan jalkapallon MM 2018", "sv": "Fifas fotbolls-VM 2018"}, "countryOfOrigin": [], "creator": [{"type": "Organization", "name": "FIFA Switzerland"}], "productionId": "88800046024", "partOfSeries": {"id": "1-3619218"}, "type": "TVSeason", "id": "1-4225626", "subject": [{"type": "Concept", "inScheme": "finnpanel-genre-classification", "id": "21-5", "notation": [{"valueType": "finnpanel-notation", "value": "4"}], "title": {"fi": "Urheilu", "en": "Sports"}}, {"type": "Concept", "inScheme": "yle-content-main-classification", "id": "31-1-3", "title": {"fi": "Urheilu"}}, {"type": "Concept", "inScheme": "yle-content-format-classification", "id": "31-2-1.4", "title": {"fi": "Tapahtuma"}}, {"type": "Concept", "inScheme": "yle-content-topic-classification", "id": "31-3-3.89", "title": {"fi": "Jalkapallo"}}, {"broader": {"id": "5-162"}, "title": {"fi": "Uutisohjelmat", "sv": "Nyhetsprogram"}, "inScheme": "areena-content-classification", "key": "uutisohjelmat", "type": "Concept", "id": "5-163"}, {"broader": {"id": "5-130"}, "title": {"fi": "Urheilu", "sv": "Sport"}, "inScheme": "areena-content-classification", "key": "urheilu", "type": "Concept", "id": "5-164"}, {"broader": {"id": "5-164"}, "title": {"fi": "Urheilumakasiini", "sv": "Sportsmagasin"}, "inScheme": "areena-content-classification", "key": "urheilumakasiini", "type": "Concept", "id": "5-166"}, {"broader": {"id": "5-164"}, "title": {"fi": "Jalkapallo", "sv": "Fotboll"}, "inScheme": "areena-content-classification", "key": "jalkapallo", "type": "Concept", "id": "5-172"}, {"type": "Concept", "inScheme": "areena-analytics-classification", "id": "5-267", "key": "urheilu", "title": {"fi": "Urheilu"}}]}, {"indexDataModified": "2018-05-21T09:32:17.028+03:00", "seasonNumber": 2017, "description": {}, "title": {"fi": "Jalkapallon MM 2018 karsinta", "sv": "Fotbolls-VM 2018, kval"}, "countryOfOrigin": [], "creator": [{"type": "Organization", "name": "Yleisradio Oy"}], "productionId": "88800021365", "partOfSeries": {"id": "1-3619218"}, "type": "TVSeason", "id": "1-3975911", "subject": [{"type": "Concept", "inScheme": "finnpanel-genre-classification", "id": "21-5", "notation": [{"valueType": "finnpanel-notation", "value": "4"}], "title": {"fi": "Urheilu", "en": "Sports"}}, {"type": "Concept", "inScheme": "yle-content-main-classification", "id": "31-1-3", "title": {"fi": "Urheilu"}}, {"type": "Concept", "inScheme": "yle-content-format-classification", "id": "31-2-1.4", "title": {"fi": "Tapahtuma"}}, {"type": "Concept", "inScheme": "yle-content-topic-classification", "id": "31-3-3.89", "title": {"fi": "Jalkapallo"}}, {"broader": {"id": "5-162"}, "title": {"fi": "Uutisohjelmat", "sv": "Nyhetsprogram"}, "inScheme": "areena-content-classification", "key": "uutisohjelmat", "type": "Concept", "id": "5-163"}, {"broader": {"id": "5-130"}, "title": {"fi": "Urheilu", "sv": "Sport"}, "inScheme": "areena-content-classification", "key": "urheilu", "type": "Concept", "id": "5-164"}, {"broader": {"id": "5-164"}, "title": {"fi": "Urheilumakasiini", "sv": "Sportsmagasin"}, "inScheme": "areena-content-classification", "key": "urheilumakasiini", "type": "Concept", "id": "5-166"}, {"broader": {"id": "5-164"}, "title": {"fi": "Jalkapallo", "sv": "Fotboll"}, "inScheme": "areena-content-classification", "key": "jalkapallo", "type": "Concept", "id": "5-172"}, {"type": "Concept", "inScheme": "areena-analytics-classification", "id": "5-267", "key": "urheilu", "title": {"fi": "Urheilu"}}]}, {"indexDataModified": "2018-05-21T09:32:17.006+03:00", "seasonNumber": 2017, "description": {"fi": "Kooste muista p\u00e4iv\u00e4n otteluista.", "sv": "Dagens \u00f6vriga matcher i sammandrag."}, "title": {"fi": "Jalkapallon MM 2018 karsinta", "sv": "Fotbolls-VM 2018, kval"}, "countryOfOrigin": [], "creator": [{"type": "Organization", "name": "FIFA Switzerland"}], "productionId": "88800021358", "partOfSeries": {"id": "1-3619218"}, "type": "TVSeason", "id": "1-3975888", "subject": [{"type": "Concept", "inScheme": "finnpanel-genre-classification", "id": "21-5", "notation": [{"valueType": "finnpanel-notation", "value": "4"}], "title": {"fi": "Urheilu", "en": "Sports"}}, {"type": "Concept", "inScheme": "yle-content-main-classification", "id": "31-1-3", "title": {"fi": "Urheilu"}}, {"type": "Concept", "inScheme": "yle-content-format-classification", "id": "31-2-1.4", "title": {"fi": "Tapahtuma"}}, {"type": "Concept", "inScheme": "yle-content-topic-classification", "id": "31-3-3.89", "title": {"fi": "Jalkapallo"}}, {"broader": {"id": "5-162"}, "title": {"fi": "Uutisohjelmat", "sv": "Nyhetsprogram"}, "inScheme": "areena-content-classification", "key": "uutisohjelmat", "type": "Concept", "id": "5-163"}, {"broader": {"id": "5-130"}, "title": {"fi": "Urheilu", "sv": "Sport"}, "inScheme": "areena-content-classification", "key": "urheilu", "type": "Concept", "id": "5-164"}, {"broader": {"id": "5-164"}, "title": {"fi": "Urheilumakasiini", "sv": "Sportsmagasin"}, "inScheme": "areena-content-classification", "key": "urheilumakasiini", "type": "Concept", "id": "5-166"}, {"broader": {"id": "5-164"}, "title": {"fi": "Jalkapallo", "sv": "Fotboll"}, "inScheme": "areena-content-classification", "key": "jalkapallo", "type": "Concept", "id": "5-172"}, {"type": "Concept", "inScheme": "areena-analytics-classification", "id": "5-267", "key": "urheilu", "title": {"fi": "Urheilu"}}]}, {"indexDataModified": "2018-05-21T09:32:29.800+03:00", "description": {}, "title": {"fi": "Jalkapallon MM 2018 karsinta", "sv": "Fotbolls-VM 2018, kval"}, "countryOfOrigin": [], "creator": [], "productionId": "40316800000", "partOfSeries": {"id": "1-3619218"}, "type": "TVSeason", "id": "1-3140446", "subject": [{"type": "Concept", "inScheme": "finnpanel-genre-classification", "id": "21-5", "notation": [{"valueType": "finnpanel-notation", "value": "4"}], "title": {"fi": "Urheilu", "en": "Sports"}}, {"type": "Concept", "inScheme": "yle-content-main-classification", "id": "31-1-3", "title": {"fi": "Urheilu"}}, {"type": "Concept", "inScheme": "yle-content-format-classification", "id": "31-2-1.3", "title": {"fi": "Reportaasi, raportti"}}, {"type": "Concept", "inScheme": "yle-content-topic-classification", "id": "31-3-3.89", "title": {"fi": "Jalkapallo"}}, {"broader": {"id": "5-130"}, "title": {"fi": "Urheilu", "sv": "Sport"}, "inScheme": "areena-content-classification", "key": "urheilu", "type": "Concept", "id": "5-164"}, {"broader": {"id": "5-164"}, "title": {"fi": "Urheilumakasiini", "sv": "Sportsmagasin"}, "inScheme": "areena-content-classification", "key": "urheilumakasiini", "type": "Concept", "id": "5-166"}, {"broader": {"id": "5-164"}, "title": {"fi": "Jalkapallo", "sv": "Fotboll"}, "inScheme": "areena-content-classification", "key": "jalkapallo", "type": "Concept", "id": "5-172"}, {"type": "Concept", "inScheme": "areena-analytics-classification", "id": "5-267", "key": "urheilu", "title": {"fi": "Urheilu"}}]}], "coverImage": {"available": true, "version": 1529115274, "type": "ImageObject", "id": "13-1-3619218-1526294363131"}, "type": "TVSeries", "id": "1-3619218", "subject": [{"type": "Concept", "inScheme": "finnpanel-genre-classification", "id": "21-5", "notation": [{"valueType": "finnpanel-notation", "value": "4"}], "title": {"fi": "Urheilu", "en": "Sports"}}, {"type": "Concept", "inScheme": "yle-content-main-classification", "id": "31-1-3", "title": {"fi": "Urheilu"}}, {"type": "Concept", "inScheme": "yle-content-format-classification", "id": "31-2-1.4", "title": {"fi": "Tapahtuma"}}, {"type": "Concept", "inScheme": "yle-content-topic-classification", "id": "31-3-3.89", "title": {"fi": "Jalkapallo"}}, {"broader": {"id": "5-162"}, "title": {"fi": "Uutisohjelmat", "sv": "Nyhetsprogram"}, "inScheme": "areena-content-classification", "key": "uutisohjelmat", "type": "Concept", "id": "5-163"}, {"broader": {"id": "5-130"}, "title": {"fi": "Urheilu", "sv": "Sport"}, "inScheme": "areena-content-classification", "key": "urheilu", "type": "Concept", "id": "5-164"}, {"broader": {"id": "5-164"}, "title": {"fi": "Urheilumakasiini", "sv": "Sportsmagasin"}, "inScheme": "areena-content-classification", "key": "urheilumakasiini", "type": "Concept", "id": "5-166"}, {"broader": {"id": "5-164"}, "title": {"fi": "Jalkapallo", "sv": "Fotboll"}, "inScheme": "areena-content-classification", "key": "jalkapallo", "type": "Concept", "id": "5-172"}, {"type": "Concept", "inScheme": "areena-analytics-classification", "id": "5-267", "key": "urheilu", "title": {"fi": "Urheilu"}}]}}}}
    DEBUG: media:
    DEBUG: {"meta": {"mediaId": "1-50003140", "callback": "yleEmbed.startPlayerCallback", "instance": "1", "client": "areena-flash-player", "protocol": "HDS", "id": "55-4a81d2d54c574c9bb8b3229f7fef0a26-od"}, "data": {"media": {"HDS": []}, "domain": {}}}
    ERROR: Unsupported stream: Media not found
    WARNING: Failed! If there is no clear reason above the reason might
    WARNING: be a geo restriction. This stream is available only in Finland.

**Comment by gunnar12** [comment]
Mini-wish-list:

While adding the new link etc, would be nice to get a --shoiwall or --showtitleurl option.
Would at least show Title and URL on two consecutive lines, easily copied to "some other downl;oader"
(did it, but run into too large changes to be a simple patch

**Comment by aajanki** [comment]
There is now a partial support for the world cup streams. Most of the metadata is missing and some audio is lost on some streams.

**Comment by aajanki** [comment]
@gunnar12, use `--showmetadata` instead of the older `--showtitle` and `--showurl`.

**Comment by gunnar12** [comment]
--showmetadata instead of the older --showtitle and --showurl./

-metadat shows only duration, also the yet non-corrected title-file-name (--vfat,etc)

My point was to get three lines like this
Easy to copy from terminal window with mouse, without having to manually edit it.

12345
file-name.ext
htpps://......971

Problem, the small function printing the final filename, URL going to the external downloader doesnt know what the duration is, if not saved in some suitable imported or global structure.
(plus some for me unknow filter argument)
The args array has filename and URL for ext dwnlder additionally varies for diffrnt downloaders.

PS In general, making changes like this run into problem for the same reason, the small function doing the actual thing doesnt have access to all the general info. (like the metadata).
It seems to demand changes in 3-4-5 places, not simple small patch

**Comment by aajanki** [comment]
I just published version 2.33 that handles at least most of the world cup videos I have tested. Most of the metadata is still missing.

I created a new issue #160 for adding the filename to the metadata, and will close this issue.
