### ISSUE TITLE
Use "short" filename or long, search for both?

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#161]
In process of merging my-you code.
Got to the seconds,minutes from publishday to outputfilename.

Easy to add a --short argument for
       #                             2018  mm    dd    hh    mm    ss 
        short0 = re.match(r'\d{4}-\d{2}-\d{2}T\d{2}:\d{2}', start_time or '')
        short1 = re.match(r'\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{1}', start_time or '')

Slightly more complecated  to save both filename versions to be able to (somewhere else) search directory for both and only then decide on what to do, download or not

Even more complicated but fun to add 
--checkdir="chkdir.txt"
for a text-list of directories (hard drives) where to search for them alrdy existing downloads 
(with some sanity check on filesize included while waiting for some smarter code next winter, compare header and first kBytes, check duration,etc, as rtmp does)

and Best!

add --lastdir="movetodir"  for where to move files that are
- about to expire
- alrdy expired

PS any simple way of doing on-run-keys (signals? like ctrl-c,z, etc) on Python.
Need to merge my ugly code for changing things to "on-the-run-fly-change"

PPS Realy fun, merging spd-say, the linux speak-program,
(simplest, just add to logger code, but needs time to speak long stuff,hehe)

However, every now and then it stops working, stuck, , yle-dl too stuck and need to do spd-conf to kill and restart spd-say.

But GREAT when yle-dl speaks and tells me what it is doing.
(well, need to add on-the-run keys for male-female and volume,etc settings)

PPPS I guess all 1-50xxx programs need the "Sportsdownloader"?
Seems you do a too rigid check of their areena link containing right web page & "?play that thing".

https://areena.yle.fi/tv/ohjelmat/30-901?play=1-50003202

Or are there some (from regular areena page, where FIFI programs turn up like?)

https://areena.yle.fi/1-5000xxxx

that cant take the SportsDownloader system??

PPPPS(hit)
ISNT THERE A DAMXXED WAY OF MAKING A SIMPLE TOTALLY RAW GLOBAL thing in Python??
Like
- export in one place
- import in all others

later on one can do it the safe & secure & "simple" Python-way, namespaces and distributed servers and whatever missile-refrigator-processor architectures
(simpler than
- write to a file in one place
- read from that global file in all others
hehe)

**Comment by gunnar12** [comment]
Btw, time to delete issue on "windows code" down there?

New setup and cfg, python 3.6 (?or something) makes it easy.
However, seems one need to copy three files, yle-dl exe, manifest and script to run it, or some yesterday special version, somewhere else? NICE! Thanks! (like the Sportsdwnldr and new file-distribution, better "readability")

PS Havnt tested whatelse it needs from the python 3.6 install and finds it thrgh windows path settings

PPS SOmetimes I get a "lower resolution" file (than normal or later). 
Does YLE itself change their own production of for example AamuTV, A-Studio "along the day", or some other possible reason (cmpr added text caption and them seconds?)?
(I have not yet walked thrgh the code for that, what resolutions and how picked)

**Comment by gunnar12** [comment]
Btw, another interesting, maybe, thing I havnt mentioned.
Tht thing abt copying just the final fftemp or wget info, filename & video URL, is because

SOmetimes I use the mobile internet (thrgh smartphone or stick) and another PC for "special or urgent" downloads. 
Basically using two computers with their own internet connection.
When doing this I just copy that filename + vidro-url from linux (or windows) screen, quit that download (q for ffmpeg) and start that download in the other computer (which uses the other internet connection)
Getting 14Mbps in a lousy 3G area now, the whole tower,   3xYLE ideo bitrate
But sometimes just 1-3Mbps.

Someday maybe Android yle-dl and ffmpeg? and 1TeraByte smartphones..

**Comment by gunnar12** [comment]
Aaahh, had forgot that "alternative name: thing, adding -n to filename if it already exists.

I dont remember while the result of some of my wishlists were to add the -n and doenload once again (if  not using --resume).

ANyway, added an ugly simple fix, if the file already exists, set returned filename to "exist".
High up in the cloads, before subtitle save I then test for that filename and just return success (no download) to have yle-dl continue downloading the next according to text list.

PS Next need to add that "sanity check" on that existing downloaded file.
Plus all the --checkdirs.. search dirctory using glob.glob etc strange Python stuff..
(for files with and without seconds, plus all the series-title name weird YLE stuff)

**Comment by gunnar12** [comment]
series-title name weird YLE stuff/

Havnt really figured it out, but seems (both yle-dl and ) YLE play games with the meta dat finally producing the outputfilename??

Not just the seconds and minutes for publishing, but also, Serie name and Episode name, as one example

Doc Martin: S0nE0m Hello-hello-hello
or just
Hello-hello-hello S0nE0m (missing the "Doc Martin" part)

Seems to change during the day too, disappears and maybe even returns??

PS Thats why I decided to not just check if file alrdy exists, but also search for partial matches.

Any idea whats really going on with the YLE metadata??

**Comment by aajanki** [comment]
`yle-dl --output-template '${series}${title}${episode}${date}'` will output "short" filenames without the time.

Checking for partial matches for possible earlier downloads sounds very brittle. A better way would be to save the episode ID into a database together with a flag that tells if the download has succeeded, and check the status there on resume. I'm assuming that Yle is not modifying episode IDs after publication. However, I don't have time to implement this, so you have to do it yourself.
