### ISSUE TITLE
In some instances error of "unsupported stream" from areena video

### ISSUE THREAD

**Issue by shlandturtle** [aajanki/yle-dl#162]
I am not sure what causes this problem, but no matter what backend I use, yle-dl doesn't find the stream of a certain areena video, outputting the following:
ERROR: Unsupported stream: Unknown stream flavor
I'm using yle-dl version 2.35, the 2.34 version produced error message "ERROR: Unsupported stream: Media not found".

I have only seen this error in one video, which uses different looking web player than other areena content. Besides that, I managed to find out that the video in question might have framerate of 50 at the highest quality (while lower quality are the usual 25 fps). Whether or not this framerate difference is part of the issue, is outside my knowledge.

Asking for --metadata the output is following:
```
[
  {
    "webpage": "https://areena.yle.fi/1-50004420", 
    "flavors": [
      {
        "error": "Unknown stream flavor"
      }
    ], 
    "subtitles": []
  }
]
```
While --debug shows the following:

```
DEBUG: not a playlist
DEBUG: program data:
<Very long output part redacted>
DEBUG: media:
DEBUG: {"meta": {"mediaId": "1-50004420", "callback": "yleEmbed.startPlayerCallback", "instance": "1", "client": "areena-flash-player", "protocol": "HDS", "id": "55-2abe6d3b922047729090ece8454a94a7-od"}, "data": {"media": {"HDS": []}, "domain": {}}}
DEBUG: media:
DEBUG: {"meta": {"mediaId": "1-50004420", "callback": "yleEmbed.startPlayerCallback", "instance": "1", "client": "areena-flash-player", "protocol": "HDS", "id": "55-2abe6d3b922047729090ece8454a94a7-od"}, "data": {"media": {"HDS": []}, "domain": {}}}
DEBUG: Available flavors:
DEBUG: bitrate: None, height: None, width: None, hard_subtitle: None
DEBUG: max_height: None, max_bitrate: None
DEBUG: Selected flavor: FailedFlavor(media_type=u'unknown', height=None, width=None, bitrate=None, streams=[<yledl.backends.FailingBackend object at 0x7fc644a11710>], hard_subtitle=None)
ERROR: Unsupported stream: Unknown stream flavor
```

The video that prouced this error (available for three weeks):
https://areena.yle.fi/1-50004420
Just type "yle-dl https://areena.yle.fi/1-50004420" and you should get the same error.

**Comment by aajanki** [comment]
Looks like this is a same kind of stream that was used for World Cup streams. yle-dl is actually able to download that kind of streams, but in this case it misdetect the stream type. I'll improve the stream type detection.

**Comment by gunnar12** [comment]
same kind of stream/Global Xmas tree/

Anoither thing regarding the "SportsStreams", I am trying to look into it, but not yet familiar enough.

Any chance to get that StartTime or PublishTime or some timestamp at the same time?
I have had success by fooling yle-dl to detect the sports-stuff by adding the neededd keywords
https://areena.yle.fi/1-50004420
https://areena.yle.fi/tv/ohjelmat/30-901?play=1-5-50004420

but didnt work in thise case.
Also, different programs seem to get the same outputfilename when no timestamp is added?
(I havnt yet merged my own code of logging info, program ID, etc, etc to avoid duplicates as well as looking in many directories for an already downloaded file)

Gunnar

PS Seems a userfriendly "Xmas-tree" global structure wld be nice (ref new breakout of io)
A "Global Xmas tree" that one can easily "add and hang stuff onto" anywhere in code and modules, also import and check easily in any other place.

**Comment by gunnar12** [comment]
ClipExtractor Class/

Thanks!!
Was just abt to attack programInfo junglefor my perpetual merges!!

This shld help a lot!

Gunnar

**Comment by aajanki** [comment]
I improved the stream type detection and this stream (and hopefully all others) can now be downloaded.

**Comment by Hajmer777** [comment]
Not work, not download :(

`[root@rulle yle-dl]# yle-dl https://areena.yle.fi/1-3882500 -o /home/hajmer/video.mp4
yle-dl 2.37: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2018 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

ERROR: Unsupported stream: No source video was found
[root@rulle yle-dl]# ERROR: Unsupported stream: No source video was found
`

**Comment by aajanki** [comment]
@Hajmer777, that stream has expired. It says "Ohjelman katseluaika on päättynyt" on the Areena web page. I'll add a better error message.
