### ISSUE TITLE
Make yle-dl support newer versions of python-attrs (or remove the dependency)

### ISSUE THREAD

**Issue by Emgalai** [aajanki/yle-dl#163]
Arch Linux users are no longer able to use yle-dl with the python-attrs provided in the official Arch Linux repositories, as the version there is 18.1.0, and yle-dl requires an old version 17.4.0. This has been solved for now with an AUR package of the old version of python-attrs, but I feel that is more like a work around than a real solution.

Why does yle-dl depend on an old version of python-attrs?

**Comment by aajanki** [comment]
I updated attrs version, and it should be compatible with Arch (at least until a new attrs version appear and Arch updates their package). The dependency is versioned, because attrs API changes every few versions, and yle-dl can only depend on a version that I know to be compatible.

**Comment by hugovk** [comment]
Does the API change for minor versions or only major versions?

If only major, how about something like `'attrs >= 18.1.0, < 19'`?

**Comment by aajanki** [comment]
The API changes also between minor versions.
