### ISSUE TITLE
Cant disable WGET wth bogus path anymore?

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#164]
Cant disable WGET wth bogus path anymore? 
in at least v 2.36?

Seems the system gives error message "cant find" but yle-dl does not continue by trying ffmpeg?
(remember, the GByte bug in default wget in ubuntu installation, need to use ffmpeg)

Similar problem with 1-5000xxx which doesnt use the "sports downloader"?
yle-dl tries it , link isnt there, but could/should give it another try with the old downloader.

Kindo difficuklt to find some recent programs, but had to switch to 2.33 for this one regular news

https://areena.yle.fi/1-50006066
(only 11h left, note, one can see what downloader needed in firedox, different "rotating wait" stuff, "sports" or "old" or "even older")

PS Ouch, the pain with python picking wrong, old versions can also be used to pick the right old version that one wants.

that (badly silly designed) "easy-install.pth" file 
in smthng like usr/local/pythonX-X/dist-packages, sudo to edit it.
by switching the order of them version paths egg-dist-packs.
(I still have no idea how the total link command-linux-python-egg-pack-final code-stuff goes)

Btw, even worse (or better) in windows??
Not just enoiugh the get the exe file right, all the bundled pythion stuff is somewhere else!!??
No problem if old and new use the same stuff, but not when one adds some python "system" code.

PS have had no luck producing a "stand-alone" windows exe,  cant even read the 5 page step-by-step stuff to the end... same problem, that "egg-stuff"

**Comment by gunnar12** [comment]
corrected dbl=link, now blocked from editing old message too

https://areena.yle.fi/1-50006066

**Comment by gunnar12** [comment]
and of course, that --shortname= Yes,no,0,1,2,3 or whatever

plus able/disabling that "XXX-2.mp4" attempt if file already exists

and printing them three-four important lines before starting download...

**Comment by gunnar12** [comment]
one weirs 5000 link..  needs old downloader, and just noted the firefox browser player doesnt show any rotating "wait thing" at all..

That is, I have been sorting links according to first the 5000xxxx and additionally (sometimes) by checking how they start in a regular windows browser (the player protocol the browser and server decide on?)

Finally I cross-run both listsa on both "old and new" based on 2.33 and 2.36.

That is, been busy doing that with 2 stable merges and dont dare changing code, messing them upp, eggs and all, that I havnt been able to "debug".

Gunnar

**Comment by aajanki** [comment]
With recent yle-dl you should use `yle-dl --backend ffmpeg` to disable all other backends besides ffmpeg.

Unfortunately, https://areena.yle.fi/1-50006066 had expired before I had time to debug the issue. Post a link if you happen to find another program with the same error.

**Comment by gunnar12** [comment]
yle-dl --backend ffmpeg/ thanks explains that

(posted the following new link alrdy, but disappeared?)

Already posted this maybe similar, 5000XXXX but needed old 2.33 (for me,before I knew that --backend=)

One other sign of weirdness, the player firefox and areena agrees on has no "rotating wait" while handshaking, waiting for actual video.

https://areena.yle.fi/1-50007115

butbut, I will dbl-check next "major" similar problem, (now that I know --backend)
Maybe 2.36 just skips the "bogus wget path" when going for the "sports" link and settings?

**Comment by aajanki** [comment]
I'm closing report this because the downloaders can now be disabled/selected with --backend.
