### ISSUE TITLE
Why I can now download from YLE Areena

### ISSUE THREAD

**Issue by vilsu2** [aajanki/yle-dl#167]
What is the issue why I can not download https://areena.yle.fi/1-2694720
from YLE Areena?

There have been similar issues with other files too.

Thank you for your effort with yle-dl!! It is great!! I like it a lot!! 

Parhain terveisin vilsu2

**Comment by aajanki** [comment]
It should work. Which version of yle-dl are you using? Do you get any error messages?

**Comment by vilsu2** [comment]
Antti Ajanki kirjoitti 14.10.2018 kello 15:30:
> It should work. Which version of yle-dl are you using? Do you get
>  any error
> messages?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/aajanki/yle-dl/issues/167#issuecomment-429622545


Hei Antti!

Laitan tähän alas mitä kone kertoi kun yritin ladata:

--------------- alku -------

ville@ville-HP-ProDesk-600-G1-SFF ~ $ yle-dl https://areena.yle.fi/1-2694720
yle-dl 2.32: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2018 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3
Output file: Avaruuskansiot: Aurinko: E01-2015-03-06T16:30.flv
ERROR: Failed to execute php /home/ville/.local/lib/python3.5/site-packages/yledl/AdobeHDS.php --manifest https://areenahdfi-vh.akamaihd.net/z/fi/c3/c3cc3e6b8077975ca965c3573366d5c3_,135168,367616,610304,958464,.mp4.csmil/manifest.f4m?hdnea=st=1539540723~exp=1539583923~acl=/z/fi/c3/c3cc3e6b8077975ca965c3573366d5c3_*~hmac=a389b40fa1356327cd4b756e13e4db292ebdc0aaaa240b2b4f475ed632aea307&g=ABCDEFGHIJKL&hdcore=3.8.0&plugin=flowplayer-3.8.0.0 --quality 1062 --delete --outfile Avaruuskansiot: Aurinko: E01-2015-03-06T16:30.flv
ERROR: No such file or directory: 'php'
ERROR: Failed to import youtube_dl
WARNING: Failed! If there is no clear reason above the reason might
WARNING: be a geo restriction. This stream is available only in Finland.

------------------ loppu ---------------

Jos osaat sanoa mikä on pielessä niin tuhannet kiitokset jo etukäteen.

Ystävällisin terveisin Ville Saarela

PS. Ai niin, Linux Mint 18.3 Cinnamon käytössä.

**Comment by aajanki** [comment]
Sinulla ei ole asennettuna php-tulkkia, jota tarvitaan joidenkin videoidan lataamiseen. Kannattaa tarkistaa, että myös muut README-tiedostossa luetellut ohjelmat on asennettu.

Debianissa tarvittavat ohjelmat saa asennettua seuraavalla komennolla. Sama saattaa toimia Mintissäkin.
```
sudo apt-get install rtmpdump wget ffmpeg python3-dev python3-setuptools \
    python3-pip python3-pycryptodome python3-requests python3-lxml python3-socks \
    php-cli php-curl php-xml php-bcmath
pip3 install --user --upgrade yle-dl
```

**Comment by aajanki** [comment]
Auttoiko ohjelmien asentaminen?

Suljen nyt tämän bugiraportin, mutta voit avata sen uudelleen, jos ongelma ei noilla ohjeilla selvinnyt.

**Comment by vilsu2** [comment]
Hei !

Anteeksi kun en vastannut aikaisemmin. Kyllä, ohjeesi auttoivat erittäin hyvin. En tiedä miten olin saanut asennettua yle-dl:n niin väärin, mutta olen aika taitamaton näissä linuxjutuissa.

Käytän siis Linux mint Cinnamon 18.3 -järjestelmää.

Paketti python3-pycryptodome ei löytynyt repoista mitä minulla on asennettuna, mutta näyttää toimivan yle-dl erinomaisesti ilman sitäkin.

Joskus yle-dl oli löytyi tuolta pakettihallinnasta ihan oletusasetuksilla, mutta nyttemmin se on kadonnut. Se oli silloin joskus erittäin kivaa kun oli oletuksena.

Kiitos paljon hyvästä ohjelmasta. Kiitos että olet jaksanut luotsata ohjelmaa vuosien ajan. 

Ystävällisin terveisin ja suurin kiitoksin,

Ville eli vilsu2






Antti Ajanki kirjoitti 22.10.2018 kello 21:36:
