### ISSUE TITLE
YLE messing around with Radio protocol??

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#170]
Been busy so started by "viela ehdit" as usual, drag-drop to a text-list.

some quick observations without digging into it:

Seems maybe half or more are not available as rtmp anymore, and yle-dl picks ffmpeg fallback but/or wrong link for them.
Maybe yle-dl does it itself, but one can "anticipate" the problem from outfile having extention mp3 and not flv (as with rtmpdmp)

Firefox also seem to pick another looking player, the fairly new "10 sec back jump circle", but might do it always even if stream still available as rtmp?

Some examples which are still there for a cpl of days.
THat is, almost all with 2-3 days left, 

https://areena.yle.fi/1-4553691

 IDM(win $20 dldr) picks above link and "does it" (note, a.mp3 and almost  typcal dxmnxd akamai expiration cookie)

https://ylekaod-a.akamaihd.net/s/p/1955031/sp/195503100/serveFlavor/entryId/0_swac41iz/v/2/flavorId/0_x7ndvzk7/name/a.mp3?__hdnea__=st=1540623030~exp=1540637430~acl=/s/p/1955031/sp/195503100/serveFlavor/entryId/0_swac41iz/v/2/flavorId/0_x7ndvzk7/name/a.mp3*~hmac=d285fc4eac7eec043ec2770564b5e3fb20145871062932264578e5d16b70c328

same when going frwrd on webpage
https://areena.yle.fi/1-4553712 fail
https://areena.yle.fi/1-4252145 available as rtmp, but also 10s akamai mp3(with IDM), old 2017 prgrm
https://areena.yle.fi/1-4252155 same, 2017 prgrm
https://areena.yle.fi/1-4271547 same, 2017 
https://areena.yle.fi/1-4492027 fail, month old, mp3,akamai HLS done ok by IDM
https://areena.yle.fi/1-4492029  same fail
etc.. etc

Gunnar
PS The "still avail in rtmp" or not, seem to depend on who and where on YLE the program is produced?
YLE upgtading studio equipment??

PPS dxmnxd Apple HLS and Akamai server: USA congress, c-span.org live stream changed to same a month ago, stream from swedish server.
But that  akamai cookie actually expires and the stream stopped if ffmpeg using old cookie.

Additionally one wld need to get that "new cookie" from a USA cable provider! (hope YLE doesnt do the same "by mistake")

Any tricks to calculate a new oneself from the X hour old one?? Back-Calculate the token,etc..
(was once "public secret" which at least was fun) . 
But I never got into the expiration part of that cookie.

PPS addtn;y Akamai keeps only latest 3 segments available, 30 seconds. ridiculous.
YLE does 2 or 4h for live streams... some default settings and default installer did this install..

**Comment by gunnar12** [comment]
Btw, with this new installation I once again run into "them eggs getting messed up"

Once again it was that easy-install.pth but additionally the local, .local and dist vs site-packages.
A dbl-checked mentioning of this would be good in the install instructions?

Havnt dbl-checked it, but additionally a matter of python versions?? Different directory trees there too!?
A true easy-install-mess..

**Comment by aajanki** [comment]
This should be fixed in the latest version.

> Btw, with this new installation I once again run into "them eggs getting messed up"

Use Python virtualenvs if you want to keep several versions of yle-dl.
