### ISSUE TITLE
new YLE Radio demands wget, doesnt work falling further back to ffmpeg?

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#171]
MeThinks that was my problem.

With wget yle-dl picks same or at least similar stream link as IDM (on windows)

but wget has problems retrying with https, SSL, and then, after that. ffmpeg gets wrong link??
Akamai cookies "protects your expired property??" with the wget link-protocol;??
(guess yle-dl wld have to get wget a newr cookie??)
(next I'll try same list without https, often just http works, one can avoid buggy SSL stuff, lost keys etc)

xxxxxxx
2018-10-29 22:31:11 (87.6 KB/s) - Connection closed at byte 10485760. Retrying.

--2018-10-29 22:31:12--  (try: 2)  https://ylekaod-a.akamaihd.net/s/p/1955031/sp/195503100/serveFlavor/entryId/1_ww6hfl5v/v/2/flavorId/0_5vhptwv1/name/a.mp3?__hdnea__=st=1540844951~exp=1540859351~acl=/s/p/1955031/sp/195503100/serveFlavor/entryId/1_ww6hfl5v/v/2/flavorId/0_5vhptwv1/name/a.mp3*~hmac=4eda6f909a66a08a194ad458f1e64281592ce88d69a310cd143c8bf332056c34
Connecting to ylekaod-a.akamaihd.net (ylekaod-a.akamaihd.net)|217.212.252.105|:443... connected.
Unable to establish SSL connection.

xxx

goin ffmpeg "Resume not supported on this stream"

xxx
WARNING: Resume not supported on this stream
Output file: F:\238\RSO_n kapellimestarina ja solistina András Schiff-2018-09-28T22_00_00+03_00.mp3
input format: 'https://cdnapisec.kaltura.com/p/1955031/sp/195503100/playManifest/entryId/1_ww6hfl5v/flavorId/0_5vhptwv1/forma
t/url/protocol/https/a.mp3?referrer=aHR0cHM6Ly9hcmVlbmEueWxlLmZp&playSessionId=11111111-1111-1111-1111-111111111111&clientTag
=html5:v2.67&preferredBitrate=600&uiConfId=37558971'
https://cdnapisec.kaltura.com/p/1955031/sp/195503100/playManifest/entryId/1_ww6hfl5v/flavorId/0_5vhptwv1/format/url/protocol/
https/a.mp3?referrer=aHR0cHM6Ly9hcmVlbmEueWxlLmZp&playSessionId=11111111-1111-1111-1111-111111111111&clientTag=html5:v2.67&pr
eferredBitrate=600&uiConfId=37558971: Invalid data found when processing input

Now downloading from URL 5/395: https://areena.yle.fi/1-4491987
xxxx
"Invalid data found when processing input" is what ffmpeg says! (that kaltura server says?)

**Comment by gunnar12** [comment]
At least wget and Akamai server protocol agrees to download with just http:// , no https:// (and no SSL back-and-forth)

download went OK, no retries, but Im on a backup internet connection using mobile 3G USB internet, has its own problems every now and then,,

That is, need better test for possible expiration of "private Akamai expired property"

**Comment by Akuli** [comment]
to me, it seems like it doesn't work with radio programs by default, but it works with `--backend=wget`

**Comment by aajanki** [comment]
The ffmpeg backend should now be able to download audio streams
