### ISSUE TITLE
Unsupported stream: No KS where KS is required

### ISSUE THREAD

**Issue by ReekyMarko** [aajanki/yle-dl#173]
When trying to download this url: https://areena.yle.fi/1-2895523
I get the following error:
```
ERROR: Unsupported stream: No KS where KS is required
We're sorry, access to this content is restricted.
```

Running the latest yle-dl-git from AUR

**Comment by aajanki** [comment]
I think that the "No KS" error means that you are trying to download geo-restricted content outside Finland. Are you located abroad? Would it be possible for you to test downloading from a Finnish IP address?

**Comment by ReekyMarko** [comment]
Sorry I totally forgot about this issue. I am abroad at the moment but I was using a VPN in Finland while trying to do this.

**Comment by aajanki** [comment]
According to [this discussion forum thread](https://hopeinenomena.fi/viewtopic.php?f=84&t=135041&start=525) Yle is blocking (some) VPN providers. Somebody on that thread is reporting seeing exactly the same "No KS where KS is required" message when using a blocked VPN.

There is not much else you can do that try a different VPN provider.
