### ISSUE TITLE
Unknown stream flavor

### ISSUE THREAD

**Issue by Twilrom** [aajanki/yle-dl#174]
If I try to download https://svenska.yle.fi/artikel/2014/04/03/tove-jansson-laser-smatrollen-och-den-stora-oversvamningen I get:
ERROR: Unsupported stream: Unknown stream flavor

**Comment by gunnar12** [comment]
Btw, any child and me need that HD video of still pic while listening..
lots a small and big details..

**Comment by aajanki** [comment]
Thanks for reporting. The support Arkivet audio streams had broken at some point, but should be ficed again at the latest Github commit.
