### ISSUE TITLE
ERROR: Unsupported stream: Media not found

### ISSUE THREAD

**Issue by topikissa** [aajanki/yle-dl#176]
Hi,

Some videos such as:

https://areena.yle.fi/1-4247408
https://areena.yle.fi/1-4199450

give the error message (in the topic) and cannot be loaded. Using the newest version version of the yle-dl from the master branch.

**Comment by aajanki** [comment]
yle-dl was not able to process videos that are available only as very low resolution mobile streams like your two examples cases. It is fixed on the git master branch now. Thanks for reporting!

**Comment by topikissa** [comment]
Thank you very much!
