### ISSUE TITLE
Subtitles occasionally not downloaded

### ISSUE THREAD

**Issue by ExTechOp** [aajanki/yle-dl#177]
On some files, subtitles do not initially get downloaded, and even trying --subtitlesonly does nothing.

% yle-dl --subtitlesonly -o Jack_London-An_American_Adventure-S01E01-First_Period.mp4 https://areena.yle.fi/1-3882504
yle-dl 20181221: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2018 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

% ls -l
total 1393440
-rw-rw-r--  1 1024 users 1426600926 Jan  8 08:27 Jack_London-An_American_Adventure-S01E01-First_Period.mp4

The strange feature of this problem is that trying to use --debug seems to cause it to work, and after that it works even without using the flag. Maybe it's actually some kind of a bug on the Areena side?

% yle-dl --subtitlesonly -o Jack_London-An_American_Adventure-S01E01-First_Period.mp4 https://areena.yle.fi/1-3882504
yle-dl 20181221: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2018 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

Subtitles saved to Jack_London-An_American_Adventure-S01E01-First_Period.fin.srt
Subtitles saved to Jack_London-An_American_Adventure-S01E01-First_Period.fihh.srt

% ls -l
total 1621944
-rw-rw-r--  1 1024 users      59336 Jan  8 08:33  Jack_London-An_American_Adventure-S01E01-First_Period.fihh.srt
-rw-rw-r--  1 1024 users      25733 Jan  8 08:33  Jack_London-An_American_Adventure-S01E01-First_Period.fin.srt
-rw-rw-r--  1 1024 users 1426600926 Jan  8 08:27  Jack_London-An_American_Adventure-S01E01-First_Period.mp4

**Comment by aajanki** [comment]
There has been similar reports once or twice before. I have not been able to debug this, because the problematic subtitles always seem to work when I get around to test them. For example, now the subtitles for your test case get downloaded just fine. I strongly suspect that this is some kind of momentary problem on the Areena side.

If you happen to come across another case, can you check 1) if you can see subtitles when playing the video on the web browser and 2) if `yle-dl --showmetadata ...` lists any urls in the "subtitles" array.

**Comment by ExTechOp** [comment]
Unfortunately, it happens so rarely that finding a test case is difficult. This time subtitles didn't get loaded, I checked with that viewing the document with subtitles on the website worked, and --subtitlesonly worked at that point. I forgot to check --showmetadata BEFORE doing this, I'll strive to remember it the next time.

% yle-dl -o America_in_Color-S01E02-The_1930s.mp4 https://areena.yle.fi/1-4192119
yle-dl 20181221: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2018 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

Output file: America_in_Color-S01E02-The_1930s.mp4
--2019-01-14 19:02:20--  https://cdnsecakmi.kaltura.com/p/1955031/sp/195503100/playManifest/entryId/1_kyd6ikjl/flavorId/1_zupzo8cq/format/url/protocol/https/a.mp4?uiConfId=43362851&referrer=aHR0cHM6Ly9hcmVlbmEueWxlLmZpLzEtNDE5MjExOQ==&playSessionId=11111111-1111-1111-1111-111111111111&clientTag=html5:v0.36.5
Resolving cdnsecakmi.kaltura.com (cdnsecakmi.kaltura.com)... 2.19.12.96
Connecting to cdnsecakmi.kaltura.com (cdnsecakmi.kaltura.com)|2.19.12.96|:443... connected.                                                                                                                                                     HTTP request sent, awaiting response... 302 Moved Temporarily                                                                                                                                                                                   Location: https://ylekaod-a.akamaihd.net/s/p/1955031/sp/195503100/serveFlavor/entryId/1_kyd6ikjl/v/1/ev/7/flavorId/1_zupzo8cq/name/a.mp4?__hdnea__=st=1547485340~exp=1547499740~acl=/s/p/1955031/sp/195503100/serveFlavor/entryId/1_kyd6ikjl/v/1/ev/7/flavorId/1_zupzo8cq/name/a.mp4*~hmac=029a8b7509754e8166234c4fd8a34d43e937ed2728e018d5de054ab78b4dc21d [following]
--2019-01-14 19:02:21--  https://ylekaod-a.akamaihd.net/s/p/1955031/sp/195503100/serveFlavor/entryId/1_kyd6ikjl/v/1/ev/7/flavorId/1_zupzo8cq/name/a.mp4?__hdnea__=st=1547485340~exp=1547499740~acl=/s/p/1955031/sp/195503100/serveFlavor/entryId/1_kyd6ikjl/v/1/ev/7/flavorId/1_zupzo8cq/name/a.mp4*~hmac=029a8b7509754e8166234c4fd8a34d43e937ed2728e018d5de054ab78b4dc21d                                                                                                                      Resolving ylekaod-a.akamaihd.net (ylekaod-a.akamaihd.net)... 193.229.109.173, 193.229.109.91                                                                                                                                                    Connecting to ylekaod-a.akamaihd.net (ylekaod-a.akamaihd.net)|193.229.109.173|:443... connected.
HTTP request sent, awaiting response... 200 OK                                                                                                                                                                                                  Length: 1399518573 (1.3G) [video/mp4]                                                                                                                                                                                                           Saving to: ‘America_in_Color-S01E02-The_1930s.mp4’                                                                                                                                                                                              
America_in_Color-S01E02-The_1930s.mp4                       100% [=================================>]   1.30G  5.78MB/s    in 4m 22s   
2019-01-14 19:06:42 (5.10 MB/s) - ‘America_in_Color-S01E02-The_1930s.mp4’ saved [1399518573/1399518573]

Stream saved to America_in_Color-S01E02-The_1930s.mp4                                                                                                                                                                                           

% ls -l America_in_Color-S01E02-The_1930s*
total 1701964
-rw-rw-r--   1 1024 users  274917376 Jan 14 19:03 America_in_Color-S01E02-The_1930s.mp4                                                                                                                                                         

% yle-dl --subtitlesonly -o America_in_Color-S01E02-The_1930s.mp4 https://areena.yle.fi/1-4192119
yle-dl 20181221: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2018 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3
Subtitles saved to America_in_Color-S01E02-The_1930s.fin.srt
Subtitles saved to America_in_Color-S01E02-The_1930s.fihh.srt
Subtitles saved to America_in_Color-S01E02-The_1930s.swe.srt

% yle-dl --showmetadata https://areena.yle.fi/1-4192119
[
  {
    "webpage": "https://areena.yle.fi/1-4192119",
    "title": "Historia: Amerikka v\u00e4rikuvissa: 1930-luku: S01E02-2019-01-14T06:00",
    "flavors": [
      {
        "media_type": "video",
        "height": 176,
        "width": 320,
        "bitrate": 179,
        "backends": [
          "ffmpeg"
        ]
      },
      {
        "media_type": "video",
        "height": 360,
        "width": 640,
        "bitrate": 466,
        "backends": [
          "ffmpeg",
          "ffmpeg",
          "wget"
        ]
      },
      {
        "media_type": "video",
        "height": 360,
        "width": 640,
        "bitrate": 666,
        "backends": [
          "ffmpeg",
          "ffmpeg",
          "wget"
        ]
      },
      {
        "media_type": "video",
        "height": 360,
        "width": 640,
        "bitrate": 942,
        "backends": [
          "ffmpeg",
          "ffmpeg",
          "wget"
        ]
      },
      {
        "media_type": "video",
        "height": 720,
        "width": 1280,
        "bitrate": 1473,
        "backends": [
          "ffmpeg",
          "ffmpeg",
          "wget"
        ]
      },
      {
        "media_type": "video",
        "height": 720,
        "width": 1280,
        "bitrate": 2577,
        "backends": [
          "ffmpeg",
          "ffmpeg",
          "wget"
        ]
      },
      {
        "media_type": "video",
        "height": 1080,
        "width": 1920,
        "bitrate": 4051,
        "backends": [
          "ffmpeg",
          "ffmpeg",
          "wget"
        ]
      }
    ],
    "duration_seconds": 2763,
    "subtitles": [
      {
        "url": "https://cdnsecakmi.kaltura.com/api_v3/index.php/service/caption_captionAsset/action/serve/captionAssetId/1_anxuhe42/ks/djJ8MTk1NTAzMXyyCE-bEsZjup3Vx_HWQTeNnDCPhqcUv3qR_-P_d_kDSzR0zAOSGLynsuBH_Or_ZqBSk4fxAH9qsyR9KibJUcwfmbcZyEidt6sWYikw-chuCW3-FiRoKcRyOAJPNCk9POjSM_ZVSfqZtCF_JjY-VWFP--sXq9RcSJ9glYoXg4o3u3pvjUlIExHdsO0WpHO3z01qNv9a0bGlriRr_eJmPKjg",                                                                                                                           "lang": "fin"
      },
      {
        "url": "https://cdnsecakmi.kaltura.com/api_v3/index.php/service/caption_captionAsset/action/serve/captionAssetId/1_jwl39jow/ks/djJ8MTk1NTAzMXxgnqIJLptXkQwLKunj6RHZK5lEww6oilpVkweuHF9BHL0jOYZsW1gVkUxt68tZvlYDaqM21EHNsgVRBar4DCzgCKaI-retNJf1ZfF8EHLQ2Mi6rjxKIiq3QRv4ddwLZdvMfoU5BO8bDRlV8nHJqED8pnK8M743gzVSJw61L_eyO8pPJ0CLLwuSz5R7rPevQoaBEL19DasHpGSSQXQppdTR",                                                                                                                           "lang": "fihh"
      },
      {
        "url": "https://cdnsecakmi.kaltura.com/api_v3/index.php/service/caption_captionAsset/action/serve/captionAssetId/1_o73wqesb/ks/djJ8MTk1NTAzMXyI_gk9FEbHJbfBZK4ajzMYwClR_klOXzggW38OhKfXrZcluB2Rc1rAWicbkh5f_Etr2LUL8RaAlFGwKu11Jr2xHAxJ9oHDxm0zqAFF7Rsh-UJB9WYfVVbSx6zeGLpNEIF0K1Epq05cyxIgUP8uQT_U5mcobD5bZXGKWz1umvoCS6DeIMppfoBuXgXAYLu1bkVCGeT3ID4yW5xNQpkpN0EO",                                                                                                                           "lang": "swe"
      }
    ],
    "region": "Finland",
    "publish_timestamp": "2019-01-14T06:00:00+02:00",
    "expiration_timestamp": "2019-04-14T23:59:59+03:00"
  }
]]

**Comment by ExTechOp** [comment]
All right, I've now figured out what happens: once the Areena video viewer has been used to view the subtitles, then subtitles can be found also by yle-dl and downloaded.

Here is a session where I first attempt to download subtitles, fail, save the metadata, then view the subtitles on Areena, succeed in downloading the subtitles, and compare the changed metadata:

% ls -l MOT-Riivaajat_kirkossa*                                                                                                                                                                                                       -rw-rw-r-- 1 1024 users 323333623 Dec 30 14:51 MOT-Riivaajat_kirkossa.mp4

% yle-dl --subtitlesonly -o MOT-Riivaajat_kirkossa.mp4 https://areena.yle.fi/1-1806102
yle-dl 20181221: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2018 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3                                                                                                                                                                      

% yle-dl --showmetadata https://areena.yle.fi/1-1806102 >& metadata1.txt

=== At this point I view the file on the Areena web interface and enable "ohjelmatekstit" (fihh.srt subtitles) ===

% yle-dl --subtitlesonly -o MOT-Riivaajat_kirkossa.mp4 https://areena.yle.fi/1-1806102
yle-dl 20181221: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2018 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

Subtitles saved to MOT-Riivaajat_kirkossa.fihh.srt

% yle-dl --showmetadata https://areena.yle.fi/1-1806102 >& metadata2.txt

% diff -w metadata*
61c61,66
<     "subtitles": [],
---
>     "subtitles": [
>       {
>         "url": "https://cdnsecakmi.kaltura.com/api_v3/index.php/service/caption_captionAsset/action/serve/captionAssetId/1_q404i2cu/ks/djJ8MTk1NTAzMXwLcGQgEW7e3NOtRPI--SJKJTdZqK5nhtsb_uP2bo5xa34L53DcKpIOQywta6nKM-WMrxaeGzjyw1XP4KzPn5_HuxFovc-Bt7TSz-aGE5XYuDq0I7GcOHf905h8eKHYCAHE7LuAciRMKJYJ38BPbfRBzkLkEqo8K_u1w_AYPjFyGpB3WD7rvaTFpcNajo3kTkbtaDnPntASHXEVY7eRxVZC",
>         "lang": "fihh"
>       }
>     ],

% ls -l MOT-Riivaajat_kirkossa*
-rw-rw-r-- 1 1024 users     28269 Jan 14 20:12 MOT-Riivaajat_kirkossa.fihh.srt
-rw-rw-r-- 1 1024 users 323333623 Dec 30 14:51 MOT-Riivaajat_kirkossa.mp4

**Comment by Jormangeud** [comment]
> All right, I've now figured out what happens: once the Areena video viewer has been used to view the subtitles, then subtitles can be found also by yle-dl and downloaded.
> 
I can confirm this. Got a video downloaded without any subtitles. Only after activating the subtitles in the webplayer, the subtitles got downloaded.

**Comment by aajanki** [comment]
Yes, it looks like the API yle-dl uses to get subtitle URLs, actually only returns subtitles when one has recently played the video with subtitles activated on the web browser.

I also found out that Areena web is no longer using that API, so I'm assuming that the API is being deprecated. I'm planning to get rid of the API call completely and switch to using embedded subtitle tracks like the current Areena web player. So subtitles will be embedded in the mp4 file instead of being downloaded as external files.

There is a somewhat preliminary implementation on the git master. There are some issues, like yle-dl still downloads the external subtitles (in addition to embedded ones) and vlc reporting the language of every subtitle track as English. yle-dl will start using ffmpeg as the default download backend because only ffmpeg can handle embedded subtitles.

**Comment by aajanki** [comment]
The latest version (which I released today as version 20190203) downloads subtitles using the new API and embeds them to the output video file. The subtitle language metadata is still wrong, every subtitle shows up as English.
