### ISSUE TITLE
Feature-request: "-q" option to hide excess information, "wget --xattr" like option to preserve URL in downloaded files

### ISSUE THREAD

**Issue by j4riv** [aajanki/yle-dl#179]
Feature-request: "-q" option to hide excess information
 Output should be less than 10 lines unless there are errors.

"wget --xattr" like option to preserve command line/URL in downloaded files
 "What is this file? Do I need it or can I delete it?" Multiple files are loaded with one command. Also handy if download of higher quality version is necessary ("$ getfattr -d file")
Put date/timestamp in attr ("2018-01-23T04_00_00+03_00" from filename)

**Comment by ExTechOp** [comment]
The ffmpeg output is by default inconveniently wider than 80 characters, and will scroll excessively unless you set the screen width to be ~97 characters. I've been reading the documentation, but unfortunately there does not seem to be any way to adjust this output.

**Comment by aajanki** [comment]
There's now a new option `-q` for less verbose output (progress bar and warnings) and `-qq` for even more quiet (no progress, errors only).

**Comment by aajanki** [comment]
I just released version 20221015 that includes `--xattrs` command line option for saving the URL (and some other metadata) as file attributes.
