### ISSUE TITLE
All streams downloaded for some videos

### ISSUE THREAD

**Issue by uusijani** [aajanki/yle-dl#181]
I'm using version 20190203.

Yesterday I noticed a couple of videos took a particularly long time to download, and the resulting files contained all the available streams, as opposed to just the best. For instance, the streams downloaded for https://areena.yle.fi/1-50067640:

    $ ffprobe Mäkihypyn\ maailmancup\:\ Mäkihypyn\ MC\:\ HS\ 130\,\ miesten\ karsinta-2019-02-08T20\:31.mp4 2>&1 | grep Stream
        Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 480x270 [SAR 1:1 DAR 16:9], 299 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc (default)
        Stream #0:1(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 480x270 [SAR 1:1 DAR 16:9], 299 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc
        Stream #0:2(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 640x360 [SAR 1:1 DAR 16:9], 749 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc
        Stream #0:3(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 640x360 [SAR 1:1 DAR 16:9], 749 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc
        Stream #0:4(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 960x540 [SAR 1:1 DAR 16:9], 1499 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc
        Stream #0:5(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 960x540 [SAR 1:1 DAR 16:9], 1499 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc
        Stream #0:6(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 2499 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc
        Stream #0:7(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 2499 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc
        Stream #0:8(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 3499 kb/s, 50 fps, 50 tbr, 90k tbn, 100 tbc
        Stream #0:9(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 3499 kb/s, 50 fps, 50 tbr, 90k tbn, 100 tbc
        Stream #0:10(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s (default)
        Stream #0:11(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s
        Stream #0:12(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s
        Stream #0:13(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s
        Stream #0:14(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s
        Stream #0:15(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s
        Stream #0:16(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s
        Stream #0:17(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s
        Stream #0:18(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s
        Stream #0:19(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s

The only other one exhibiting this I've come across so far is https://areena.yle.fi/1-50044648 (a hefty download even without the excess streams due to the length, but with all streams 25 GB in total).

An example of the previous behavior is https://areena.yle.fi/1-4538143 (published after the other two mentioned, so this is apparently not enacted for all recent publications):

    $ ffprobe file:"Sohvaperunat: S07E02-2019-02-09T10:31.mp4" 2>&1 | grep Stream
        Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 3819 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
        Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)

The lower quality streams should be easy enough to slice out of the mp4 after downloading, but of course it'd be optimal not to waste the bandwidth downloading them in the first place.

**Comment by aajanki** [comment]
Thanks for reporting!

As a first aid, I modified yle-dl to download only the first video and audio streams on multi-bitrate streams to limit the total downloaded size.

It seems that the first stream is the lowest bitrate one (at least in the two test cases). I plan to implement bitrate and resolution filtering properly later.
