### ISSUE TITLE
All subtitles missing for some videos

### ISSUE THREAD

**Issue by topikissa** [aajanki/yle-dl#184]
The following videos are missing the subtitles completely:
https://areena.yle.fi/1-4106701
https://areena.yle.fi/1-4106709
https://areena.yle.fi/1-4106703

Using the most recent yle-dl version from github and ffmpeg version n4.1.1. (from ubuntu snap store).

For most other videos the subtitles are downloaded correctly.

With the yle-dl version 20181221 also the above links have subtitles downloaded correctly.

**Comment by rhoeden** [comment]
I can confirm this on Arch Linux with ffmpeg 4.1.1 and both yle-dl/yle-dl-git from aur.

yle-dl 20181221 does indeed work perfectly

**Comment by aajanki** [comment]
The subtitles are working with the git HEAD now. This might have been some kind of temporary problem at Areena server or maybe this is something similar to #177 and one has to start viewing the video on the Areena web player before the subtitles become downloadable.

If you find other cases with missing subtitles, post the URLs here.

**Comment by uusijani** [comment]
I'm using yle-dl from the HEAD and [ffmpeg & ffprobe built from git](https://johnvansickle.com/ffmpeg/). For the three URLs listed above, I could only get subtitles to download for the last one (with `--debug`) _until_ I tried playing it in the web player, _after which_ they were no longer downloaded for that one either. Aargh :)

[Here's `--debug` output for the first download](https://github.com/aajanki/yle-dl/files/2910667/before.log) (before opening in webplayer), resulting in subtitles being downloaded.

[Here's `--debug` output for the latter download](https://github.com/aajanki/yle-dl/files/2910669/after.log) (after opening in webplayer), resulting in subtitles not being downloaded.

**Comment by teroyks** [comment]
At the moment, it seems subtitles are missing from all videos (latest macOS, yle-dl 20190203, ffmpeg 4.1.1).

Example video URL: https://areena.yle.fi/1-4457868

**Comment by aajanki** [comment]
@teroyks  Can you try with the latest yle-dl git HEAD?

If that doesn't work, can you send me the debug output of `yle-dl -V https://areena.yle.fi/1-4457868`?

Do you get subtitles, if you first start playing the video on the Areena web page for a few seconds and then try yle-dl again?

**Comment by teroyks** [comment]
For some reason, I'm not able to install the latest version from source. I get the following error message:
```
$ python3 setup.py install --user
running install
error: can't combine user with prefix, exec_prefix/home, or install_(plat)base
```

**Comment by aajanki** [comment]
Can you send me the output of `yle-dl -V https://areena.yle.fi/1-4457868` (for example, by email. See my email address in README.fi)?

The error with `--sublang fin` is intentional. On recent versions, the only legal options are "all" and "none".

**Comment by tp0** [comment]
@topikissa 
> and ffmpeg version n4.1.1. (from ubuntu snap store).

I think that is your issue. The ffmpeg in the Snap store is not complied with HTTPS support and when you use `yle-dl -V` you will see it complains about lack of https protocol support. And those files it can't fetch appear to be the subtitle files.

You can use the static builds from [here](https://johnvansickle.com/ffmpeg/) and then just add it to your PATH.

**Comment by tp0** [comment]
> Can you send me the output of `yle-dl -V https://areena.yle.fi/1-4457868` (for example, by email. See my email address in README.fi)?

Here is my output: https://gist.github.com/tp0/7c29fcaa8e7b7554c21503617721561d

yle-dl: git master
ffmpeg: 4.1.3-static

Another example video: https://areena.yle.fi/1-4355000 (and no problem with version 20181221).

**Comment by aajanki** [comment]
I believe this is now fixed. There was a bug in the stream selection logic that randomly caused yle-dl to select a stream flavor without subtitles even though the subtitles were available.
