### ISSUE TITLE
New YLE 1-5000 "sports" server?

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#185]
New YLE 1-5000xxxxx "sports" server since cpl days ago?
Or is it my windows-install picking, mixing old version egg-packets again?
picking wrong ffmpeg? (who actly gets the manifest?)

"cant get manifest" and seems to be yleawodamd.akamaized.net  when eavesdropping on firefox, new to me.

PS some retries on ffmpeg wld also be good.  With 10-20s inbetween. I sometimes get "failed to resolve hostname", wld work 10-20s later.
Same thing with wget, it retries but without "waiting inbetween", bang-bang-bang-bang and quits.

With some wget setting? I havnt searched for that. (ffmpeg documentation even worse, timeouts for everything and nothing, made for reading from HDisk)
Or better, in yle-dl python code so it is easy to customize to anything, sound alarms,add to log file, blink the screen, etc.

1st try 10s delay, 2de 20s, etc is the good old one.

PPS One of worst problmes with ffmpeg is actly the old history of "input from HDisk".
Accessing thrgh internet protocol is "forced into the code" and very little in terms of avoiding getting stuck in libs, sockets or deeper down, no timeouts, retries and that silly lack of "resume" (stream data received in segments anyway, easy to re-read, buffer until correct, ref adobehds)

Kind of "teenager code", works perfectly, at least once! (but probably not twice if something goes wrong)

hmm, found "setting --retry-connrefused lets wget retry even after a »connection refused« error."
Akamai likes to refuse...protects expired private property..
how many times, delay inbetween??

**Comment by aajanki** [comment]
Can you post an example URL that is causing problems?

**Comment by gunnar12** [comment]
post an example URL/

today "500-sports"


https://areena.yle.fi/1-50080482
https://areena.yle.fi/1-50080418
https://areena.yle.fi/1-50080233

but not eduskunta, if sticking to 1-500 links
https://areena.yle.fi/1-50080642

--showmetadata gives
Now downloading from URL 1/5: https://areena.yle.fi/1-50080482
[
  {
    "webpage": "https://areena.yle.fi/1-50080482",
    "flavors": [
      {
        "error": "Manifest URL is missing"
      }
    ],
    "embedded_subtitles": []
  }
]

**Comment by gunnar12** [comment]
yepyep, checked yle nyheter dwnloaded almost imm after publish


Name: Yle Nyheter TV-nytt-2019-02-28T19_29_55+02_00.mp4
Video
Resolution: 1280 x 720
Aspect ratio: 1.77778
Format: h264
Bitrate: 1841 kbps
Frames per second: 25.000000
Selected codec: h264

**Comment by gunnar12** [comment]
Virgin Ubuntu installation, virgin yle-dl installation, same "Manifest is missing" for most "1-500 sports" streams.

Seems the backend is called with an empty  hls_manifest_url by full_hd_flavors(self, hls_manifest_url, media_type)

Can anyone at least check the links??

https://areena.yle.fi/1-50080482
https://areena.yle.fi/1-50080418
https://areena.yle.fi/1-50080233

**Comment by teepean** [comment]
Latest Flickfetch manages to download 1-500 links. I copied the output to pastebin:

https://pastebin.com/FpE47Q6t

**Comment by lsolin** [comment]
> Virgin Ubuntu installation, virgin yle-dl installation, same "Manifest is missing" for most "1-500 sports" streams.
> 
> Seems the backend is called with an empty hls_manifest_url by full_hd_flavors(self, hls_manifest_url, media_type)
> 
> Can anyone at least check the links??
> 
> https://areena.yle.fi/1-50080482
> https://areena.yle.fi/1-50080418
> https://areena.yle.fi/1-50080233

I also get "Manifest URL is missing" with Ubuntu and yle-dl 20182112.

**Comment by gunnar12** [comment]
I also get "Manifest URL is missing" with Ubuntu and yle-dl 20182112./

Thanks!!

**Comment by gunnar12** [comment]
Flickfetch manages to download/

Yes, so does other downloaders. Problem is not "YLE" but something in yle-dl not finding the right URL to the manifest.
Quick print-debug showed an empty URL, but with python one can never be sure what a variable is, string, array or floating number or whatever..
