### ISSUE TITLE
title-series-name=date template ok, but

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#186]
title-series-name=date template ok, but

lacks the old "original" +02_00.mp4 format, instead 0200.mp4.
Cldnt find where to "patch", in some other module somewhere far away behind Python secret string handling?( in new breakout of handling title, date, etc)

Any hint on how and where?

Wld be nice when I am searching directories for all "old title variations" to avoid re-downloading and also moving expiring streams to another HD.
Even finding "same stream but published, downloaded years ago"
(ffmpeg doesnt download the exact same file every time, size and thus CRC different, compare adobehds which did exact same downloads from same segments)

PS looked into ffmpeg "resume" long time ago, but got stuck in how ffmpeg re-arranges segment data, audio, video,etc..  "re-muxes on the fly" etc even when "copy" for both.
SHld, must be done at "buffering segments-frags" level?()6-10s some MBytes, to HDisk temps. like adobehds)

Kind of sad, bc one idea with the short numbered segments is to make re-trying, buffering until correct possible, but AFAKL, no code for it in ffmpeg?
Wld solve most ffmpeg internet-stream problems... in one place..

**Comment by aajanki** [comment]
I left the time zone out intentionally, because all timestamps are at Finnish time zone, anyway. If you want to change this for yourself, take a look at TitleFormatter._timestamp_string() at yledl/titleformatter.py.
