### ISSUE TITLE
All subtitles saved as eng

### ISSUE THREAD

**Issue by arranna** [aajanki/yle-dl#187]
When downloading an episode all subtitles are saved as eng(lish). Example:
https://areena.yle.fi/1-1510909

VLC also show them as english and they are not english but finnish/swedish.

I also tried the git HEAD version.

[ffprobe.txt](https://github.com/aajanki/yle-dl/files/2934767/ffprobe.txt)
[debug.txt](https://github.com/aajanki/yle-dl/files/2934806/debug.txt)

**Comment by aajanki** [comment]
This is now fixed in the current git HEAD. The latest version downloads videos as Matroska (.mkv) files. I couldn't figure out how to get ffmpeg to correctly label subtitles languages in mp4 files, but it works in Matroska.
