### ISSUE TITLE
Detected Stream type, Detected Flavors and Selected

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#190]
While struggling with flavors, please add a --showstreamflavor or similar argument which only shows, for example from present code, or just the most important info.

One reason, seems more and more YLE programs are first publushed at a lower resolution and hours or only next day in full resolution.
(Iam adding an alarm if aamuTV,Astudio etc not yet at full resolution, plus a different name when lower)

That is, not needing the full debug logging
xxxxxx
Detected an HTML5 media

[StreamFlavor(media_type='video', height=176, width=320, bitrate=162, streams=[<yledl.backends.HLSBackend
 object at 0x0000000004713B70>], hard_subtitle=None), StreamFlavor(media_type='video', height=360, width=
640, bitrate=452, streams=[<yledl.backends.HLSBackend object at 0x0000000004713CC0>, <yledl.backends.HLSB
ackend object at 0x0000000004713D30>, <yledl.backends.WgetBackend object at 0x0000000004713DD8>], hard_su
btitle=None), StreamFlavor(media_type='video', height=360, width=640, bitrate=651, streams=[<yledl.backen
ds.HLSBackend object at 0x0000000004713E80>, <yledl.backends.HLSBackend object at 0x0000000004713EF0>, <y
ledl.backends.WgetBackend object at 0x0000000004713F98>], hard_subtitle=None), StreamFlavor(media_type='v
ideo', height=360, width=640, bitrate=936, streams=[<yledl.backends.HLSBackend object at 0x00000000046FA7
48>, <yledl.backends.HLSBackend object at 0x00000000047082E8>, <yledl.backends.WgetBackend object at 0x00
000000047083C8>], hard_subtitle=None), StreamFlavor(media_type='video', height=720, width=1280, bitrate=1
455, streams=[<yledl.backends.HLSBackend object at 0x0000000004708358>, <yledl.backends.HLSBackend object
 at 0x0000000004708470>, <yledl.backends.WgetBackend object at 0x00000000047086A0>], hard_subtitle=None),
 StreamFlavor(media_type='video', height=720, width=1280, bitrate=2584, streams=[<yledl.backends.HLSBacke
nd object at 0x00000000047080B8>, <yledl.backends.HLSBackend object at 0x0000000004708CF8>, <yledl.backen
ds.WgetBackend object at 0x0000000004708240>], hard_subtitle=None), StreamFlavor(media_type='video', heig
ht=1080, width=1920, bitrate=4068, streams=[<yledl.backends.HLSBackend object at 0x0000000004708A90>, <yl
edl.backends.HLSBackend object at 0x00000000047081D0>, <yledl.backends.WgetBackend object at 0x0000000004
708940>], hard_subtitle=None)]
Available flavors:
bitrate: 162, height: 176, width: 320, hard_subtitle: None
bitrate: 452, height: 360, width: 640, hard_subtitle: None
bitrate: 651, height: 360, width: 640, hard_subtitle: None
bitrate: 936, height: 360, width: 640, hard_subtitle: None
bitrate: 1455, height: 720, width: 1280, hard_subtitle: None
bitrate: 2584, height: 720, width: 1280, hard_subtitle: None
bitrate: 4068, height: 1080, width: 1920, hard_subtitle: None
max_height: None, max_bitrate: None
Selected flavor: StreamFlavor(media_type='video', height=1080, width=1920, bitrate=4068, streams=[<yledl.
backends.HLSBackend object at 0x0000000004708A90>, <yledl.backends.HLSBackend object at 0x00000000047081D

**Comment by aajanki** [comment]
There is already the `--showmetadata` option that outputs lots of information in a parseable JSON format. Does that include the information you need? If not, what pieces of information should be added?

**Comment by gunnar12** [comment]
There is already the --showmetadata option that outputs lots of information in a parseable JSON format. Does that include the information you need? /

My whole point was to get |the most important" from --shiwmetadata on 3-4-5 lines before yle-dl shiws it starts downloading that specific stream.
- possible and picked resolution
- duration
- etc

to give the user an idea "hows it going", "how much time until done", "do I want this". etc without having to run one pre-run and read, search the log file page up and down (list usage)

**Comment by aajanki** [comment]
I don't have the time to implement this, sorry. However, you can do it yourself. Write a script that calls yle-dl twice, first with `--showmetadata` piped to [jq](https://stedolan.github.io/jq/) or some other JSON parser, which extracts whatever information you want and shows it in a nice format, and then a second yle-dl call to perform the actual download.
