### ISSUE TITLE
Anything wrong with --highest/lowest resolution

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#192]
Anything wrong with --highest/lowest resolution switch  for newnew 1-500 sports streams like this?

At least an easy quick fix/fix? Just call ffmpeg without -map argument!
I have no idea what it does to subtitles which seem to call the same code, or embedded or whatever as I use this only for them those special newnew cases picking the lowest resolution? 

Does any stream-case, which demands some -map arguments for ffmpeg, use this code-path??

By deleting the -map argument to ffmpeg it selects highest resolution.
while '-map', '0:v:0', '-map', '0:a:0' pick the first and lowest?

backends.py

        args = (['-bsf:a', 'aac_adtstoasc',
                 '-codec', 'copy',
                 '-map', '0:v:0', '-map', '0:a:0'] + subtitles_args +
                ['file:' + output_name])

## over-ride without -map arguments
				
        logger.info('args:  ')
        logger.info(args)

        args = (['-bsf:a', 'aac_adtstoasc',
                 '-codec', 'copy']
                 + subtitles_args +
                ['file:' + output_name])
	
        logger.info('args:  ')
        logger.info(args)
##        sys.stdin.read(1) 			

PS Btw, one can easily run two different versions of yle-dl!

- one version started with plain yle-dl, compiled with that ....install  -user

another for and only as sudo!

- started with "sudo yle-dl" and compiled with "sudo python setup.py install" WITHOUT the --user

**Comment by aajanki** [comment]
The resolution selection is currently broken on some streams. This is related to bug #181 .

The `-map` is needed on certain multi-bitrate streams. Without the `-map` these streams would result in huge downloads that include all available resolutions in one file.
