### ISSUE TITLE
while I remember, found <tab> (\t) in a cpl of titles

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#193]
while I remember, found <tabs> (\t) on a cpl of titles, windows NTFS doesnt like it.
I think when run on linux and ntfs-partition, the filename got replaced by a short-name?
At least once??

Anyway, added '\t' to ASCII to encode list of, to be replaced by underscore, for both --vfat and linux.
Not sure what all versions of ffmpeg says abt tabs in filenames??

yledel.py:
excludechars = '\"*/:<>?|\t' if args.vfat else '*/|\t'

**Comment by aajanki** [comment]
This is now fixed in git HEAD. Thanks for reporting!
