### ISSUE TITLE
Warning, new YLE areena strategy!

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#194]
First time I seem it today

- Yle Aamu-TV, which usually is Areena-available after many hours, afternoon, full resolution sometimes only next day was today "available very soon"

Great surprise but yle-dl said "media not available" or similar (dont blame yle-dl)
Firefox starts the stream OK, but only 1080x720 resolution..hmm..!

- the Reason

YLE posts an icon, program ID etc but it goes to Tv1Live stream.

Like this (what ffmpeg would "need")

https://yletvhdliveworld-lh.akamaihd.net/i/yletv1hdworld_1@187592/master.m3u8?__b__=1064&set-segment-duration=quality&start=2019-03-27T06:25:00.000+02:00&end=2019-03-27T09:30:01.760+02:00

Interesting to see when regular full resolution appears and how??

Detect server frm metadata (its there) and print suitable error message?
Best, if in list, move URL to bottom or later in list!!

PS seems the "live 4h back in time" has changed too, longer, but havnt checked manifest index-fragments..

CHecked, latest 23.9999 hours now available

first and last
https://yletvhdliveworld-lh.akamaihd.net/i/yletv1hdworld_1@187592/segment15665240_2764_av-b.ts?sd=10
https://yletvhdliveworld-lh.akamaihd.net/i/yletv1hdworld_1@187592/segment15656603_2764_av-b.ts?sd=10
segments = 8637 = 24h

PPS  Ffmpeg supports starting from the middle of segment list as follows, at least some versions do

ffmpeg.exe -live_start_index 1238 (can be negative. althgh probly doesnt support the start & end times in the manifest arguments) 

dont remeber if shld be negative  or positive index offset, if from beginning (24h ago) or now
Ffmpeg code is tough and bad, with ifs and butts and abs calculations

**Comment by aajanki** [comment]
It should now be possible to download a stream right after a live broadcast has finished.

It seems that after a live broadcast has finished the program is available in one format and after 10 minutes or more in different format. There might be even more format changes later on. So, you get slightly different stream depending on when exactly you run download.
