### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by highcast** [aajanki/yle-dl#20]
Platform: Ubuntu x86 on vmware player, network is proven to work properly..

someone@ubuntu:~$ yle-dl http://areena.yle.fi/radio/1994546
Output file: Parasta ennen! pe klo 20.00-2013-08-30T20:00:00.flv
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
ERROR: RTMP_Connect0, failed to connect socket. 111 (Connection refused)

**Comment by aajanki** [comment]
I'm closing this very old bug report. I haven't encountered the error in years, so I'm assuming that it has been fixed in rtmpdump since you reported it.
