### ISSUE TITLE
WebVTT subtitle problems

### ISSUE THREAD

**Issue by karsta62** [aajanki/yle-dl#202]
****Kubuntu 18.04.02 / yle-dl 20190502** / ffmpeg version 4.1.3-0york1~18.04** 
Downloads one mkv file with embedded unplayable subtitles.
From mkvinfo:
_|  + Track number: 3 (track ID for mkvmerge & mkvextract: 2)
|  + Track UID: 3
|  + Lacing flag: 0
|  + Language: fi
|  + Codec ID: D_WEBVTT/SUBTITLES
|  + Track type: subtitles_

VLC player can show video and play audio, but not the subtitles. The same with kaffeine player and a set top box Vu+ Duo2. I've not been able to extract the subtitles to other than ".mks" which I haven't been able to convert to srt or any text subtitles.

When choosing the subtilte stream in VLC, the debug output is:

_main debug: looking for spu decoder module matching "any": 22 candidates
main debug: no spu decoder modules matched
main error: could not identify codec
main debug: killing decoder fourcc ` '_

The only player capable of showing the downloaded mkv with subtitles so far is QMPlay2 v.18.07.03 so far, but that does not serve my needs.

Exact example source:
_$ yle-dl --sublang all --latestepisode https://areena.yle.fi/1-3917928
yle-dl 20190502: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2019 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3_

_Output file: Medicit, Firenzen valtiaat: Vastuksia ja tilaisuuksia: S02E03-2019-05-24T20:00.mkv
frame=82236 fps= 82 q=-1.0 Lsize= 1596251kB time=00:54:49.47 bitrate=3975.2kbits/s speed= 3.3x    
Stream saved to Medicit, Firenzen valtiaat: Vastuksia ja tilaisuuksia: S02E03-2019-05-24T20:00.mkv_

Is there any way to get something like "srt" subtitles as before?

**Comment by lsolin** [comment]
yle-dl 20181221 still does the job. The only thing I've noticed that doesn't work is downloading a live stream, but that doesn't really work with the new version either: I can only get a 396p video.

**Comment by aajanki** [comment]
Can you try with the latest version on Github? I changed yle-dl to save subtitles as srt (still embedded inside the video file, not as a separate file).

**Comment by karsta62** [comment]
Great. I will try but it'll take a few days. I'll let you know.

**Comment by karsta62** [comment]
ok, I removed pip installation and then cloned from https://github.com/aajanki/yle-dl and installed by instructions. The version number did not change (20190502:) and neither anything else that I would have noticed. Still webvtt subtitles embedded in an mkv file. What went wrong?

**Comment by aapo** [comment]
yledl untagged version, git f95e0583a49dc6f4d31f4735e9faad2ef1ca32e3 subtitle problems with vlc

yle-dl https://areena.yle.fi/1-4438401
Subtitles are not workingat all, tested with vlc, mplayer, parole.
Only parole gave any errors: "Parole needs application/x-subtitle-unknown decoder to play this file."
[https://git.xfce.org/apps/parole]

mediainfo [https://mediaarea.net/en/MediaInfo] shows:

    Text #1
    ID                                       : 3
    Format                                   : D_WEBVTT/SUBTITLES
    Codec ID                                 : D_WEBVTT/SUBTITLES
    Duration                                 : 40 min 33 s
    Language                                 : Finnish
    Default                                  : Yes
    Forced                                   : No
    Comment                                  : käännöstekstitys
    VARIANT_BITRATE                          : 4190242
    
    Text #2
    ID                                       : 4
    Format                                   : D_WEBVTT/SUBTITLES
    Codec ID                                 : D_WEBVTT/SUBTITLES
    Duration                                 : 42 min 47 s
    Language                                 : Swedish
    Default                                  : Yes
    Forced                                   : No
    Comment                                  : översättning
    VARIANT_BITRATE                          : 4190242
    
    Text #3
    ID                                       : 5
    Format                                   : D_WEBVTT/SUBTITLES
    Codec ID                                 : D_WEBVTT/SUBTITLES
    Duration                                 : 43 min 54 s
    Language                                 : Finnish
    Default                                  : Yes
    Forced                                   : No
    Comment                                  : ohjelmatekstitys
    VARIANT_BITRATE                          : 4190242

/yle-dl --preferformat mp4  https://areena.yle.fi/1-4438401
mediainfo:

    Text #1
    ID                                       : 3
    Format                                   : Timed Text
    Muxing mode                              : sbtl
    Codec ID                                 : tx3g
    Duration                                 : 40 min 33 s
    Bit rate mode                            : Variable
    Bit rate                                 : 42 b/s
    Stream size                              : 12.6 KiB (0%)
    Language                                 : English
    Default                                  : Yes
    Forced                                   : No
    Alternate group                          : 3
    
    Text #2
    ID                                       : 4
    Format                                   : Timed Text
    Muxing mode                              : sbtl
    Codec ID                                 : tx3g
    Duration                                 : 42 min 47 s
    Bit rate mode                            : Variable
    Bit rate                                 : 51 b/s
    Stream size                              : 16.0 KiB (0%)
    Language                                 : English
    Default                                  : No
    Forced                                   : No
    Alternate group                          : 3
    
    Text #3
    ID                                       : 5
    Format                                   : Timed Text
    Muxing mode                              : sbtl
    Codec ID                                 : tx3g
    Duration                                 : 43 min 54 s
    Bit rate mode                            : Variable
    Bit rate                                 : 63 b/s
    Stream size                              : 20.1 KiB (0%)
    Language                                 : English
    Default                                  : No
    Forced                                   : No
    Alternate group                          : 3
    
vlc is not showing subtitles.
mplayer and parole works.

**Comment by lsolin** [comment]
Latest yle-dl ([](https://github.com/aajanki/yle-dl/tarball/master)), ffmpeg version 3.4.4, Xubuntu 16.04

I get working subtitles (vlc) with both examples [](https://areena.yle.fi/1-3917928) and [](https://areena.yle.fi/1-4438401), mkvinfo shows:

+ Track number: 1 (track ID for mkvmerge & mkvextract: 0)
|  + Track UID: 1
|  + Lacing flag: 0
|  + Language: fi
|  + Codec ID: S_TEXT/UTF8
|  + Track type: subtitles

**Comment by karsta62** [comment]
Current status with https://areena.yle.fi/1-50094878.
Changed, but still unusable.
mkv file now contains srt subtitles, but VLC acts the same as before and is unable to show any of them.

mkvextract can extract swedish subs to srt, and claims the same with finnish, but the finnish output is not recognized by VLC nor subtitleeditor. Opening with text editor shows that it's not proper .srt unlike the swedish is.

**Mediainfo of the downloaded mkv:**
_Text #1
ID                                       : 1
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 51 min 13 s
Writing library                          : Lavc58.35.100 srt
Language                                 : Finnish
Default                                  : Yes
Forced                                   : No
Comment                                  : käännöstekstitys
VARIANT_BITRATE                          : 1564127_

**Mediainfo of the extracted finnish srt (as you can see, there is more than subs):**
mediainfo subs.srt 
General
Complete name                            : subs.srt
Format                                   : ADTS
Format/Info                              : Audio Data Transport Stream
File size                                : 49.8 MiB
Overall bit rate mode                    : Variable
FileExtension_Invalid                    : aac aacp adts

Audio
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format version                           : Version 4
Format profile                           : LC
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 49.8 MiB (100%)

**Mediainfo of the working extracted swedish srt**
_Complete name                            : subs.srt
Format                                   : SubRip
File size                                : 31.4 KiB

Text
Format                                   : SubRip
Compression mode                         : Lossless_

**Comment by karsta62** [comment]
An update: 
I downloaded with "--preferformat mp4". Now VLC was satisfied. It shows 2-3 subtitle tracks, but all labelled as "English". Anyway, one of them is finnish and it can display it. As well my set top box displays finnish subs directly.
I didn't know that mp4 can contain subtitles, but figured out that they can be also extracted:
_MP4Box -srt 1 some.mp4_
assuming that track 1 is what is wanted. Can be verified by:
_MP4Box -info some.mp4_

I can live with this, but could be a bit easier like managed by parameters.

**Comment by aajanki** [comment]
Subtitles not being displayed in VLC might be because an old libavcodec (or some other related library). Subtitles work for me on libavcodec 7:4.1.3-1 and VLC 3.0.6-0-g5803e85f73.

You can run subtitle extraction automatically after a download by writing a script and using the `--postprocess` argument. See `scripts/muxmp4` for an example postprocessing script.

I'm closing this issue as it seem that the changing the format to srt helped.
