### ISSUE TITLE
Neither the proxy nor the subtitle works for me

### ISSUE THREAD

**Issue by NiesmialyGosc** [aajanki/yle-dl#203]
No one is experiencing the same issue?

D:\videotest>yle-dl --proxy http://95.216.155.228:3128 --sublang all https://areena.yle.fi/1-4586709
yle-dl 20190502: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2019 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

ERROR: Unsupported stream: Media not found

Any help will be appreciated.

Thank you
Jacob

**Comment by aajanki** [comment]
There has been improvements both to the proxy and subtitle support in the latest versions. Can you test again on the yle-dl version 20210808?

**Comment by aajanki** [comment]
I'm closing this old issue, because both proxy and subtitles support have changed since this was opened. There are still some known issues with subtitles, but those are being tracked on other open tickets.

If you still encounter problems, please reopen this or create a new bug report.
