### ISSUE TITLE
AKAMAI hdtns/hdnea cookie exp expiration + wget

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#204]
While I remember, I brought this up earlier but the answer was a "misunderstanding" then.

The problem, when wget runs into an expiring akamai timestamp, is that YLE-DL falls back to ffmpeg which zeroes the file and starts from zero.

Instead YLE-DL shld , at least a couple of ti,mes (before going for ffmpeg)
- get the a new hdnts cookie
- restart wget with that new cookie, which has a new exp expiration time.
 and wget will resume .

Background:
quite messy, because some yle streams have, some dont, some hdnts, some hdnea.
typ hdnts has 
hdnts=...st%3D1560880802~exp%3D1560888002..
where 1560880802 is EPOCH UNIX time, use webpage
https://www.epochconverter.com/
st=start, exp=expire (seconds after 1970-01-01 zero time)

Seems akamai server 
- knows something abt lenght of program
- adds an hour?? 
- rounds up to even hour??

This is great for slow downloading of small files but not enough when 3-5GB and downlaoding at half or less speed (multple downloads  or "in background") 

ANother "issue" wld be give wget parameters

more retries (10-15)
much more wait inbetween retries (increasing 60-600 or more sec, ADSL etc reconnect time)
look thrgh the wget-error code from the server or connection
(the present yle-dl-wget setting "quits in a fraction of seconds, no retry" if cant resolve IP adress or similar)

PS When doing these changes my python problem was that the actual yle-dl sys-exec of all downloaders happen with the same line python code?
One needs to know which dnldr the code tries, etc to decode error codes, what to do, etc
(and the user might have spacified paths and dnldrs with "strange" names, I am using a handful of wget and ffmpeg versions, wget18,20,21 etc)

**Comment by gunnar12** [comment]
Btw, my "best problem enviroment" is
- in and out of network and windows "multiple fall back gateways"
- virtualBox seems to "get things wrong" abt "Master Browser", resets connection and worse
- 3-4GSM internet cinnection

ffmpeg is the worst I have seen in "mess up stream if any problems" althgh it works with numbered (video) fragments, wld be easy to just reload the fragment that went wrong (seems it uses code for reading a hard disk file)
wget does the 5 retries but too few and too fast

Funny, the "standard Windows workhorse downloader" IDM is coded to "handle all of this" (except some extreme server cases)
I salute their coders!! (and error-handling, always 90% of coding)
thats why it costs $25 and is updated all the time?

**Comment by aajanki** [comment]
I think that this is the same old issue that yle-dl should fetch a fresh URL from Areena before retrying. Fixing this is a bit tricky because it requries lots of refactoring in the code.

Duplicate of #157
