### ISSUE TITLE
Subtitles file downloaded only partially

### ISSUE THREAD

**Issue by tlikonen** [aajanki/yle-dl#205]
Yle-dl (2.34-169-g82041a8) downloads (some?) subtitles only partially. For example

    yle-dl https://areena.yle.fi/1-2312324

produces an mkv file which has only about nine minutes of subtitles. I confirmed this by extracting the subtitle track from mkv file:

    ffmpeg -i film.mkv -map 0:s:0 -c copy subtitles.srt

**Comment by aajanki** [comment]
Please update to the latest yle-dl version 20190614 and ffmpeg 4.1 or later and try again.

**Comment by tlikonen** [comment]
Antti Ajanki [2019-06-23 10:55:50-07:00] wrote:

> Please update to the latest yle-dl version 20190614 and ffmpeg 4.1 or
> later and try again.

Thank you. I compiled ffmpeg from the source code repository and with
that version yle-dl indeed works. I guess the problem was about some
subtitle format conversion feature which my too old ffmpeg lacked.
