### ISSUE TITLE
?  and "DASH" in program title

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#207]
?  and "DASH" in program title. WHile I remember

Found them in some now old programs where the title started with a question.
Linux didnt like it, or then it was Windows, hehe. or both?

Not absolutly sure anymore, but I think there was a "dash" too there, ie. not the usual "minus" like in +/- ? (the real pest bc one doesnt see the difference)

maybe even some hidden CR or just LF?? which can happen if filling out the YLE  title=form with a smart phone??

Gunnar

PS New record by YLE, 5 day old Aamu-TV not yet coded and cut properly for Areena use.
Areena and browser even says "will be available" and the 5 day old date and time.
(sw checked it wasnt in the 24 hour buffer anymore)

PPS Technology improves. SVT-FST are now streaming, not just FIFA-Ball, but also boobie-balls in 50 frames/s (All-song live)
Faster moving icehocley puck and smaller female balls still need 100 frames/s to stay sharp.
Dxmn, the not-archived live stream also used the AKAMAI hdntl cookies with expiration time.
But one can still copy frpm the very start with ffmpeg using

-live_start_index 0

even if one begins in the middle. Fragments are only 4seconds short!.
Note, for some streams " -live_start_index 100" means

start from segment 100
start 100 segmnts back from "now"

gets funnier with " -live_start_index -100"

**Comment by aajanki** [comment]
That's right, the question mark is not supported on Windows filenames. Call yle-dl with the `--vfat` option to generate filenames without question mark or other charaters that are not supported on Windows.

I realize that dash might sometimes be a bit inconvenient, but I think the tab completion and copy pasting should take care of it. Besides, it is supported both by Windows and Linux. I'd like to keep the names resonably close to the original ones, so I'll leave the dashes unchanged.

CR and LF are already replaced by witespace.
