### ISSUE TITLE
Feature request: aria2c for backend

### ISSUE THREAD

**Issue by ersi-dnd** [aajanki/yle-dl#208]
Hi. How about aria2c as yet another thing to put in --backend? I have tried appending it with --wget and --backend and unfortunately it does not work by accidental luck.

**Comment by aajanki** [comment]
I can see that this might be an useful feature, but I also think this is a pretty low priority issue and most likely won't have time to implement this anytime soon.

If somebody wants to contribute a patch, I'm happy to accept one.

**Comment by ersi-dnd** [comment]
`youtube-dl` has the ability to download with `aria2c`. Maybe the code can be ported from there. Sorry I am no coder.

**Comment by aajanki** [comment]
I'm closing this issue, because I really don't have time to add new downloaders and besides it wouldn't be possible to download subtitles anyway with aria2c.
