### ISSUE TITLE
Removing the watermark from the videos

### ISSUE THREAD

**Issue by vkk800** [aajanki/yle-dl#211]
All the videos downloaded from Areena come with the Yle watermark. For the purists among us, it would be neat to be able to remove it. The watermark is transparent so it is possible that the original picture could be fully recovered without any artifacts. This would probably require the following steps:

* Reverse engineer the filter that was used to create the watermark
* Create an inverse of this filter
* Apply the created filter using ffmpeg or something similar

Since yle-dl already supports ffmpeg backend, the last step would be easy, provided that the correct filter is found.

I've done some preliminary research on the problem and it looks like the watermark is only applied in the luma channel in the YUV decomposition of the image.

Is anyone else interested in adding this feature? Any ideas on how to best reverse engineer the watermark?

**Comment by aajanki** [comment]
I like the idea but don't know how to reverse engineer the watermark filter.

**Comment by fbjon** [comment]
Here's a capture of the watermark, averaged from the y-channel of a few thousand frames with black background: https://pasteboard.co/IM7Hb4c.png. The image is cropped to include the necessary padding in the upper-left corner.

I couldn't quite find the perfect settings to remove it: blending with exclude or subtract is a very good start, but it seems to also depend on the underlying image brightness somewhat. And also, there's compression artifacts which this won't help with.

**Comment by vkk800** [comment]
I also did some research on this some time ago but forgot to post the results. Here's what I found out:

* The watermark is only applied in the luma channel
* It looks like the filter is slightly different for different videos (maybe they have changed it over time?). It clearly looks brighter on some videos.
* The watermark is not applied using any of the standard image filters that I know of (add/multiply/burn/etc.)
* The watermarking operation is not a 1-to-1 mapping, which means that it's not exactly invertible. I analyzed one video by taking luma values around the watermark, comparing them to one pixel towards the watermark and taking the median of all the data to find some kind of approximation to the mapping curve used in the watermarking operation. Here's the result: [https://postimg.cc/nC9yhppz](https://postimg.cc/nC9yhppz) . x-axis is the original luma value of a pixel and y-axis is the luma value after the watermarking operation. Blue curve is the data after median filtering it and the orange curve some kind of approximation that I made up.

I also found out that for videos with certain aspect ratios (whatever the widest standard one is), the watermark is completely in the black border of the image, which means that it could easily be removed by just cropping the image or blocking it with just black colour without any loss in actual information.

If someone wants to work on this (I don't think I have the time), my suggestions are:

* First implement the removal for wide aspect ratio videos for which the operation is trivial. This is already good progress.
* Do analysis similar to what I did to find the exact mapping used to apply the watermark and implement at least some kind of an approximation for the inverse operation. I don't know what tools should be used to actually process the videos. Does ffdshow support custom filters?
* The hardest part is to invert the dark part of the mapping curve since it's not an invertible function. However, a good enough approximation could probably be found by looking at the pixels surrounding the logo and using some heuristic to determine which branch of the mapping curve should be used for the inversion.

**Comment by aajanki** [comment]
I'm closing this old issue. I don't have time or motivation to implement this.

**Comment by Alias21x** [comment]
Hey, i don't know if I'm late to this and/or if this is even helpful but i was wondering why since i have backed up some yle content to plex and when changing settings and everything goes black for a second, the only thing remaining from the image is the YLE watermark, as if it is a seperate part of the inage? I don't know if they changed anything in the last couple years or so?
