### ISSUE TITLE
Easy macOS installation 10.14.6

### ISSUE THREAD

**Issue by erikschmidt3001** [aajanki/yle-dl#213]
This is not really an issue, but when I just installed yle-dl on a recently setup Mac running macOS 10.14.6 (Mojave) I just needed these three steps to get it running:

Install homebrew
brew install youtube-dl yle-dl
brew install wget

Could/Should the installation instructions be adjusted?

**Comment by aajanki** [comment]
Thanks! I updated the installation instructions
