### ISSUE TITLE
Embedded subtitles completely fail to load?

### ISSUE THREAD

**Issue by ExTechOp** [aajanki/yle-dl#218]
When downloading a stream like https://areena.yle.fi/1-4303984 the --showmetadata option tells there are fin/swe embedded subtitles available. However, once you have downloaded the file, Kodi or vlc can't find subtitles in it, and when I look at the file with ffmpeg, there don't seem to be embedded subtitle streams:

```
% ffmpeg -i The_Ganges_with_Sue_Perkins-S01E01.mp4 
ffmpeg version N-92549-g3317155 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8 (GCC)
  configuration: --prefix=/home/otto/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/otto/ffmpeg_build/include --extra-ldflags=-L/home/otto/ffmpeg_build/lib --extra-libs=-lpthread --extra-libs=-lm --bindir=/home/otto/bin --enable-gpl --enable-libfdk_aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree --enable-libzvbi
  libavutil      56. 24.101 / 56. 24.101
  libavcodec     58. 40.100 / 58. 40.100
  libavformat    58. 23.100 / 58. 23.100
  libavdevice    58.  6.100 / 58.  6.100
  libavfilter     7. 46.101 /  7. 46.101
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'The_Ganges_with_Sue_Perkins-S01E01.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
  Duration: 00:51:49.50, start: 0.000000, bitrate: 4055 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 3922 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
```

Would it also be possible to re-implement the --subtitles option so that one could get the separate subtitle files afterwards?

**Comment by aajanki** [comment]
Can you send the debugging output genereted by `yle-dl --verbose  https://areena.yle.fi/1-4303984` so I can see if it contains any clues why subtitles are not being downloaded? The debug log will be long. You can use pastebin.com or similar service to share it.

**Comment by ExTechOp** [comment]
The main part of the log was of course the download record, which doesn't really convey that much information. I abbreviated that, and the result is 39441 bytes: [debug.log](https://github.com/aajanki/yle-dl/files/3741138/debug.log)

**Comment by aajanki** [comment]
Your ffmpeg does not include support for https(!). From the log: `https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.`

Yle-dl falls back on a secondary source which can be downloaded without ffmpeg but which doesn't include subtitles.

Subtitles should start working if you install a fully functional version of ffmpeg.

**Comment by ExTechOp** [comment]
Oops. Well, that was a somewhat unexpected cause, I'd left a self-compiled experimental ffmpeg in the path. Sorry for the bother.
