### ISSUE TITLE
Any windows and Linux help, wrong code is run

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#220]
Any windows and Linux help, wrong code is run, usually some old version.

It seems Python every now and then messes up what "egg-code" it should run.

Instead of picking what I compiled 2 seconds ago it starts some old yle-dl compiled code.

At the moment my windows versions got stuck like this.

the actual code python starts is version 2.36 from somewhere..

ANy explanation on how Pyhthon does, handles, etc "these things" on some link somewhere.
Both Linux and Windows.

Any systematic way to track down the problem when this happens??
yle-dl-script??   cfg??  all the shxt in that windows python dir-tree?
(which saves evry compilation version I ever did??)

Same for Linux?? (additionally the normal user and root difference)

PS on linux theres this, actually tons of them, easy-install??path file?
Usually needs clean up, many yle-dl entries, always pick first, but the new compilation goes last?

But there many of these file, hoe to track down which one is used, as root and as normal user?

**Comment by gunnar12** [comment]
same easy-install-mess.pth in WIndows

C:\Users\xxxxxxr\AppData\Roaming\Python\Python37\site-packages\easy-install.pth

 WHO PUT THE 236 version at the top!! SUDDENLY!!

./yle_dl236-2.36-py3.7.egg
./yle_dl_1025-20191022-py3.7.egg
./yle_dl-20190614-py3.7.egg
./yle_dl2331-2.3313-py3.7.egg
./yle_dl3015-2.305g1w-py3.7.egg
./yle_dl23015-2.305g1w-py3.7.egg

**Comment by aajanki** [comment]
If you want to switch between several versions of yle-dl, I recommend using [virtual environments](https://docs.python.org/3/tutorial/venv.html). A virtual environment is a self-contained directory where you can install one version of yle-dl with its dependencies. You can control which version of yle-dl is being used by activating one of the virtual environments.
