### ISSUE TITLE
YLE changed title stuff in MetaData again!!

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#221]
YLE changed title stuff in MetaData again!!

means yle-dl cant find out the same file is already downloaded (old videos) or the configures title-conf produces weird stuff (empty becomes areena)

This is why I needed to make some print-debuglines added and got stuck with version 2.36..

Has anyone already mapped and documented?

- what YLE is doing, titles and dates, in its metadata
- what yle-dl picks accordng to template in the conf file?

it seems an empty field from the metadata is changed to "areena" by yle-dl?

Seems to have happened mainly to YLE-Ammu-TV, uutiset and some new and old swedishseries (rantahotelli- just became areena- )

PS only solution is clearly to include the program ID code (yes/no using conf.txt) in the output file-name?
Looks bad but only possibility?

PPS A whole new functional block, module or whatever its called.
- Gets all the stuff used from the MetaData
- uses ArtificialIntelligence adaptive table-look-up and "file.exists", size, duration,etc to figure out if the video already downloaded! (or just the program ID if included in file-name, hehe)

**Comment by aajanki** [comment]
Can you give an example of an URL where the title becomes areena? All Rantahotelli episodes that I tested seem to work correctly.

**Comment by gunnar12** [comment]
title becomes areena? /

Was YLE temporary problem.

Yle-Ammu TV was "correct" again today.
My list of "last chance" went thrgh without any progrzm becoming "areena-".
(my yle-dl tests if alrdy exists and skips if it does, had to look for areena-named and Aamu-TV was the largest 5GByte, waste of time)

Both the Yle-Ammu that was one month old and the one of today were "normal" again.

PS YLE has had some problems with the "last chance" webpage and even "the burst" of new videos they give at 24.00 and 06.00

**Comment by aajanki** [comment]
The title alone is not reliable for detecting duplicates as you have noticed. With the latest version on Github you can include the program ID (which hopefully is more reliable) in the file name: `yle-dl --output-template '${program_id}' --resume https://areena.yle.fi/1-50356660`.

It's possible to have both the ID and the full title in the file name: `--output-template '${program_id}${series}${title}${episode}${timestamp}'` but in that case you need to write your own script that first does `yle-dl --showmetadata` to get the ID and then checks if there already exists a file that starts with that ID.
