### ISSUE TITLE
Subtiles partially missing

### ISSUE THREAD

**Issue by samuana** [aajanki/yle-dl#223]
Download goes fine, but subtitles are saved only partially. When viewing video, both finnish and swedish subtitles are ok for a first 5 minutes, but rest of the movie subtitles are missing.

yle-dl https://areena.yle.fi/1-4196183
yle-dl 20190203: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2019 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

Output file: Your Name-2019-11-27T06:00.mp4
frame=153288 fps=144 q=-1.0 Lsize= 2939089kB time=01:42:11.55 bitrate=3926.7kbits/s speed=5.76x    
Stream saved to Your Name-2019-11-27T06:00.mp4

Players (VLC, kodi, SMPlayer) stops to show subtitles at 5 minutes. I extracted subtitles with MP4box to verify that only first 5 minutes are present.

All subtitles are ok when viewing this movie in areena.

Another minor thing: both subtitle languages (finnish, swedish) are marked as "English" in streams metadata.

**Comment by aajanki** [comment]
Try upgrading your ffmpeg to version 4.1 or later. Then you should get the subtitles for the whole duration of the movie.

The second issue with the incorrect subtitle language labels should go away if you upgrade yle-dl to the latest version, which is 20191022.

**Comment by samuana** [comment]
I'm on Debian 9 with repository version 3.2.14 of ffmpeg. Even latest lts ubuntu 18.04 have 3.4.6.
Tried to install newer, but there are lots of package dependencies and could not find good repository to fill them all.

Instelled new ffmpeg (4.2.1) and yle-dl (20191022) to older win7 machine and downloded movie again and now text are ok.

So I can confirm that suggested newer versions fix this problem.

Labels for languages are still mess: fi name is "{gg" and sv is "{gm".

**Comment by aajanki** [comment]
Good to hear that subtitles work with the updated ffmpeg. I'm closing this issue.

I don't know what's wrong with the labels. On Linux the labels are shown correctly as fi and sv.
