### ISSUE TITLE
Stream title language not based on URL

### ISSUE THREAD

**Issue by fbjon** [aajanki/yle-dl#225]
When downloading media from Areena, the stream metadata (title etc.) is always in Finnish even if the URL is for the swedish site. E.g. using [arenan.yle.fi/1-3094265](https://arenan.yle.fi/1-3094265) vs [areena.yle.fi/1-3094265](https://areena.yle.fi/1-3094265) gives a file with the same name.

Is there a way to set the metadata language, as with `--audiolang`?

**Comment by aajanki** [comment]
There is currently no way to change the metadata language. It would be a nice feature but I'm not sure when I have time to implement it.

**Comment by dhofverberg** [comment]
I would also very much like to be able to get Swedish titles and episode titles in the file names, when using URLs from the Swedish language Arenan site.

Quite annoying with Finnish episode titles, when you don't actually speak Finnish...

**Comment by aajanki** [comment]
yle-dl now uses the Swedish title in the file name on Swedish site URLs.

Furthermore, you can force yle-dl to use Swedish titles whenever they are available even on other URLs with the new option `--metadatalang swe`.
