### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by vazhnov** [aajanki/yle-dl#228]
Hello!

My wife and I visited "Ajankohtaista Oopperassa & Baletissa" (Finnish National Opera and Ballet) in December 2019, watched "Peppi Pitkätossu" (Pippi Longstocking). Now video recording available [on site](https://oopperabaletti.fi/en/stage24/pippi-longstocking-recording/) and I downloaded it easily:

```bash
yle-dl https://areena.yle.fi/1-50349584
```

Thank you for such simple in use product!

**Comment by aajanki** [comment]
Glad to hear that you have found the application useful!
