### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by jainkila** [aajanki/yle-dl#229]
Yle-dl downloads from yle areena just fine and saves the tv-program into mkv-file.

Issue: Subtitles works for the five first minutes from the start and then sub's disappear. Confirmed with vlc-player and Celluloid.

Yle-dl version 20191231. Linux Mint 19.3.

**Comment by aajanki** [comment]
This is a known problem with older ffmpeg versions. Updating ffmpeg to the version 4.1 or later will fix it.

**Comment by jainkila** [comment]
Works with ffmpeg version 4.1.4. Thanks for your time and effort!
