### ISSUE TITLE
Saami titles crash

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#232]
Saami titles crash

theres some something-code that ensures pure ascii from anu kind of unicode weird stuff??
good to add where needed.

**Comment by aajanki** [comment]
Can you give a sample URL? It would make it easier to debug

**Comment by gunnar12** [comment]
https://areena.yle.fi/1-50409368

**Comment by aajanki** [comment]
Thanks! Fixed in the latest commit.
