### ISSUE TITLE
How to select bitrate for specified resolution?

### ISSUE THREAD

**Issue by spvkgn** [aajanki/yle-dl#235]
Hello,
i can't download 720p stream in high bitrate - yle-dl always downloads it in low bitrate (~1500). Download wIth `--maxbitrate best` or `--maxbitrate 2575` has no effect. Is there an option to download with high bitrate for specified resolution?
```
$ yle-dl --showmetadata https://areena.yle.fi/1-1386571
…
{
        "media_type": "video",
        "height": 720,
        "width": 1280,
        "bitrate": 1436,
        "backends": [
          "ffmpeg",
          "wget"
        ]
      },
      {
        "media_type": "video",
        "height": 720,
        "width": 1280,
        "bitrate": 2575,
        "backends": [
          "ffmpeg",
          "wget"
        ]
      },
```

**Comment by aajanki** [comment]
This works for me: `yle-dl --resolution 720 --maxbitrate 2575 https://areena.yle.fi/1-1386571`

Can you give me your exact yle-dl command line parameters? Which version of yle-dl do you have?

**Comment by spvkgn** [comment]
Thanks, `--maxbitrate 2575` works as it should, I jumped to conclusion here. But `--resolution 720 --maxbitrate best` downloads in low ~1500 bit-rate and it confused me a bit. I guess that `maxbitrate best` should get highest bit-rate for resolution.
yle-dl 20200222

**Comment by aajanki** [comment]
I noticed and fixed the issue with `--maxbitrate best` yesterday after answering to you. The fix in already in the master branch. Thanks for reporting the issue.
