### ISSUE TITLE
new/old AUDIO web-page

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#238]
new/old AUDIO web-page.

Seems YLE has killed the oldold RADIO web page, for a week or two only the new silly AUDIO page now! (they admitted they had "tested" the crxp on certain users earlier)

Has anyone

- managed to get the program IDs ( ylexxx/1-nnn ) from the uudet/viela-ehdit new pages?
It was my major technique to drag-drop the yle-URL to a text file for yle-dl

- some "open in new window" from the program-icons (firefox), one cld get the ID, one-by-one?
single programs still use that 1-nnnnn URL, SILLY YLE!

- is this a matter of what device one uses, win-linux firef,chrome/opera, android,etc?? different web-pages produced?

- any other trick, tool to get-them?? Even "all of them" into one text file 
I cld add an yle-dl function to either pick or exclude what I want/dont-want.

SILLY YLE!! leaving out the DRAG-DROP line of the code!

PS one more, when downloading a whole series, it wld be nice with at least a counter for "how many found".
Now yle-dl, without verbose, just shows black screen for an hour (paiva tunnissa, haatanen,etc)

DBL-SILLY YLE, cant find a way to click-click to uudet/viela-ehdit except by writing (the secret) link myself
https://areena.yle.fi/audio/ohjelmat/30-490

**Comment by lsolin** [comment]
You can get the old-style urls thru the Areena search box or the Yle search page.

[](https://haku.yle.fi/?language=fi&page=1&query=kalle%20haatanen&type=areena&uiLanguage=fi)

**Comment by gunnar12** [comment]
search box / thanks!

Maybe there is hop? very early this morning viela-ehdit Drag-Drop was there!
BUT, almost all program-icons were behind a "viewable in EU" text/
BUTBUT now it is back to the non-drag version again.

At least someone somewhere is trying to add DragDrop to the page system??

**Comment by gunnar12** [comment]
OK, Drag-Drop included again, and program icons are normal.

https://areena.yle.fi/audio/ohjelmat/30-490

**Comment by aajanki** [comment]
It seems Areena has been updated and the web browser now shows a URL for a single episode when you open the episode pop-up.
