### ISSUE TITLE
Still no wget-mp4 sublanguage downloads?

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#242]
Still no wget-mp4 sublanguage downloads?

or do I have something else wrong?

Shouldnt they get downloaded even with no yle-dl parameters-arguments (except prefer mp4?)

**Comment by gunnar12** [comment]
btw, found the max limit for api, but just need to wait
https://developer.yle.fi/tutorial-overview/index.html
------
Rate limiting

The API is rate limited. You can expect to be able to do 10 requests/second, 300 requests/hour and 7200 requests/day to the API. If you exceed your quota, HTTP 401 Unauthorized response will be returned.

In this case, you should wait for a while before trying to make a new request.

**Comment by aajanki** [comment]
Can you give an example of a command line that is producing downloads without subtitles?

This should give mp4 with subtitles:
```
 yle-dl --preferformat=mp4 https://areena.yle.fi/1-50495163
```

This will not give subtitles (and is not even supposed to do so because wget doesn't undestand subtitles):
```
yle-dl --preferformat=mp4 --backend=wget https://areena.yle.fi/1-50495163
```

**Comment by aajanki** [comment]
I added a warning message about missing subtitles when downloading with wget.
