### ISSUE TITLE
youtube-dl / mpv integration

### ISSUE THREAD

**Issue by tpikonen** [aajanki/yle-dl#246]
I just noticed the "Remove remaining references to [...] youtube-dl" commit, which got me thinking about integration with youtube-dl. Is there any chance of having an yle-dl plugin for youtube-dl?

I usually play videos with mpv, which can use youtube-dl transparently with seeks etc. working. Piping streams from yle-dl to mpv works of course, but does not show the size of the program or support forwards seeks.

**Comment by aajanki** [comment]
Over the years there has been a few attempts (by others, not by me) to get youtube-dl to support Areena, but they have not been merged. Possibly because the youtube-dl maintainers seem to be overwhelmed. The repo currenty has more than 600 open pull requests! So I wouldn't hold my breath waiting it to happen. :(

**Comment by tpikonen** [comment]
Thanks for the info. There is indeed an open pull request for YleAreena extractor for youtube-dl, but it does not seem to work with all streams. The Kaltura extractor of youtube-dl works on URLs output by yle-dl though.

So for people following along, this trivial wrapper script plays Areena URLs in mpv+youtube-dl with seeks and stream lengths working:

```
#!/bin/sh

mpv $(yle-dl --showurl "$1")
```

**Comment by pekkarr** [comment]
I made a simple mpv plugin [mpv-yledl](https://github.com/pekkarr/mpv-yledl) to integrate yle-dl into mpv. With it you can just pass Areena web page URL to mpv.

Advantages of mpv-yledl over `mpv $(yle-dl --showurl "$1")`:
- works similarly to youtube URLs
- shows video title correctly
- adds subtitles

Advantages over piping to mpv:
- you can seek anywhere in the video
- stream length is shown

**Comment by tpikonen** [comment]
I also have a (rejected) [PR](https://github.com/ytdl-org/youtube-dl/pull/26147) for areena support with yle-dl in youtube-dl, but unfortunately I forgot to mention about it here.

The code can be found [here](https://github.com/tpikonen/youtube-dl/commits/yle-dl). I rebase it occasionally against youtube-dl master.
