### ISSUE TITLE
ffmpeg updated not work

### ISSUE THREAD

**Issue by ukko6** [aajanki/yle-dl#249]
yle-dl 20200807

ffmpeg 4.3.1

[hls @ 0x55f2104c8a40] Could not find codec parameters for stream 1 (Video: h264 ([27][0][0][0] / 0x001B), none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska @ 0x55f2117ebd00] dimensions not set
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

-->wget -->no subtitles

**Comment by aajanki** [comment]
Does this happen on every video or on just some videos?

**Comment by ukko6** [comment]
> Does this happen on every video or on just some videos?

Every 20 what i test. With older (ffmpeg 4.1) libav* -libraries yle-dl works, but when update new ffmpeg it needs new libraries. Now i have mixed ffmpeg 4.3.1 and collection miscellaneous libraries, but it is very difficult choice and needs big reporoulette, but it works. Distro is OpenSuse (Leap/Tubleweed) and i think at the problen is some new feature in ffmpeg.  Debian i perhaps try next week, but there ffmpeg is yet 3.xx ffmpeg. Why 4.xx ffmpeg, quite buggy yet and 4.1 is big security risk.

**Comment by aajanki** [comment]
I'm not able to reproduce this with ffmpeg 4.3.1 on Debian unstable. Everything works as expected.

Not quite sure what might be the problem here. I'll have to install OpenSuse on a VM and see if I can figure it out.

**Comment by aajanki** [comment]
OpenSuse official ffmpeg packages do not contain support for non-free codecs like h264 used on Areena. You can install ffmpeg with the necessary non-free codecs from the unofficial packman repository, see https://opensuse-guide.org/codecs.php

This is what I had to do:
```
sudo zypper addrepo -f http://packman.inode.at/suse/openSUSE_Tumbleweed/ packman
sudo zypper install --allow-vendor-change ffmpeg-4
sudo zypper dup --allow-vendor-change --from http://packman.inode.at/suse/openSUSE_Tumbleweed/
```

**Comment by ukko6** [comment]
Yes, with Tumbleweed i can doo it. But Leap 15.2 do not support ffmpeg 4.xx, neither with packman repo. That problem becomes then found security bugs 4.1 and 4.2 ffmpeg versions. I thank you your time, the broblem is out of our hands ;-}
