### ISSUE TITLE
shlex.join not available in python versions <3.8

### ISSUE THREAD

**Issue by juippis** [aajanki/yle-dl#253]
Hey, 

1f14b77775324d3b0fb953e4e26a90bd8f608498 introduced `shlex.join(args)` on *backend.py* and I just want to point out that this functionality was added in python-3.8, 
https://docs.python.org/3.7/library/shlex.html
https://docs.python.org/3.8/library/shlex.html

I tried going through distributions that still use <3.8 as their basic interpreter, and looks like at least openSUSE and some versions of Debian (and such some variants) still do, so this updated yle-dl won't work on those distributions. 

I tried reverting this commit and ran yle-dl with both python-3.7 and python-3.8 and it seems to work. (You can also just update the required dependency list to have python-3.8+...)
This issue was originally reported in https://bugs.gentoo.org/750536

**Comment by aajanki** [comment]
Thanks for reporting! That was unintentional. I fixed it and released a new version 20201022.
