### ISSUE TITLE
ImportError: libffi.so.7: cannot open shared object file

### ISSUE THREAD

**Issue by Haprog** [aajanki/yle-dl#256]
I started getting this failure on Linux recently (after upgrading my distro Pop!_OS from version 20.04 to 20.10):
```
Traceback (most recent call last):
  File "/home/haprog/.local/bin/yle-dl", line 5, in <module>
    from yledl.yledl import main
  File "/home/haprog/.local/lib/python3.8/site-packages/yledl/__init__.py", line 2, in <module>
    from .backends import Backends
  File "/home/haprog/.local/lib/python3.8/site-packages/yledl/backends.py", line 4, in <module>
    import ctypes
  File "/home/haprog/.pyenv/versions/3.8.5/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory
```

I'm not sure if it is because of the distro uprgade, but I think it's probable.

I tried updating with `pip3 install --user --upgrade yle-dl` but it didn't help. No errors on that command though.

I'm running Python 3.8.5, wget (GNU Wget) 1.20.3, ffmpeg n4.1.4 (`built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)`)

Is there some dependency I'm missing?

If I do a file search for `libffi.so.*` on my system I find:
```
/usr/lib/x86_64-linux-gnu/libffi.so.8.1.0
/usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
/usr/lib/i386-linux-gnu/libffi.so.8.1.0
```

My TimeShift backup from before the dist upgrade seems to contain:
```
/usr/lib/x86_64-linux-gnu/libffi.so.8.1.0
/usr/lib/x86_64-linux-gnu/libffi.so.7.1.0
/usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
/usr/lib/i386-linux-gnu/libffi.so.8.1.0
/usr/lib/i386-linux-gnu/libffi.so.7.1.0
```

I wonder why these libffi.so.7.1.0 aren't there anymore or if I need to install some extra package to get these back properly? Or should yle-dl be able to use libffi.so.8.1.0 instead?

**Comment by Haprog** [comment]
Actually this seems to be a more generic Python related issue on Ubuntu based distros when upgrading to 20.10. I was able to fix it by installing libffi7 with this deb https://mirrors.edge.kernel.org/ubuntu/pool/main/libf/libffi/libffi7_3.3-4_amd64.deb

I found the solution here: https://askubuntu.com/a/1290347/134155

Feel free to close this issue, but I think other's may have the same issue and it might be useful to keep this open/visible for a while.

**Comment by aajanki** [comment]
Python depends on libffi. It is a bug in the distro's package dependencies if installing Python doesn't pull a compatible version of libffi, and it should be reported to the distro's bug reporting system.
