### ISSUE TITLE
${episode} does not work in output template

### ISSUE THREAD

**Issue by pallost** [aajanki/yle-dl#257]
`yle-dl --resume --output-template '${series} ${episode} ${title}' --maxbitrate best https://areena.yle.fi/1-2213829` only prints show title and episode title, but not `"S**E**"`

Version 20201022

Thanks for development! Do you have a Patreon?

**Comment by aajanki** [comment]
It seems that the Areena API response doesn't include the episode numbers for the Ryhmä Hau episodes and that is why ${episode} is empty. Somebody at Yle would need to enter the correct episode numbers in the program metadata.

I tested with some other programs and ${episode} does produce a correct S*E* entry if a program has proper metadata at Areena.

**Comment by pallost** [comment]
Ah, that sucks... Well, I'll need to dig the episode numbers up then manually from imdb probably. Thanks anyway!
