### ISSUE TITLE
Zero-length downloads

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#258]
Checked for old zero-downloads, found this one

https://areena.yle.fi/1-50696797
https://areena.yle.fi/1-50697288  too.

download OK with IDM, didnt check and change analyze probe length.

PS merging code is a pain, would be nice with

- checkdir list, cfg file og paths where yledl checks if outputfile already exists.
- lastdir, a sub-path "./lastdir" where existing and downloaded file is moved
(run with arg --lastdir when doing a viela-ehdit list)

only way(s) to avoide dbl-downloads (when one directory not enough, or sorting, moving etc myself)

sub-path because linux can move a "live" file within the same partition, path and name are "tag"
(note, scheckdir shld check any ./lastdir too)

Windows more tricky, using shutil gor windows and has to
- check if move-to file already exists
- -compare dates to not move a file that another yle-dl writes to
-- if "today", check size. wait 3-10 seconds and check size again , if still same, do the move.
(might be possible to detect by trying to open for writing if the other yle-dl has opened excluding it. Not so at the moments, both can happily overwrite and destroy the outputfile together)

try and then reporting and error reporting on all, hehe!

PS using windows cmd and its own move is easier but "non-python"

**Comment by aajanki** [comment]
hmm, I'm able to download both. Does yle-dl output any errors when you try downloading?

I see some warnings like these:
```
[hls @ 0x559a23265080] Could not find codec parameters for stream 15 (Video: h264 ([27][0][0][0] / 0x001B), none): unspecified size                                                                                         
Consider increasing the value for the 'analyzeduration' and 'probesize' options
```
and even
```
[tls @ 0x562dd072aa40] Error in the pull function.
```
but it seems that the full video gets downloaded despite these.

**Comment by aajanki** [comment]
Are you using the ffmpeg or the wget backend? Both programs seem to be only available in format supported by ffmpeg.

**Comment by gunnar12** [comment]
Busy, lost a system-HD..

inbetween tested on almost virgin ubuntu 18, better but similar problems with the 2 links
UBU 18 sets up with ffmpeg 3.x.. not 4.
updated v.4.3 and worked OK. 
for windows additional mix ffprobe and ffmpeg..

Might be good for yle-dl to check versions of both before using them.

**Comment by aajanki** [comment]
yle-dl now prints a warning if ffmpeg version is older 4.1.0.
