### ISSUE TITLE
Minor, full series includes future prgrms becomes zero files

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#259]
for example this one, 2 weeks to publish

Jazzklubi_ Antti Lötjönen Quintet East Tampere Jazz Happeningissä-2021-01-10T19_00

More important would be to get some default screeninfo when downloading a series
- name before building the list starts (might take haatanen-minutes)
- some counter on how many (ok in debug mode)
- the used areena-link whenthe  downloads starts (copy paste when somthing goes wrong)
- 
- best?, first output the found URLs to a text list for later use (when things go wrong)
- do the downloads in the same bunches of 100 as the URLS are "searched"
- do only the first (latest) 100?? with arg
- 
best example "haatanen", probably most archived programs on YLE?

**Comment by aajanki** [comment]
Thanks for the bug report! I have now fixed it on the master branch. The upcoming episodes do not anymore generate zero-length files.

Your other wishes are all good ideas but i don't have time to implement them, sorry. However, you can do it yourself: First run `yle-dl --showmetadata ...` on a series page to get all titles, URLs and counts. Then download each episode one-at-a-time printing the title and URL and everything else in exactly the format you want.
