### ISSUE TITLE
Debian - ffmpg - Thread message queue blocking;

### ISSUE THREAD

**Issue by 6b6561** [aajanki/yle-dl#262]
I'm getting the following messages from ffmpg on Debain:
`[hls @ 0x6d74a00] Thread message queue blocking; consider raising the thread_queue_size option (current value: 512)`

I resolved it by increasing -thread_queue_size to 1024 on line 344 in backends.py.

I'm running a static ffmpg5.
`kea@linchpin:~/.local/lib/python3.7/site-packages/yledl$ ffmpeg --version
ffmpeg version N-55540-g63505fc60a-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers`

**Comment by aajanki** [comment]
Thanks for the report and the pull request! I merged your fix.

**Comment by 6b6561** [comment]
Cool! First time that I have ever attempted to tweak anything in git, I
must admit that I where a bit confused about the git process as such,
but it looks like it worked. 

Kim

On 2021-02-01 21:22, Antti Ajanki wrote:

> Thanks for the report and the pull request! I merged your fix. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/aajanki/yle-dl/issues/262#issuecomment-771096501
[2]
