### ISSUE TITLE
Some news URLs do not work

### ISSUE THREAD

**Issue by tpikonen** [aajanki/yle-dl#268]
There are still some news URLs where streams are not found.

Example with video: https://yle.fi/urheilu/3-11861925
Example with audio: https://yle.fi/uutiset/3-11843834

But for example this URL works: https://yle.fi/uutiset/3-11861836

**Comment by aajanki** [comment]
I improved the stream detection code again and these cases now work.

By my count, yle.fi/uutiset uses at least six different ways to embed video/audio content. :astonished:

**Comment by odelma** [comment]
I was wondering if it is a user error or is this kind of page such where the video url detection does not work: https://yle.fi/uutiset/3-12570253

As the error I'm getting: ERROR: Unsupported stream: Required backend not enabled. Try: --backend ffmpeg

**Comment by aajanki** [comment]
That particular video can only be downloaded using [ffmpeg](https://ffmpeg.org/). You should install ffmpeg and then yle-dl should be able to download it.

If you already have ffmpeg installed, it might be that yle-dl can't find it. In that case, use the `--ffmpeg` command line switch to set the location of the ffmpeg application, for example: `yle-dl --ffmpeg /path/to/ffmpeg https://yle.fi/uutiset/3-12570253`

**Comment by odelma** [comment]
Thanks - actually I first tried with ffmpeg but apparently the version was too old. Got it working now 👍
