### ISSUE TITLE
'yle-dl' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by Mistew** [aajanki/yle-dl#271]
When trying to run the command yle-dl (Yle areena link) in the command prompt it said: 'yle-dl' is not recognized as an internal or external command, operable program or batch file. Any solution for this or have i done something wrong while installing?

**Comment by aajanki** [comment]
Most likely, the installation location is not on your command prompt search path. You should be be able to run the program using the full path like this: `~/.local/bin/yle-dl`

To avoid having to type the full path everytime, you can append the directory on the search path. For example, if you are using bash, execute
```
echo export PATH=$PATH:\$HOME/.local/bin >> ~/.bashrc
```

and restart the command prompt.

**Comment by aajanki** [comment]
I have improved the installation instructions and I'm closing this issue.
