### ISSUE TITLE
ERROR: Unsupported stream: Unknown stream flavor

### ISSUE THREAD

**Issue by pekkarr** [aajanki/yle-dl#274]
Downloading https://areena.yle.fi/1-50875269 fails with an error message:
```
$ yle-dl https://areena.yle.fi/1-50875269
yle-dl 20210502: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2021 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

ERROR: Unsupported stream: Unknown stream flavor
```

**Comment by aajanki** [comment]
Thanks for reporting! This seems to be some kind of new video hosting option on Areena.

I made a smal fix to yle-dl to better handle these kind of streams. Yle-dl is now able to extract the stream URL and metadata. However, the video still won't get downloaded. Ffmpeg just outputs lots of error messages like these:
```
[https @ 0x55e503bf9100] HTTP error 403 Forbidden
[hls @ 0x55e5038d64c0] Failed to open segment 0 of playlist 0
```

I'll continue to debug this further.

**Comment by pekkarr** [comment]
The problem seems to be `Range: bytes=0-` HTTP header in the initial request to the stream URL. Ffmpeg uses this header by default. The server returns different looking `index.m3u8` file if the header is included. Also using the header in subsequent requests doesn't seem to matter.

The `Range` header can be disabled in the initial request in ffmpeg by command line option `-seekable 0`. With this modification `yle-dl` is able to download the stream.

**Comment by aajanki** [comment]
An excellent discovery I added the seekable option onto the ffmpeg command line.

**Comment by vervalkon** [comment]
Where exactly is the `-seekable 0` argument supposed to be typed in?
Obviously just `yle-dl -seekable 0 http://areena.yle.fi/1-12345678` doesn't work so

**Comment by aajanki** [comment]
Recent versions of yle-dl already use `-seekable 0` when they call ffmpeg to download a video stream. It's not something that you as an user need to add anywhere.
