### ISSUE TITLE
Season indicator missing from ${episode}

### ISSUE THREAD

**Issue by ExTechOp** [aajanki/yle-dl#275]
Attempting the multi-season download command with yle-dl 20210704:
`% yle-dl --output-template 'All_Creatures_Great_and_Small-${episode}-${title}.mp4' https://areena.yle.fi/1-50744378
`

You end up with filenames like `All_Creatures_Great_and_Small-: E01-: Tervettä järkeä.mp4`, `All_Creatures_Great_and_Small-: E02-: Koiranpäivät.mp4` and so on: missing the season indicators.

**Comment by ExTechOp** [comment]
Looking closer at the YLE page https://areena.yle.fi/1-50744378 it seems the problem is at their end: they haven't organized the series as separate seasons but as a run of 87 consecutive episodes? If this is the reason, I can well see how yle-dl can do nothing about it, and this issue can obviously be closed.

**Comment by aajanki** [comment]
It is like you noticed yourself that Areena does not have seasons for that particular program.
