### ISSUE TITLE
HTTP error 404 Not Found - Multiple Episodes

### ISSUE THREAD

**Issue by B3nihana** [aajanki/yle-dl#276]
Hey, was so happy to find this tool, but looks like I ran into an issue immediately. I tried several different episode, but experience the same issue, a 404. In the debug/verbose log it finds the file and gets the correct metadata, just fails to grab the stream.

$ yle-dl https://areena.yle.fi/1-4265502
yle-dl 20210704: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2021 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

Output file: Muumilaakso: Pikku Myy tuli taloon: S01E01-2019-02-25T00:01.mkv
[https @ 0000023ec5710e00] HTTP error 404 Not Found
https://cdnsecakmi.kaltura.com/p/1955031/sp/195503100/playManifest/entryId/1_y39fkhaq/flavorId/1_6jf9b626/format/applehttp/protocol/https/a.m3u8?uiConfId=43362851&referrer=aHR0cHM6Ly9hcmVlbmEueWxlLmZpLzEtNDI2NTUwMg==&playSessionId=11111111-1111-
1111-1111-111111111111&clientTag=html5:v0.39.4: Server returned 404 Not Found

DEBUG: Detected an HTML5 media
DEBUG: Available flavors:
DEBUG: bitrate: 171, height: 176, width: 320
DEBUG: bitrate: 469, height: 360, width: 640
DEBUG: bitrate: 939, height: 360, width: 640
DEBUG: bitrate: 1537, height: 720, width: 1280
DEBUG: bitrate: 2586, height: 720, width: 1280
DEBUG: bitrate: 4070, height: 1080, width: 1920
DEBUG: max_height: None, max_bitrate: None
DEBUG: Selected flavor: StreamFlavor(media_type='video', height=1080, width=1920, bitrate=4070, streams=[<yledl.backends.HLSBackend object at 0x000002379652
42B0>, <yledl.backends.WgetBackend object at 0x00000237965242E0>])
DEBUG: Now trying downloader ffmpeg
Output file: Ryhmä Hau: Pennut ja pavunvarsi _ Pennut pelastavat serkukset-2021-06-28T07:56.mkv
DEBUG: Executing:
DEBUG: ffmpeg -y -loglevel warning -thread_queue_size 1024 -seekable 0 -strict experimental -stats -i 'https://cdnsecakmi.kaltura.com/p/1955031/sp/195503100
/playManifest/entryId/1_r28hqy92/flavorId/1_kobze7fc/format/applehttp/protocol/https/a.m3u8?uiConfId=43362851&referrer=aHR0cHM6Ly9hcmVlbmEueWxlLmZpLzEtMjIxN
jg0Nw==&playSessionId=11111111-1111-1111-1111-111111111111&clientTag=html5:v0.39.4' -metadata:s:v:0 'description=Kausi 1. Pennut ja pavunvarsi. Rolle näkee
unta jättiläis-Aleksista. / Pennut pelastavat serkukset. Kapteeni Turpon ranskalaisserkku tulee vierailulle ja hankaloittaa lintukuvauksia.' -metadata creat
ion_time=2021-06-28T07:56:53+03:00 -bsf:a aac_adtstoasc -vcodec copy -acodec copy -scodec srt -map '0:p:0:s?' -map 0:p:0:v -map 0:p:0:a -dn 'file:Ryhmä Hau:
 Pennut ja pavunvarsi _ Pennut pelastavat serkukset-2021-06-28T07:56.mkv'
[https @ 000001b9ee080dc0] HTTP error 404 Not Found
https://cdnsecakmi.kaltura.com/p/1955031/sp/195503100/playManifest/entryId/1_r28hqy92/flavorId/1_kobze7fc/format/applehttp/protocol/https/a.m3u8?uiConfId=43
362851&referrer=aHR0cHM6Ly9hcmVlbmEueWxlLmZpLzEtMjIxNjg0Nw==&playSessionId=11111111-1111-1111-1111-111111111111&clientTag=html5:v0.39.4: Server returned 404
 Not Found

**Comment by aajanki** [comment]
Are you by any change located outside of Finland? Some programs in Areena are available only to Finnish web users (and at least https://areena.yle.fi/1-4265502 is one of these restricted programs). If this happens also with programs that are supposed to be viewable everywhere then there is something else going on. 

Can you test downloading the news broadcast: https://areena.yle.fi/1-50627807 ? If you can download it but not some other programs, then it confirms that you are hitting the geo-restraction.

**Comment by B3nihana** [comment]
Yes located outside of Finland and using a VPN. 

I can confirm that the news broadcast downloaded without issue. When I try with VPN disabled I get the warning about not being located in Finland but with the VPN connected I don't get that, just the 404 or SSL errors.

Is this issue happening regardless of VPN?

**Comment by B3nihana** [comment]
Can confirm this appears to be a Windscribe (or Windscribe config issue), changing to another VPN provider did not have these faults.  Closing now!
