### ISSUE TITLE
YLE live 4h or 24h

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#278]
Been using ffmpeg directly with script file to calculate time difference and -live_start_index.
Been working OK for 1-2 yrs but started having problems some months ago, misses segments, audio-video synch.
Mainly the YLE1 program "old finnish B&W movies" at abt 12,xx - 13,yy.
Got the URL using Stream Detector win-firefox extention.

OK, thght I wld try yle-dl but after a while I noticed using the regular yle URL https://areena.yle.fi/tv/suorat/yle-tv1   restricts "backwards time" to 4h !

With "my system" I can do 24 hours backwards using
UU=https://yletv-lh.akamaihd.net/i/yletv1hls_1@103188/master.m3u8

"from the very start" m3u8 file but now problems, ffmpeg skips start segments. Goes thrgh all resolutions..etc

Picking pre-picking from its content the HD 4096 m3u8 file, leaving out after ?rebase.. it works "again"

UU=https://yletv-lh.akamaihd.net/i/yletv1hls_1@103188/index_4096_av-b.m3u8

OKOK, any chance you cld include this in yle-dl_:

the URL link from a text file? or keyword YLE1
time difference as the day, time to start from (yle-dl does "now-then")
Note, yle-dl needs to know if start time is today or yesterday or figure it out itself

Would be nice!

**Comment by gunnar12** [comment]
Strange, been using 10s segments? in my old script?
The more regular YLE-URL that yle-dl can use (4h) seem to use 6s segments..

Too tired to dbl-check and need to reboot myself too

**Comment by aajanki** [comment]
Closing this old issue. The Areena live TV URLs have have changed so I don't think this is relevant anymore.
