### ISSUE TITLE
Just for the fun, 100% python yle-d;? with  Streamlink??

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#279]
Been using that STream Detect and others and then Streamlink for some time.
Obv For non-YLE programs.

Seems possible to add StreamLink as a backend (get rid of ffmpeg??)

**Comment by aajanki** [comment]
New downloaders are in principle good features, but unfortunately I simply don't have time to implement and maintain support for Streamlink or any other new downloader.
