### ISSUE TITLE
Output template not working as expected

### ISSUE THREAD

**Issue by viikonloppu** [aajanki/yle-dl#280]
I have searched in the other issues but none seem to match my issue. I am trying to use the following output template, '${date} - ${program_id} - ${title}' to create filenames like '2021-06-11 - 1-50689700 - Yle Uutiset selkosuomeksi.mkv'
Running 'yle-dl --output-template '${date} - ${program_id} - ${title}' https://areena.yle.fi/1-50689700' produces a filename of '2021-06-11 - -1-50689700 - : Yle Uutiset selkosuomeksi.mkv'
Running the same command with --vfat changes : to _
Ideally what I am trying to do is use the template similarly to youtube-dl and write the exact format that I want. However as it is here, the output template feature is adding an extra hyphen and colon, and extra spaces.
Am I misunderstanding the output template feature and is there any way to get filenames like the above?

**Comment by aajanki** [comment]
The output template will always insert extra separators, so currently it is not possible to do what you want to do.

I'm not sure why I have implemented it like that. It would make more sense if all extra characters would be part of the template string and not inserted automagically. I might change it at some point.

**Comment by aajanki** [comment]
The templating has now been changed to be more intuitive and does not anymore insert extra separators.
