### ISSUE TITLE
Consistent out of sync sound - "Non-monotonous DTS in output stream"

### ISSUE THREAD

**Issue by krokofant** [aajanki/yle-dl#286]
Trying to download https://arenan.yle.fi/1-4000447 I get a bunch of "Non-monotonous DTS in output stream" errors and the resulting file has the sound of of sync.

`yle-dl.exe --vfat --sublang all --maxbitrate best -i SKAM.txt`

Log file attached. The sound

[SKAM_S04E05_download_errors.txt](https://github.com/aajanki/yle-dl/files/6863883/SKAM_S04E05_download_errors.txt)

**Comment by krokofant** [comment]
Seems to have worked with --showurl and using youtube-dl instead.

**Comment by aajanki** [comment]
What is your ffmpeg version? This might be some kind of ffmpeg incompability issue, especially if youtube-dl works.

I'm not able to reproduce this with ffmpeg 4.3.2 (on Linux).

**Comment by krokofant** [comment]
I was using ffmpeg 4.4 and youtube-dl 2021.06.06 (latest) and the latest version of yle-dl.

I get that this might be very hard to troubleshoot, especially with the region locks 😅. Would any more logs help?

**Comment by aajanki** [comment]
Do you get a similar error if you try the same video again or did it happen just once? Does the same error occur also on other videos?

Like you said, this is quite difficult to debug. One thing that might possible help is if you can rerun yle-dl with the `--verbose` flag and attach the verbose log here.

**Comment by krokofant** [comment]
I had the problem consistently on a few retries 10 days ago, but when retrying now it works. 😕
