### ISSUE TITLE
Getting 404 when downloading videos from https://areena.yle.fi

### ISSUE THREAD

**Issue by iroc-1** [aajanki/yle-dl#289]
Hi
I may be missing something obvious, but I'm getting 404 when trying to download videos from https://areena.yle.fi
Live TV is working well, and video is playing properly in my web browser.

I'm using the latest version of the docker container, (I'm on windows, and using a VPN)
docker run --rm -ti -v "%CD%":/out taskinen/yle-dl "https://areena.yle.fi/1-50806587"
and getting the following output

Ohimennen: Donovan-2021-05-12T00:01.mp4 already exists.
Checking if the stream is complete...
WARNING: Failed to get duration for the fileOhimennen: Donovan-2021-05-12T00:01.mp4: Stream probing failed with status 1
Output file: Ohimennen: Donovan-2021-05-12T00:01.mp4
--2021-08-22 17:40:35--  https://cdnsecakmi.kaltura.com/p/1955031/sp/195503100/playManifest/entryId/1_e284lf1d/flavorId/1_1u5mhhbr/format/url/protocol/https/a.mp4?uiConfId=43362851&referrer=aHR0cHM6Ly9hcmVlbmEueWxlLmZpLzEtNTA4MDY1ODc=&playSessionId=11111111-1111-1111-1111-111111111111&clientTag=html5:v0.39.4
Resolving cdnsecakmi.kaltura.com (cdnsecakmi.kaltura.com)... 23.48.181.165, 23.48.181.165
Connecting to cdnsecakmi.kaltura.com (cdnsecakmi.kaltura.com)|23.48.181.165|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-08-22 17:40:37 ERROR 404: Not Found.

Any idea what's going on ?
Thanks

**Comment by iroc-1** [comment]
Ah, looks like the docker image didn't contain the latest version of yle-dl.
After I updated the version manually, everything worked fine :)

**Comment by aajanki** [comment]
Good that updating to the latest version helped.

I assume that you refer to [this Docker image](https://hub.docker.com/r/taskinen/yle-dl/). It seems that it was updated just yesterday, so hopefully it now contains the latest version by default. (The Docker image is not maintained by me.)
