### ISSUE TITLE
MacOS: colon is a prohibited character for file names.

### ISSUE THREAD

**Issue by heikkij** [aajanki/yle-dl#294]
MacOS doesn't like colon in the file names and files should be manually renamed because of that. That's why I would like to have at least option not to have colon in the file names generated by yle-dl.  Eg if I use output-template `${series} ${episode}` result should be something like `Huippu sarja S02E04` (https://discussions.apple.com/thread/7540284)

**Comment by aajanki** [comment]
Yle-dl has the option `--vfat` that replaces colons with underscores in the generated filenames.

The documentation for that option talks about Windows-compatible filenames because I thought that Windows filesystems are the only ones that don't support colons or certain other characters.
