### ISSUE TITLE
link to yle-dl2 in ini filt?

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#305]
link to yle-dl2 in ini file?

I havnt figure out what and how to change, 
any help

**Comment by aajanki** [comment]
I don't understand what you mean. Can you describe in more detail what you are trying to do?

**Comment by gunnar12** [comment]
the compiling and linking ini ptodubes a program yle-dl
yje src is in a directory also named yle-dl

rhis means there are lots of "yle-dl" in the ini and src  files for compiling but one never knows which  one it is, src-directory ot final executable.

which ones are tre executable

PS Whar is even worsem the puthon [togram additionally messes up the golden egg packets with the actual machine code and library stuff bc that too is just "yle-dl"-somethimg

**Comment by aajanki** [comment]
I still don't understand what is the problem you are having. What are you compiling? What is "ini ptodubes"? What is "the file containing main.py" (there is no main.py in the yle-dl source code)? 

I understand that you are saying that there are too many "things" named yle-dl. Can you list them (source code file name and line number)?

How do you propose renaming them?

**Comment by aajanki** [comment]
I'm closing this issue, because I don't understand it.
