### ISSUE TITLE
zero download Haavisto Gas

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#310]
Now downloading from URL 3/403: https://areena.yle.fi/1-62708147
yellow ffmpeg 4.3.1 windos warnings: 
-----------------------------------------------------
[hls @ 00000000005ea380] Could not find codec parameters for stream 4 (Audio: aac ([15][0][0][0] / 0x000F), 0
hannels, fltp): unspecified sample rate
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[hls @ 00000000005ea380] Could not find codec parameters for stream 10 (Audio: aac ([15][0][0][0] / 0x000F), 0
channels, fltp): unspecified sample rate
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[hls @ 00000000005ea380] Could not find codec parameters for stream 16 (Audio: aac ([15][0][0][0] / 0x000F), 0
channels, fltp): unspecified sample rate
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[hls @ 00000000005ea380] Could not find codec parameters for stream 22 (Audio: aac ([15][0][0][0] / 0x000F), 0
channels, fltp): unspecified sample rate
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[hls @ 00000000005ea380] Could not find codec parameters for stream 28 (Audio: aac ([15][0][0][0] / 0x000F), 0
channels, fltp): unspecified sample rate
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Unsupported codec with id 100358 for input stream 2
Unsupported codec with id 100358 for input stream 5
Unsupported codec with id 100358 for input stream 8
Unsupported codec with id 100358 for input stream 11
Unsupported codec with id 100358 for input stream 14
Unsupported codec with id 100358 for input stream 17
Unsupported codec with id 100358 for input stream 20
Unsupported codec with id 100358 for input stream 23
Unsupported codec with id 100358 for input stream 26
Unsupported codec with id 100358 for input stream 29

red ffmpeg error:
-------
Output file: Yle Uutiset suora_ Tsekin ja Suomen ulkoministereiden info_ 2022-06-02T14_31.mkv
[hls @ 0000000000539840] Could not find codec parameters for stream 4 (Audio: aac ([15][0][0][0] / 0x000F), 0

Akso this warning on most downkoads: when a series for an hour or two
-----------------
Unsupported codec with id 100358 for input stream 2
Unsupported codec with id 100358 for input stream 5
Unsupported codec with id 100358 for input stream 8
Unsupported codec with id 100358 for input stream 11
Unsupported codec with id 100358 for input stream 14
Unsupported codec with id 100358 for input stream 17
Unsupported codec with id 100358 for input stream 20
Unsupported codec with id 100358 for input stream 23
Unsupported codec with id 100358 for input stream 26

less often

Now downloading from URL 5/103: https://areena.yle.fi/1-347131
Output file: McLeodin tyttäret_ Tunteet puntarissa_ S03E05-2022-05-05T
[hls @ 000000000045a540] Can't support the subtitle(uri: https://yleka
95503100/serveFlavor/entryId/1_drfezt13/v/1/ev/9/flavorId/1_dy439c3h/n
=st=1654205229~exp=1654291629~acl=/s/fhls/p/1955031/sp/195503100/serve
Id/1_*~hmac=a0d827c15281b7e7f7ab67e289b70574568580ce43f567cec7b16c2786
Unsupported codec with id 100358 for input stream 2
[webvtt @ 0000000003401740] Dropping 172 duplicated subtitle events

**Comment by gunnar12** [comment]
one more if helps


Now downloading from URL 6/103: https://areena.yle.fi/1-4673561
Output file: Kakarat_ Barcelona_ S01E01-2020-01-01T00_01.mkv
[hls @ 000000000040a580] Can't support the subtitle(uri: https://ylekaodamd.akamaized.net/s/fhls/p/1955031/sp/1
95503100/serveFlavor/entryId/1_alcaelga/v/1/ev/84/flavorId/1_calkm3hs/name/a.srt/index.m3u8/index.m3u8?__hdnea_
_=st=1654205475~exp=1654291875~acl=/s/fhls/p/1955031/sp/195503100/serveFlavor/entryId/1_alcaelga/v/*~hmac=d7c58
ac717c476136f70328e81f438c0ed49ae299f52ec3aa65da03fa02ed513)
[hls @ 000000000040a580] Can't support the subtitle(uri: https://ylekaodamd.akamaized.net/s/fhls/p/1955031/sp/1
95503100/serveFlavor/entryId/1_alcaelga/v/1/ev/84/flavorId/1_y77addxw/name/a.srt/index.m3u8/index.m3u8?__hdnea_
_=st=1654205475~exp=1654291875~acl=/s/fhls/p/1955031/sp/195503100/serveFlavor/entryId/1_alcaelga/v/*~hmac=d7c58
ac717c476136f70328e81f438c0ed49ae299f52ec3aa65da03fa02ed513)
[hls @ 000000000040a580] Can't support the subtitle(uri: https://ylekaodamd.akamaized.net/s/fhls/p/1955031/sp/1
95503100/serveFlavor/entryId/1_alcaelga/v/1/ev/84/flavorId/1_cscg0oy7/name/a.srt/index.m3u8/index.m3u8?__hdnea_
_=st=1654205475~exp=1654291875~acl=/s/fhls/p/1955031/sp/195503100/serveFlavor/entryId/1_alcaelga/v/*~hmac=d7c58
ac717c476136f70328e81f438c0ed49ae299f52ec3aa65da03fa02ed513)
Unsupported codec with id 100358 for input stream 2
[webvtt @ 00000000027f3240] Dropping 4 duplicated subtitle events
[webvtt @ 00000000027f4540] Dropping 109 duplicated subtitle events
[webvtt @ 00000000027f5800] Dropping 105 duplicated subtitle events
frame=56604 fps=124 q=-1.0 Lsize= 1100268kB time=00:37:44.20 bitrate=3980.8kbits/s speed=4.95x
Stream saved to Kakarat_ Barcelona_ S01E01-2020-01-01T00_01.mkv

**Comment by aajanki** [comment]
Thanks for reporting. I managed to fix this by instructing ffmpeg to probe the stream further than the default. Looks like that in this particular case ffmpeg needs to read the video for about 10 seconds to detect the stream parameters correctly.
