### ISSUE TITLE
--postprocess. --preprocess disappeared?

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#312]
--postprocess. --preprocess disappeared?

abt to add search if mkv video already exists on whole cmptr using windows "everything" cmd line interface. it has a list of all files by monitoring NTFS MFT directly, one partition in seconds
skip if exists

getting title, duration as args wld be nice
getting output into a string too. like ffmpeg version code
 only reason I use windos

**Comment by aajanki** [comment]
The `--postprocess` should work. Do you get an error when you try to use it?

There is no `--preprocess` argument (and never has been).

To implement what you plan, you can write a script that first calls yle-dl with `--showmetadata` argument and parses the filename from the response, checks if the file exists and finally calls yle-dl without `--showmetadata` if you actually decide to download the video.

**Comment by gunnar12** [comment]
There is no --preprocess/

exactly remembered I wrote my own but too old code now
