### ISSUE TITLE
streamlink warning

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#315]
struggling again:

Warning

On Linux, when not using a virtual environment, it is recommended to install custom python packages like this only for the current user (see the --user parameter below), since system-wide packages can cause conflicts with the system's regular package manager.

Those user-packages will be installed into ~/.local instead of /usr and entry-scripts for running the programs can be found in ~/.local/bin, eg. ~/.local/bin/streamlink.

In order for the command line shell to be able to find these executables, the user's PATH environment variable needs to be extended. This can be done by adding export PATH="${HOME}/.local/bin:${PATH}" to ~/.profile or ~/.bashrc.

**Comment by aajanki** [comment]
This is documented on the README section [3. Fix the search path if necessary](https://github.com/aajanki/yle-dl#3-fix-the-search-path-if-necessary) and also on the [Finnish readme](https://github.com/aajanki/yle-dl/blob/master/README.fi).

Do you have a suggestion how to improve the documentation?

**Comment by aajanki** [comment]
I'm closing this ticket. You can still send ideas on how to improve the documentation if you have any suggestions.
