### ISSUE TITLE
Suggestion: Change naming scheme for downloaded files so that episode number comes earlier

### ISSUE THREAD

**Issue by Solpo** [aajanki/yle-dl#316]
The naming scheme for downloaded TV show episodes right now seems to be %show_title%_%episode_name%episode_number%-%publication/broadcast_time%

This results in the episodes being listed according to the episode title when listing the contents of a directory with ls or dir or basically any file manager. I feel like that really doesn't serve any purpose. So I suggest that in the file naming scheme the episode number would come up right after the show title.

For instance:
Instead of: Au pairit Panamassa_ Tropiikki kutsuu, vamos!_ S01E01-2022-05-25T20_00.mkv
Like this: Au pairit Panamassa_ S01E01_Tropiikki kutsuu, vamos!_2022-05-25T20_00.mkv

**Comment by n2o4** [comment]
Looks like my previous reply got stuck somewhere in limbo.


You can use the `--output-template` switch for this, can't you?

> Instead of: Au pairit Panamassa_ Tropiikki kutsuu, vamos!_ S01E01-2022-05-25T20_00.mkv
> Like this: Au pairit Panamassa_ S01E01_Tropiikki kutsuu, vamos!_2022-05-25T20_00.mkv

`--output-template '${series}_${episode}_${title}_${timestamp}'` should get
what you want.  For persistence stick that into `~/.yledl.conf`.

**Comment by Solpo** [comment]
I didn't know that was possible but yeah, this solves my problem. Thank you 🙏

**Comment by n2o4** [comment]
You can use the `--output-template` switch for this, can't you?

> Instead of: Au pairit Panamassa_ Tropiikki kutsuu, vamos!_ S01E01-2022-05-25T20_00.mkv
> Like this: Au pairit Panamassa_ S01E01_Tropiikki kutsuu, vamos!_2022-05-25T20_00.mkv

`--output-template '${series}_${episode}_${title}_${timestamp}'` should get
what you want.  For persistence stick that into `~/.yledl.conf`.
