### ISSUE TITLE
output template: removing spaces

### ISSUE THREAD

**Issue by 07416** [aajanki/yle-dl#317]
Is removing the whitespace characters from filenames supported? I could process all yle-dl downloads with a script and change spaces to `_` for instance, but then yle-dl could no longer detect the finished downloads (I'm sure there may be other drawbacks).

the special characters at least can be handled:

> `--vfat` Create Windows-compatible filenames

**Comment by aajanki** [comment]
Currently there is no support for removing spaces. I can add support for it in the future.

**Comment by aajanki** [comment]
The git master branch now has `--restrict-filename-no-spaces` option that replaces whitespace with underscores.
