### ISSUE TITLE
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url 

### ISSUE THREAD

**Issue by gbonnema** [aajanki/yle-dl#321]
I am trying to download an episode of the series A-studio on yle because it has subtitles which I can use for studying Finnish. Unfortunately I get the above mentioned error (see title). I do use a VPN located in Finland and youtube recognizes my IP adress as being Finnish. So in theory this should not be geoblocking.

I will add the full text of the refusal after this comment. Can anyone point me in the right direction what I am doing wrong?

**Comment by ernie77** [comment]
You should update to the latest version of yle-dl.

**Comment by aajanki** [comment]
This is solved in the latest version (20220704) as ernie77 said.

Yle recently modified the API for listing episodes, and it started returning 403 to yle-dl. The latest yle-dl version fixes that by switching to a different API that doesn't require authentication.

**Comment by gbonnema** [comment]
Thank you for your response, I am very glad you guys are on top of this and I hope that Yle does not close the loop by requiring authentication everywhere. Thanks!!
