### ISSUE TITLE
Latestepisode option downloads oldest episode

### ISSUE THREAD

**Issue by ernie77** [aajanki/yle-dl#324]
Downloading A-studio or Jälkipörssi with latestepisode option, downloads oldest episode.

yle-dl --latestepisode https://areena.yle.fi/1-1494772

Output file: Jälkipörssi: AKT kuohui vielä jälkipörssissä: 2012-03-06T09:16.mkv

**Comment by aajanki** [comment]
Fixed on the master branch.

There was a bug that caused episodes without season/episode numbers (like your example) to be ordered incorrectly.
