### ISSUE TITLE
ERROR: The specified file cannot be found

### ISSUE THREAD

**Issue by hiikion** [aajanki/yle-dl#327]
cli args:
```
--backend wget --destdir C:\Users\user\Desktop\ --latestepisode --proxy 80.81.243.26:8800 -o plswork https://areena.yle.fi/1-50107839
```
full error:
```
ERROR: Failed to execute wget -O 'C:\Users\user\Desktop\plswork.mp4' --no-use-server-timestamps '--user-agent=Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0' --header 'X-Forwarded-For: 91.156.141.167' --timeout=20 --progress=bar --tries=5 --random-wait --show-progress --continue 'https://cdnsecakmi.kaltura.com/p/1955031/sp/195503100/playManifest/entryId/1_ctu8muwy/flavorId/1_62nr7rpf/format/url/protocol/https/a.mp4?uiConfId=43362851&referrer=aHR0cHM6Ly9hcmVlbmEueWxlLmZpLzEtNTAxMDQzMjg=&playSessionId=11111111-1111-1111-1111-111111111111&clientTag=html5:v1.7.1'
ERROR: The specified file cannot be found
```

tried:
changing backend to ffmpeg 
removing proxy (acsess denied error)
admin cmd

OS:
windows 10 20H2

**Comment by aajanki** [comment]
That error might mean that yle-dl can't run the wget application because it is not found on the search path. Install [wget](https://www.gnu.org/software/wget/) and try again. If you already have wget installed, you can tell yle-dl its location using the `--wget` command line switch.

**Comment by hiikion** [comment]
```
--backend wget --wget C:\Program Files(x86)\GnuWin32\bin --destdir C:\Users\user\Desktop\ --latestepisode --proxy 195.221.251.200:8080 -o plswork https://areena.yle.fi/1-50107839
```
doesent work
```
usage: yle-dl [-h] [-V] [--debug] [-q] [-c FILENAME] [-i FILENAME] [-o FILENAME] [--output-template TEMPLATE] [--pipe] [--destdir DIR] [--create-dirs] [--showurl | --showtitle | --showepisodepage | --showmetadata]
              [--vfat] [--no-resume] [--no-overwrite] [--ratelimit BR] [--proxy URI] [--postprocess CMD] [--sublang LANG] [--metadatalang LANG] [--latestepisode] [--maxbitrate RATE] [--resolution RES] [--startposition S]
              [--duration S] [--preferformat F] [--backend BE] [--ffmpeg PATH] [--ffprobe PATH] [--wget PATH]
              [url]

yle-dl 20220704: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2022 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

...
```

<br><br>

```
--ffmpeg C:\Users\user\Downloads\d\f\bin\ffmpeg.exe --destdir C:\Users\user\Desktop\ --latestepisode --proxy 195.221.251.200:8080 -o plswork https://areena.yle.fi/1-50107839
```
doesent work to
```
Output file: C:\Users\user\Desktop\plswork.mkv
ERROR: ffmpeg or ffprobe not found on PATH.
ERROR: Install ffmpeg, use "--ffmpeg" to set ffmpeg location or use "--backend wget"
```
<br>
tried so much more and nothing worked

**Comment by aajanki** [comment]
### wget

The argument for the `--wget` switch should include the wget exe file (not just the directory). In addition, because the path contains a space, surround it with double quotes (or possibly single quotes? I'm not familiar with the Windows command line.). Also, should there be a white space betweeen "Files" and "(x86)"?

So something like this:

`--wget "C:\Program Files (x86)\GnuWin32\bin\wget.exe"`

### ffmpeg

In addition to `--ffmpeg`, yle-dl might also need to know the location of ffprobe.exe specified by `--ffprobe`. I'm guessing that ffprobe.exe is located in the same folder as ffmpeg.exe.

Try including both of these:

`--ffmpeg C:\Users\user\Downloads\d\f\bin\ffmpeg.exe --ffprobe C:\Users\user\Downloads\d\f\bin\ffprobe.exe`

I will add a note that both `--ffmpeg` and `--ffprobe` are needed in the error message.

**Comment by hiikion** [comment]
Thanks with the help, started working using wget backend. 

but therre is a minor issue: 
when destination file already existst for some reason it spits out
```
ERROR: ffmpeg or ffprobe not found on PATH.
ERROR: Install ffmpeg, use "--ffmpeg" to set ffmpeg location or use "--backend wget".
```
in the end of the error (backend set to wget)

**Comment by aajanki** [comment]
Good to hear that you got the wget backend working!

Thanks for notifying about the spurious ffmpeg error message. There was a bug that caused yle-dl to try to call ffprobe even if you had selected the wget backend. I fixed that so it should not print the error message anymore in the future.
