### ISSUE TITLE
Series download doesn't work, only returns "No streams found"

### ISSUE THREAD

**Issue by dhofverberg** [aajanki/yle-dl#336]
Downloading an entire series doesn't work anymore.  Yle-dl just returns "No streams found". Therefore, options such as --latestepisode doesn't work either.

This command line:
**yle-dl --debug https://arenan.yle.fi/1-4583749**

Returns:
yle-dl 20221111: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2022 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

DEBUG: https://arenan.yle.fi/1-4583749 is an Areena URL
DEBUG: HTTP GET https://arenan.yle.fi/1-4583749
DEBUG: HTTP status code: 200
DEBUG: HTTP response headers:
DEBUG: Content-Type: text/html; charset=utf-8
DEBUG: Transfer-Encoding: chunked
DEBUG: Connection: keep-alive
DEBUG: Date: Mon, 28 Nov 2022 00:14:53 GMT
DEBUG: Cache-Control: max-age=60
DEBUG: X-Powered-By: Next.js
DEBUG: Content-Encoding: gzip
DEBUG: Vary: Cookie,Accept-Encoding
DEBUG: X-Cache: Hit from cloudfront
DEBUG: Via: 1.1 648da69bb4c2221c403be08a06311d98.cloudfront.net (CloudFront)
DEBUG: X-Amz-Cf-Pop: ARN56-P1
DEBUG: X-Amz-Cf-Id: tQk5uYnUdnR_I74s3x8PJgImrsgusPuqw0psREoRPmTTNFXuLDxBTA==
DEBUG: Age: 44
DEBUG: TV playlist
No streams found

Any idea why, and is there a workaround? Downloading single episodes, by using the URL for that particular episode, works fine.

**Comment by aajanki** [comment]
Thanks for reporting! Yle-dl failed to detect episodes on Swedish language pages. That is now fixed on the Github master branch.

As a work around, in case you don't want to update to the development version, you can download Muumit with the latest release using areena.yle.fi address instead of arenan.yle.fi: `yle-dl https://areena.yle.fi/1-4583749`
