### ISSUE TITLE
Videos and audio inside certain news articles are not downloaded.

### ISSUE THREAD

**Issue by laama1** [aajanki/yle-dl#338]
I think yle-dl can find videos and audio inside articles usually.
But this article url gives me no matches. There should be plenty.
(yle-dl version: 20221111)
`yle-dl --debug https://yle.fi/a/74-20010728`

Resulting in 
`requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://player.api.yle.fi/v1/preview/74-20010728.json?lang.....`

This used to work. Has areena changed something?

**Comment by aajanki** [comment]
Yle made some changes on their site and yle-dl got confused.

I just published yle-dl version 20221231. Try to update to the latest version. It should fix this issue.
