### ISSUE TITLE
ERROR: Unsupported URL: https://areena.yle.fi/1-50979212

### ISSUE THREAD

**Issue by navdotnetreqs** [aajanki/yle-dl#339]
Hi and thanks for your contribution!

Any idea why https://areena.yle.fi/1-50979212 fails downloading with error about being unsupported?
I just updated to the most recent version, haven't used yle-dl in a while. Changes in areena?

**Comment by aajanki** [comment]
Hi, that URL is working for me. Can you generate a debug log with the command `yle-dl --debug https://areena.yle.fi/1-50979212` and send it to me? Maybe that helps in figuring out why it doesn't work for you.

**Comment by navdotnetreqs** [comment]
Hi @aajanki and thanks for your reply,

the most peculiar thing happens. Running with no parameters but the url, download failed:
pi@raspberrypi:~ $ youtube-dl https://areena.yle.fi/1-50979212
[generic] 1-50979212: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1-50979212: Downloading webpage
[generic] 1-50979212: Extracting information
ERROR: Unsupported URL: https://areena.yle.fi/1-50979212

However, running with the -debug parameter downloading started and finished ok. 

With parameter --showurl the following url is now returned https://cdnsecakmi.kaltura.com/p/1955031/sp/195503100/playManifest/entryId/1_ps3olg1t/flavorId/1_pf79j0wf/format/applehttp/protocol/https/a.m3u8?uiConfId=43362851&referrer=aHR0cHM6Ly9hcmVlbmEueWxlLmZpLzEtNTA5NzkyMTI=&playSessionId=11111111-1111-1111-1111-111111111111&clientTag=html5:v1.7.1

Having now downloaded the file entirely (using --debug), it even works with no parameters. A few days ago it did not work and just 15 minutes ago it did not work. Though I tunnel all traffic through a vpn server from my router, I have been able to play the documentary from my browser all the time, so it shouldn't have been a vpn issue.

Sorry I wasn't able to provide anything useful, yle-dl works great!
