### ISSUE TITLE
5.1-audio

### ISSUE THREAD

**Issue by Swedie** [aajanki/yle-dl#343]
Just noticed that some shows are marked as having 5.1-audio. Is there a way of getting these. I've tried figuring it out, but without luck.
Is this something that is on the horizon of implementing?

Example: https://arenan.yle.fi/1-63497260

**Comment by Jalle19** [comment]
Noticed the same, e.g. https://arenan.yle.fi/1-62061530

**Comment by Jalle19** [comment]
https://foorumi.hifiharrastajat.org/index.php?threads/yle-areena-ja-5-1-%C3%A4%C3%A4ni.190397/#post-2550393

> YLE vastasi tiedusteluuni:
> "Areenan ääni on perinteinen stereo-ääni. TV lähetyksessä voidaan lähettää HD kanavilla DolbyDigital 5.1 ääntä, tämä tieto myös näkyy Areenassa ohjelman esittelytekstissä.Tästä voi virheellisesti luulla että myös Areenassa on monikanava-ääni."

**Comment by aajanki** [comment]
So no 5.1 audio in Areena after all. I'll close this bug report. Thanks for sharing @Jalle19 !
