### ISSUE TITLE
Problem with downloading https://areena.yle.fi/1-50159645

### ISSUE THREAD

**Issue by METROGROUND** [aajanki/yle-dl#344]
After entering command it says
yle-dl 20230611: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2023 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

Output file: Uutistunnuksia 1959-2013: 2013-02-14T15:19.mkv
Unsupported codec with id 98313 for input stream 2
file:Uutistunnuksia 1959-2013: 2013-02-14T15:19.mkv: Invalid argument
can you help me please?

**Comment by aajanki** [comment]
The "invalid argument" error most likely means that your system doesn't support non-alphabetic characters in the default output filename "Uutistunnuksia 1959-2013: 2013-02-14T15:19.mkv".

If you are on Windows, add `--restrict-filename-no-specials` argument on the yle-dl command line. It will instruct yle-dl to generate filenames without any special characters. You can even try adding `--restrict-filename-no-spaces` to remove spaces from filenames as well.

If that doesn't help, try providing a file name with the argument  `-o test.mkv`. That will override automatic filename generation, so you can use a filename consisting of just letters and digits.

(The "Unsupported codec with id 98313 for input stream 2" is a harmless warning. Areena videos often contain an extra data stream in addition to video and audio streams, and ffmpeg is just saying that it ignores the extra data stream.)

**Comment by METROGROUND** [comment]
@aajanki 
Thank you!
