### ISSUE TITLE
Playlist/soittolista

### ISSUE THREAD

**Issue by ozky84** [aajanki/yle-dl#347]
Onko mahdollista ladata kaikki  videot esim Yle MOT...
Sarjat menee hyvin ladata mutta esim MOT kun se on suositellut ja uusimmat...
Lataa vaan muutaman videon...

**Comment by ozky84** [comment]
Should here use Finnish or English language?

**Comment by aajanki** [comment]
Kaikkien jaksojen lataaminen ei tosiaan näytä onnistuvan koska MOT:n sivu on erilainen kuin muiden sarjojen sivut. Voin yrittää jossain vaiheessa tutkia saisiko latauksen toimimaan kunnolla myös tuollaisilla sivuilla.

**Comment by ozky84** [comment]
Eli sait korjattua tuon? tai toimimaan?
