### ISSUE TITLE
Setting the backend to wget no longer works

### ISSUE THREAD

**Issue by jheino** [aajanki/yle-dl#351]
After upgrading from 20230611 to 20231120, the `--backend wget` argument seems to be ignored and ffmpeg is always used:

```
$ yle-dl --backend wget https://areena.yle.fi/1-1534430
yle-dl 20231120: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2023 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

ERROR: ffmpeg or ffprobe not found on PATH.
ERROR: Install ffmpeg, and use "--ffmpeg" and "--ffprobe" to set the ffmpeg and ffprobe locations
ERROR: or use "--backend wget".
```

**Comment by aajanki** [comment]
I updated the latest yle-dl version to download the same streams the Areena web page is playing. In most cases (always?), the new streams are HLS streams, which can only be downloaded with ffmpeg and not with wget.

I'll see if I can bring back the older MP4 streams as alternative streams for wget. That might not be a long term solutions though. Yle might stop providing those streams now that Areena web page is no longer using them.

**Comment by aajanki** [comment]
I added back the wget-friendly MP4 streams. The fix is currently in the master branch. I will publish a new version with the fix included later this week.
