### ISSUE TITLE
Downloading embedded videos?

### ISSUE THREAD

**Issue by stdedos** [aajanki/yle-dl#356]
Hello there!

Would there be a way to download embedded videos from articles, like e.g. the https://yle.fi/a/74-20036911?

"After discovering the master m3u8", yt-dlp can handle it

**Comment by aajanki** [comment]
Thanks for reporting this! That pages contains a video element type that I hadn't encountered before. I added support for it. The fix is in the master branch now.

**Comment by stdedos** [comment]
On an ... unrelated matter: Would you consider merging with yt-dlp?

They have a more sophisticated _everything_, but OTOH they are "in every home".

**Comment by stdedos** [comment]
> That pages contains a video element type that I hadn't encountered before. I added support for it.

Also you might consider adding the example at readme (since you are listing [all of] your use-cases already)

**Comment by aajanki** [comment]
I don't personally want to spend effort on trying to integrate yle-dl to yt-dlp, but if you or someoe else want to take a stab at it, please go ahead!

Adding an example at readme is  a good idea. I'll do that.
