### ISSUE TITLE
Unknown stream flavour

### ISSUE THREAD

**Issue by ssundell** [aajanki/yle-dl#357]
Planeettamme Maa III's first episode (https://areena.yle.fi/1-67242086) isn't available, it just gives an error

ERROR: Unsupported stream: Unknown stream flavor

Other episodes work fine. Looking at it, the streaming manifest maybe of a different format than before?

```
#EXTM3U
#EXT-X-VERSION:5
#EXT-X-INDEPENDENT-SEGMENTS

[...]
```

**Comment by aajanki** [comment]
Thanks for reporting!

This seems to be a new stream type on Areena. I added support for it. The code on the master branch can now download the first episode.
