### ISSUE TITLE
Feaeture request: Add Yle Areena id code to the filename, batch download an Yle Areena page with videos/"podcasts".

### ISSUE THREAD

**Issue by joonas-foo** [aajanki/yle-dl#364]
Hi and thanks for the excellent program! I've these two suggestions, add Yle Areena id code to the filename so they're more easily identifable, the same way yt-dlp does. 

Second feature request is a batch download function to download an Yle Areena page of videos or "podcasts", download all the programs on that page.

**Comment by aajanki** [comment]
You can add the ID on the filename using the `--output-template` command line switch. For example: `yle-dl --output-template '${program_id}' https://areena.yle.fi/1-1621050`. See `yle-dl --help` for documentation about possible output-template options.

yle-dl should download all episodes on a web page. There are a few pages where batch downloading doesn't currently work. If you encountered a page whereyle-dl doesn't download all episodes, can you post the address of the page?
