### ISSUE TITLE
Expected behaviour/host issue? (mime type, unsupported codec) etc

### ISSUE THREAD

**Issue by DarrenPIngram** [aajanki/yle-dl#365]
When running a native download I frequently see various "advisory" errors, such as those below. I still get a video file, but maybe provided subtitles are then missing (it is difficult to be 100% sure if they existed iyswim at times). But I work on the assumption that the default running might not be flagging errors visibly if there was not a reason. So more fyi in case...

_yle-dl, via homebrew, MacOS, ffmpeg version 7.0.1, yle-dl 20240706)_

Can the "problem" be primarily with older content that maybe YLE has not updated?

```
yle-dl "https://areena.yle.fi/1-2691191"
yle-dl 20240706: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2024 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

mime type is not rfc8216 compliant
[hls @ 0x1547047d0] Can't support the subtitle(uri: https://ylekaodamd.akamaized.net/s/fhls/p/1955031/sp/195503100/serveFlavor/entryId/1_xap96x8a/v/1/ev/8/flavorId/1_w2ehcr6t/name/a.srt/index.m3u8/index.m3u8?__hdnea__=st=1720592758~exp=1720679158~acl=/s/fhls/p/1955031/sp/195503100/serveFlavor/entryId/1_xap96x8a/v/*~hmac=703fda9a01124854d8838297d6cf3faff648b623f97375efc92a47331ee915d8)
Unsupported codec with id 98313 for input stream 2
Unsupported codec with id 98313 for input stream 5
Unsupported codec with id 98313 for input stream 8
Unsupported codec with id 98313 for input stream 11
Unsupported codec with id 98313 for input stream 14
Unsupported codec with id 98313 for input stream 17
Output file: Kylä: 2016-04-18T21:30.mkv
mime type is not rfc8216 compliant
[webvtt @ 0x15c839290] Dropping 181 duplicated subtitle events
size= 1584095KiB time=00:54:12.05 bitrate=3990.4kbits/s speed=41.2x
Stream saved to Kylä: 2016-04-18T21:30.mkv
```
Finnish primary and secondary subtitle existed. Playback OK.

But still, I am not looking for a refund:) I appreciate the work you do on this application! For a number of accessibility reasons in particular it is easier to watch the programmes via your application/my own media player than via the YLE Areena app or use a browser.

I noticed in the recent release notes for yt-dlp that there was support for YLE Areena. Tested with the above programme (it wa a LOT, LOT slower to download that way). No visible errors. It did not download subtitles (nor did I check for any specific command) so I wonder if there is just some back-end older incompatibility or something at YLE?

```
 yt-dlp "https://areena.yle.fi/1-2691191"
[YleAreena] Extracting URL: https://areena.yle.fi/1-2691191
[YleAreena] 1-2691191: Downloading webpage
[YleAreena] 1-2691191: Downloading JSON metadata
[Kaltura] Extracting URL: kaltura:1955031:1_xap96x8a#__youtubedl_smuggle=%7B%22source_url%22%3A+%22https%3A%2F%2Fareena.yle.fi%2F1-2691191%22%7D
[Kaltura] 1_xap96x8a: Downloading video info JSON (Kaltura html5 player)
[Kaltura] 1_xap96x8a: Checking mxf-53043 URL
[Kaltura] 1_xap96x8a: Downloading m3u8 information
[info] 1_xap96x8a: Downloading 1 format(s): mp4-3987
[download] Destination: Kyla-[1_xap96x8a].mp4
[download] 100% of    1.51GiB in 00:06:24 at 4.03MiB/s
```

**Comment by aajanki** [comment]
These are "expected" warnings, or at least they appear even on recent versions of yle-dl and other software. They occur because Areena streams contain features that are not fully supported by ffmpeg. Playback should work despite the warnings, like you noticed.

I haven't been able to silence these warnings without hiding also other potentially important warnings.

yt-dlp uses a different implementation from yle-dl. You should report the slowness as a bug to the yt-dlp project.
