### ISSUE TITLE
spaces or special characters in filename cause errors

### ISSUE THREAD

**Issue by deffener** [aajanki/yle-dl#367]
Downloading Agenttimusikaali (https://areena.yle.fi/1-1816525) for example generates:
```
Output file: Itse Valtiaat: Agenttimusikaali: 2024-03-21T00:01.mkv
mime type is not rfc8216 compliant
[webvtt @ 000002c068953040] Dropping 183 duplicated subtitle events
[out#0/matroska @ 000002c06e27d240] Error opening output file:Itse Valtiaat: Agenttimusikaali: 2024-03-21T00:01.mkv: Invalid argument
Error opening output file file:Itse Valtiaat: Agenttimusikaali: 2024-03-21T00:01.mkv.
Error opening output files: Invalid argument
```
while stating an output name starts downloads normally. Becomes an issue with multiple input urls (given with -i) or series with multiple episodes with such names..

To replicate: download latest, pipx install with python 3.10.11 and run `<yle-dl.exe> https://areena.yle.fi/1-1816525`

**Comment by deffener** [comment]
There is a flag --restrict-filename-no-specials, which solves the problem but is not enabled by default on win10 ?

**Comment by aajanki** [comment]
Yle-dl can automatically apply `--restrict-filename-no-special` if it is installed with some additional packages: `pipx install yle-dl[extra]`. It _should_ work, but I haven't actually tested the auto-detection on Windows.
