### ISSUE TITLE
Failed to execute php

### ISSUE THREAD

**Issue by ndaniel** [aajanki/yle-dl#44]
When running:

yle-dl http://areena.yle.fi/tv/2193829

this error shows:
===================================================
yle-dl 2.3.1: Download media files from ..................
......................
Failed to execute php /usr/local/bin/AdobeHDS.php --manifest http://areenahdfi-vh.akamaihd.net/z/fi/8b/8bf4f83ac43a24d4600e085766d0cd1b_,1008640,2607104,151552,656384,385024,.mp4.csmil/manifest.f4m?hdnea=st=1404481354~exp=1404481474~acl=/z/fi/8b/8bf4f83ac43a24d4600e085766d0cd1b_,1008640,2607104,151552,656384,385024,.mp4.csmil/*~hmac=d74099d4a0205714964a39487e407eb219dffd432137eea81f4e89771e253666&g=ABCDEFGHIJKL&hdcore=3.3.0&plugin=flowplayer-3.3.0.0 --delete --outfile Daaaaaaggggg (16)-2014-07-03Tyyyyyyyy21:30:00.flv
No such file or directory
Subtitles saved to .............
Subtitles saved to ..............
Output file: ..................flv
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
WARNING: HandShake: Type mismatch: client sent 6, server answered 9
INFO: Connected...
ERROR: rtmp server sent error
ERROR: rtmp server requested close

=========================
I get this error when trying to download that specific show. All the other shows can be downloaded just fine!!

**Comment by aajanki** [comment]
I'm closing this issue, because I believe that "No such file or directory" in the error message indicates that either php or AdobeHDS.php is missing. Please reopen, if you think that the underlying reason is something else.
