### ISSUE TITLE
Can't play/stream on any player (yle-dl --showurl)

### ISSUE THREAD

**Issue by ahjolinna** [aajanki/yle-dl#51]
I tested with mplayer "$(yle-dl --showurl http://areena.yle.fi/tv/2409251)"
I couldn't play it in both of mpv and mplayer (v2).
I tested with released latest version(2.4.0).

I'm using chakraOS and I maintain the yle-dl ccr pkgbuild

also cmplayer dev had the same problem, he will add yle-dl support when this is fixed (xylosper/cmplayer#166)

**Comment by aajanki** [comment]
This is because mplayer does not support HTTP Dynamic Streaming (the streaming protocol used by Yle Areena). However, this works:

yle-dl --pipe http://areena.yle.fi/tv/2409251 | mplayer -

I'll update the example in README.

**Comment by ahjolinna** [comment]
@aajanki : that new method did not work for me, nor the cmplayer dev

**Comment by aajanki** [comment]
Do you get any error messages?

Are you able to download that stream into a file without piping to a video player like this `yle-dl http://areena.yle.fi/tv/2409251`?

Do you get a valid video file if you use --pipe and redirect stdout to a file? `yle-dl --pipe http://areena.yle.fi/tv/2409251 > testi.flv`

**Comment by ahjolinna** [comment]
@aajanki : I'm able to download just fine, and "yle-dl --pipe http://areena.yle.fi/tv/2409251 > testi.flv" worked. Here is "yle-dl --pipe http://areena.yle.fi/tv/2409251 | mplayer -" output : http://pastebin.com/kqFhSZbQ

**Comment by aajanki** [comment]
According to Google you sometimes need to give -cache option to mplayer when playing from stdin:

`yle-dl --pipe http://areena.yle.fi/tv/2409251 | mplayer -cache 1024 -`

My mplayer is slightly newer, so updating mplayer or libav might also help.

> MPlayer2 2.0-728-g2c378c7-4+b1 (C) 2000-2012 MPlayer Team
> Compiled against libavutil version 54.3.0
> Compiled against libavcodec version 56.1.0
> Compiled against libavformat version 56.1.0
> Compiled against libswscale version 3.0.0

**Comment by ahjolinna** [comment]
@aajanki : the -cache thing worked with both mpv and mplayer2

**Comment by aajanki** [comment]
Great, I'll include it in the README.
