### ISSUE TITLE
Cookies.txt created when using cmplayer

### ISSUE THREAD

**Issue by ahjolinna** [aajanki/yle-dl#52]
cmplayer got just support for yle-dl, but it seems to create Cookies.txt to home folder, there's nothing about cookie in yle-dl as far as I or the cmplayer dev can see.

I got this: http://pastebin.com/mNDSQSnK
after trying to watch this http://areena.yle.fi/tv/2449056

https://github.com/xylosper/cmplayer/

**Comment by aajanki** [comment]
Cookies.txt is a temporary file created by AdobeHDS.php. AdobeHDS fails to remove the file if it is terminated abnormally. yle-dl now tries to remove Cookies.txt even if AdobeHDS dies with a signal. The check is not completely fail-safe but the file should get deleted in most cases.
