### ISSUE TITLE
Everything gets saved in unusable fragments

### ISSUE THREAD

**Issue by mhuhtala** [aajanki/yle-dl#58]
Since Yle started to serve most of their material at HD resolutions, my yle-dl saves videos in small fragments that are unwatchable. I get files named

*flv.part
*flv.part-Seg1-Frag1
*flv.part-Seg1-Frag2
*flv.part-Seg1-Frag2
...

The first one contains a couple of seconds of video, the rest are apparently garbage, or too small to be playable with e.g. mplayer. The --maxbitrate option seems to have no effect (I tried to force yle-dl to download a low-res file instead of hd). I'm using 2.5.1 and 

rtmpdump-2.4-3.20131205.gitdc76f0a.fc21.x86_64
librtmp-2.4-3.20131205.gitdc76f0a.fc21.x86_64

on Fedora 21.

**Comment by aajanki** [comment]
Let it run until it finishes downloading all the fragments. It should merge the fragments into a usable flv file (and delete the fragment files) in the end.

If it doesn't produce an flv, what happens instead? Is there any error messages or does it just get stuck?

**Comment by mhuhtala** [comment]
I see! I do get a full-size flv file in the end, but there are some problems. Mplayer seems to only play a few seconds from the beginning (the first fragment) and then crash. VLC does play the entire file, but audio is choppy. I'm guessing there's a discontinuity in audio at each fragment merge point.

This fragment business actually kills my way of using yle-dl, which was to play the video while it was downloading, because the in-browser player doesn't cache enough video and is therefore choppy.

**Comment by aajanki** [comment]
You can still play while downloading by using the --pipe switch. It does the merging on the fly:

yle-dl --pipe http://areena.yle.fi/tv/2307123 | vlc -

The streams play fine on VLC on Debian unstable: VLC 2.2.0-rc2 Weatherwax (2.2.0-rc1-118-g22fda39)

**Comment by mhuhtala** [comment]
Thanks for your reply. There still seems to be something wrong with the merging of the fragments. The audio is discontinuous over the merge points and e.g. speech is very difficult to follow.

**Comment by mhuhtala** [comment]
Just noticed that a pass through ffmpeg seems to fix the merged flv file. I just did ffmpeg with -vcodec copy -acodec copy, and got a file that plays in mplayer and vlc without crashing and with continous sound.

**Comment by aajanki** [comment]
I haven't noticed any issues with the audio. The merging is done by AdobeHDS.php. Try to update it to the latest version (php AdobeHDS.php --update).

Alternatively, it is possible to use youtube-dl instead of AdobeHDS.php to do the actual downloading. Install youtube-dl and run `yle-dl --protocol hds:youtubedl ...`

I'm closing this issue, as the merging problems are due to AdobeHDS.php, not yle-dl.
