### ISSUE TITLE
Streaming is not working with mplayer/mpv, Version 2.6.0

### ISSUE THREAD

**Issue by samdoom** [aajanki/yle-dl#59]
Hi

Installed latest version from the zip (2.6.0), also tried 2.5.1.

command: yle-dl --pipe http://areena.yle.fi/tv/2715778 | mpv -
output:

[file] Reading from stdin...
Failed to execute php /usr/local/share/yle-dl/AdobeHDS.php --manifest http://areenahdworld-vh.akamaihd.net/z/world/3a/3ab1cea200423a02d2c391e3db069e37_,928768,145408,599040,362496,.mp4.csmil/manifest.f4m?hdnea=st=1426663622~exp=1426663742~acl=/z/world/3a/3ab1cea200423a02d2c391e3db069e37_,928768,145408,599040,362496,.mp4.csmil/*~hmac=c2e8435d6c64c5bbb922ee7c14adfc798b0e6f3fdb906c7e45ce4d3222a315af&g=ABCDEFGHIJKL&hdcore=3.3.0&plugin=flowplayer-3.3.0.0 --play
No such file or directory
Failed to recognize file format.

**Comment by aajanki** [comment]
The error "Failed to execute php /usr/local/share/yle-dl/AdobeHDS.php" indicates that you are missing either php or AdobeHDS.php or both. Install php from your distro's respository and AdobeHDS.php by running `sudo make install-adobehds` in the yle-dl directory. See yle-dl's README for more information.

**Comment by samdoom** [comment]
Installed php and got rid of the error, but still mplayer/mpv unable to open the stream:
[file] Reading from stdin...
Failed to recognize file format.
Got it working by using --protocol rtmp switch. Thanks for this piece of software: gateway to hw accelerated SMOOTH video playback from Areena.
