### ISSUE TITLE
YLE has reorganized their web site, yle-dl seems not to accept new URLs

### ISSUE THREAD

**Issue by jrintanen** [aajanki/yle-dl#61]
The old Areena is still there, but the URLs are not accepted by yle-dl.

yle-dl http://areena-v3.yle.fi/tv/2449805
yle-dl 2.3.1: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2014 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv2
Unsupported URL http://areena-v3.yle.fi/tv/2449805.
Is this really a Yle video page?

The new Areena has new type of URLs. yle-dl is happy with the URL, but does not find a file behind it.

yle-dl http://areena.yle.fi/1-2449804
yle-dl 2.3.1: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2014 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv2
Can't read http://areena.yle.fi/1-2449804.json: HTTP Error 404: Not Found
Can't read http://areena.yle.fi/1-2449804.json: HTTP Error 404: Not Found

Is this a yle-dl issue that can be fixed?

**Comment by Kynde** [comment]
The urls were fixed on Monday I think. Didn't that patch fix it for you? It worked for me, but I didn't go out of my way testing it, I only tried a few links from old, new and swedish sites.

**Comment by aajanki** [comment]
The new URLs are supported in yle-dl 2.7.0

https://github.com/aajanki/yle-dl/tarball/2.7.0

**Comment by silpol** [comment]
do you mind to push it up at https://launchpad.net/~yle-dl/+archive/ubuntu/release ?

**Comment by aajanki** [comment]
You have to contact the owner of the PPA (https://launchpad.net/~hekkup) and ask him to update the version on launchpad.

**Comment by silpol** [comment]
kiitos
