### ISSUE TITLE
Restructure to be pip-installable

### ISSUE THREAD

**Issue by nanonyme** [aajanki/yle-dl#67]
Please restructure the repo to be pip-installable. Involves at least adding a setup.py into the repo. I recommend making it read your current requirements.txt and put requirements.txt into Manifest.in as include so it will be in a source tarball and putting the yle-dl file into scripts. This should allow doing this with minimal files necessary. The end result is should be publishable to PyPI if wanted

**Comment by aajanki** [comment]
The repo now includes setup.py. I'll consider making the setup.py the preferred installation script (instead of the makefile) after I have tested it a bt more.
