### ISSUE TITLE
yle-dl 2.9.0 fails on OS X – mcrypt missing

### ISSUE THREAD

**Issue by teroyks** [aajanki/yle-dl#68]
After updating yle-dl to 2.9.0 (with brew upgrade), the program fails to run. The error messages I get are:

You have to install and enable the following extension(s) to continue: 'mcrypt'
Failed to import youtube_dl

**Comment by teroyks** [comment]
Installing youtube-dl (see #64) fixed the problem.

**Comment by teroyks** [comment]
Adding mcrypt to the OS X system PHP (5.5) with Homebrew:
https://gist.github.com/teroyks/e0d271e6720eda692456

**Comment by aajanki** [comment]
I included the improved instructions in the README file.
