### ISSUE TITLE
Rtmpdump method no longer working?

### ISSUE THREAD

**Issue by tigert** [aajanki/yle-dl#71]
Something changed in the Areena a few days ago, looks like the rtmpdump-method stopped working, the HDS streams do work however.

I noticed this when the KODI mediacenter plugin (https://github.com/szymex/xbmc-finnish-tv/) did not work anymore (it includes a snapshot of yle-dl, and I think it uses the rtmpdump method to get the streams)

**Comment by aajanki** [comment]
I believe that Yle is discontinuing the support for rtmp streams (only a part of the programs have been available through rtmp anyway). There is nothing yle-dl can do about it. You could contact the plugin author and propose that he updates to the latest version of yle-dl, which downloads HDS streams.
