### ISSUE TITLE
wishlist

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#74]
Been using yle-dl for years, downloaded probably abt 15TByte, I dont even have a TV anymore. THANKS!

However, I always have to make similar simple additions to new versions
1. In addition to --destdir a  --checkdir argument, for yle-dl to check if the file alrdy exists there
2. Lately it takes a list of checkdirs, or better, from a textfile
4. --ask, asks user with time-limited y/n, default no, also beeps,  if it shld download it again,etc
.  (prints size,etc of duplicate as info for user, forced overwrite if size un-normal small, 10-30kB)
5. grabs,prints DURATION from program_info, also helps a lot (to avoid truncated dlds)

6 The final goal,  check if the already existing file is "fully downloaded" by reading last time-stamps, compare it to YLE given duration
(ref rtmpdumps --e continue function, which doesnt wrk very well anyway)
7 command argument for (pre and) post-download program, might be an archiver, log thing, or defrag of the present file, any own "little helper program"
8 small one, if input is a text-file, open it to read a list of links to download.
(easy to drag-drop frm Areena to that file)

Btw, fragmentation (windws) huge problem as both rtmpdump, HDS write single packets to disk, easily giving 10k fragments/file. Solution, Running ultradefrag (with waitque) or similar on file, or moving the file somwhere else.(diff partition, need that checkdir here too)

btw,btw I also put the files in "their own sub-directory" using the first 4 chars of their name and checkdir checks for that too.

Gunnar

PS as needed in HDS too, retry failed getURL attempts a cpl of times before giving up

**Comment by gunnar12** [comment]
PPS the cross-platform BEEP cld be done with --beep argument to a helper-beep program, as the  --pre and --post command

**Comment by aajanki** [comment]
Not overwriting an existing file and comparing the final timestamp to the expected duration and reading URLs from a text file sound useful and I'm planning to implement these at some point (I'll also accept patches for these).

The other suggestions don't fit in with my vision of yle-dl. Things like running pre and post processing scripts and arranging the downloads in subdirectories are better done by somekind of wrapper script or manager application that just uses yle-dl to do the actual downloading.

Regarding the fragmentation you should discuss with the AdobeHDS.php maintainer: https://github.com/K-S-V/Scripts

**Comment by aajanki** [comment]
The latests version now provides an argument -i for reading a list of links to download from a file.

**Comment by gunnar12** [comment]
OK, kiitos. Pitää kokeilla ja katsoa.

Gunnar

PS Olen onnellinen kun -checkdir1,2,3,4  argumenttini toimii, tsekkaa 
löytyykö video jo nissä dirreissä ja HD-llä johon siirrän videot. 
Samalla ne defragmentoituu jos eri ositus.
Ajattelin vielä lisätä CRC-laskenta jokaisesta flv-stä koska täsmälleen 
saman video-ohjelman nimi muuttuu.
Ainakin aika-osa, YLE tekee jotain temppuja muuttamalla viimestä 
sekunti-osa.
(nyt ajan silloin-tällöin omaa CRC-calc-check softa joka etsii 
täsmälleen samat tiedostot CRCn perusteella ja voin deletoida vanhat)

Fragmentointi ilkeä juttu, 1GB video noin 1-20,000kpl 64-128kb pätkissä 
(johtuen tavasta millä php kokoaa ja kirjoittaa fragmentit sisäisesti?, 
rtmpdump audiot vielä pahempia, vaikka käänsin päälle siihen "fiksu" 
simppeli 2-10MB puskurointi, auttoi)

Käytän myöskin ultradefrag kutsuttana php-skriptistä, yksittäinen 
tiedosto ja jää myöskin jonottamaan menossa olevia edellisia defraggeja 
( -Que).
Mutta Wintoosa heittää ruudulle "adm-OK dialogin" jokaisella udefragilla 
paitsi jos poistaa UACn(unidentfied) kokonaan.
Näin tein, en jaksanut sukeltaa siihen sen enempää.

PPS Ärsyttävintä ettei voi helposti tarkistaa automatik onko koko video 
tullut, en ole ehtinyt koodata.
Toinen hauska, YLEN oma tuotanto, A-studio,etc tulee aluksi pienemmällä 
resolutiolla ja parin päivän kuluttua on maks HDef ja tekstitys lisätty.
Olisi mukava jos "upgrade" täyteen resoluutioon automatik, hehe. 
Politiikkojen ja toimittajien naamat näkyy selvemmin kun valehtelevat 
törkeästi.

PPPS YLEstä nähtvsti enkryptattuna pari draamaa-sarjaa. 
HDS-Link-detectori kaivaa tarv tiedot browserista , mutta on kai 
vaikeampi juttu sinulle?
Juu, ja ne lyhyet uutis ja traileri videot jotka on suoraan mp4 
downladattavissa. Olen lisännyt virheilmoituksen

hohoijaa, on tämä hauska, kun harrastaa softallasi 
"media-kriittisyyttä'" tehokkaasti.
YLEn taso on pudonnut melkein FOX tasolle viim 10v aikana, USA ja Putin,jne

**Comment by aajanki** [comment]
These wishlist items have now been implemented:

> grabs,prints DURATION from program_info, also helps a lot (to avoid truncated dlds)

There is now the `--showmeta` switch that prints the duration and other metadata.

> The final goal, check if the already existing file is "fully downloaded" by reading last time-stamps, compare it to YLE given duration

If you use the `--resume` switch, yle-dl checks if the file exists and contain a complete video and avoids redownloading it.

> command argument for (pre and) post-download program

There is the `--postprocess` switch that takes a name of a script file to be executed after a successful download. The script is run with two parameters: the name of the video file and the name of the subtitle file (if there are subtitles). There is an example script in git called `scripts/muxmp4` that converts a downloaded video to MP4 format.

> small one, if input is a text-file, open it to read a list of links to download.

This is implemented as the `-i` switch.

I'm not currently planning to implement other items on your wishlist because I think that they are quite specialized use cases, so I'm closing this issue.
