### ISSUE TITLE
Some programs fail to download

### ISSUE THREAD

**Issue by erlend1** [aajanki/yle-dl#76]
Hello,

Recently some programs have failed to download for me. For example this: http://areena.yle.fi/1-3264041

Judging from the manifest this maybe uses Kaltura-platform? I took a cursory look but couldn't see any straightforward way of dumping these.

**Comment by aajanki** [comment]
Which yle-dl version you are using? yle-dl 2.10.0 should be able to download Kaltura streams.

**Comment by erlend1** [comment]
Sorry! Version 2.8.0. I had made a hard copy of the yle-dl file to ~/bin and didn't notice I was using that. 

The program downloads just fine with latest version. Thanks for the help!
