### ISSUE TITLE
Option to download only subtitles.

### ISSUE THREAD

**Issue by perlop** [aajanki/yle-dl#79]
Hello. 

I am having problems with having mpv play with subtitles when using --pipe option. That's why I though I could get an option to download the subtitles and then tell mpv to open video with those subs.

Any thoughts?

**Comment by aajanki** [comment]
I modified `--pipe` to download subtitles if `--sublang` is also specified (subtitles will not be downloaded if `--pipe` is used without `--sublang`). For example: `yle-dl -o - --sublang fin http://areena.yle.fi/1-2522404 | vlc -`
