### ISSUE TITLE
Automatically mux to better container than flv

### ISSUE THREAD

**Issue by inopia** [aajanki/yle-dl#80]
I find myself often muxing the output `.flv` and `.srt` into `.mp4` container when the `flv` contains compatible codecs like `h.264` and `AAC`.
 
`ffmpeg -i movie.flv -f srt -i movie.fin.srt -codec copy -c:s mov_text movie.mp4`

This helps with playback device compatibility and it is more convenient to have the subtitle stream in the same file with audio and video streams.

It'd be very convenient if `yle-dl` contained support for specifying end container format if user has `ffmpeg` or `avconv` installed.

**Comment by aajanki** [comment]
You can now define a postprocessing script (`--postprocess` argument) that will be called after a video has been downloaded. The script gets called with the names of the video and subtitle files as parameters.

There is an example postprocessing script `scripts/muxmp4` included in the repository that executes your example ffmpeg command.
