### ISSUE TITLE
2.11: Unsupported URL

### ISSUE THREAD

**Issue by jolpe** [aajanki/yle-dl#82]
Hello, I've been using yle-dl for many years. I just did a fresh install of Ubuntu 16.04.1 64 bit, yle-dl and its dependencies as instructed in README.fi. While yle-dl gives no errors, trying any link from Areena results following:

yle-dl https://areena.yle.fi/1-3067335

yle-dl 2.11: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2016 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3
Unsupported URL https://areena.yle.fi/1-3067335.
Is this really a Yle video page?

**Comment by aajanki** [comment]
yle-dl did not handle Areena HTTPS URLs correctly. This is now fixed in a new release 2.12.
