### ISSUE TITLE
AdobeHDS path seems to be hard-coded

### ISSUE THREAD

**Issue by ilmaisin** [aajanki/yle-dl#89]
If I install yle-dl to a custom path, all files go to correct place, but the AdobeHDS path seems to be always `/usr/local/share/yle-dl/AdobeHDS.php`. Yle-dl fails to work until the user manually changes the path in the `yle-dl` executable.

**Comment by Akuli** [comment]
Doesn't the `--adobehds` option work?

**Comment by ilmaisin** [comment]
I haven't tried that because I wasn't aware of the option.

But it's not a very good user experience if you need to specify the installation paths every time you run the program. Could the `os.path.dirname` function or something similar be used to find out the install path? Or maybe edit the correct path to the script using the makefile?

**Comment by harski** [comment]
I maintain a package for Gentoo in my own repository, and what I have done is patch the correct path in during the installation process: `sed -i 's|/usr/local/share/yle-dl/AdobeHDS.php|/usr/share/yle-dl/AdobeHDS.php|g' yle-dl`. This is a hack, though, and ideally you'd want to correct the paths in setup.py according to parameters passed to it.

**Comment by aajanki** [comment]
As a quick work-around, you can define a shell alias to avoid repeating the switch every time: `alias yle-dl2="yle-dl --adobehds /path/to/AdobeHDS.php"`

I agree that it would be nice to setup the correct path in setup.py properly, but this isn't a high priority item for me right now.

**Comment by Akuli** [comment]
The "correct" way to implement this would be using Python's setuptools, and a Python module with an entry point instead of just an executable script.
