### ISSUE TITLE
Update Readme for Areena Html videos

### ISSUE THREAD

**Issue by mulecat** [aajanki/yle-dl#95]
Html videos on Areena can be downloaded with the help of youtube-dl:
`yle-dl --backend youtubedl http://areena.yle.fi/1-1010101`

**Comment by aajanki** [comment]
HTML videos should be downloadable even with the default AdobeHDS backend (or more precisely, yle-dl should detect HTML videos and download them using urllib). Can you give an example that doesn't work with the default configuration?

**Comment by mulecat** [comment]
Sorry, it seems that yle-dl does download videos correctly with default options. In fact, I tried this about a month ago and all (html video) downloads seemed to fail. Yle/Kaltura made some adjustments to videos (js) at some point, could have been that.
